//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AidStorage : NSObject
{
}

+ (double)aidGenTime:(id)arg1;
+ (id)aidValue:(id)arg1;
+ (void)cleanAid:(id)arg1;
+ (void)initialize;
+ (id)instance;
+ (void)setAid:(id)arg1 appName:(id)arg2;

@end

