//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray, UIColor;

@interface AMTumblrHud : UIView
{
    NSMutableArray *hudRects;
    UIColor *_hudColor;
}

- (void).cxx_destruct;
- (void)animateRect:(id)arg1 withDuration:(double)arg2;
- (void)configUI;
- (void)dealloc;
- (void)doAnimateCycleWithRects:(id)arg1;
- (id)drawRectAtPosition:(struct CGPoint)arg1;
- (void)hide;
@property(retain, nonatomic) UIColor *hudColor; // @synthesize hudColor=_hudColor;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)showAnimated:(_Bool)arg1;

@end

