//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class APMAlarm, APMPersistedConfig;

@interface APMSessionReporter : NSObject
{
    APMPersistedConfig *_persistedConfig;
    APMAlarm *_sessionStartTimer;
    APMAlarm *_userEngagementTimer;
    double _engagementStartUptime;
    double _freerideEngagementStartUptime;
    _Bool _reportingEnabled;
    double _minimumSessionInterval;
    double _timeoutSessionInterval;
}

- (void).cxx_destruct;
- (double)currentClockTime;
- (double)currentUptime;
- (long long)cutFreerideEngagementTimeMillis;
- (void)dealloc;
- (_Bool)extendSession;
- (void)handleAppDidBecomeActive;
- (void)handleAppWillResignActiveWithScreen:(id)arg1;
- (void)handleScreenDidChangeFromScreen:(id)arg1 toScreen:(id)arg2;
- (double)incurredEngagementTime;
- (id)initWithPersistedConfig:(id)arg1;
@property(nonatomic, getter=isReportingEnabled) _Bool reportingEnabled; // @synthesize reportingEnabled=_reportingEnabled;
@property(readonly, nonatomic, getter=isSessionExpired) _Bool sessionExpired;
- (void)logAppBackgroundEvent:(long long)arg1;
- (long long)logEngagementEventAndReturnTimeWithScreen:(id)arg1 isRedundant:(_Bool)arg2;
- (void)logSessionStartEvent;
- (void)logUserEngagementEvent;
@property(nonatomic) double minimumSessionInterval; // @synthesize minimumSessionInterval=_minimumSessionInterval;
- (void)rescheduleSessionStartTimer;
- (void)rescheduleUserEngagementTimer;
- (id)sessionIDPropertyWithTimestamp:(double)arg1;
- (id)sessionNumberProperty;
- (void)setSessionID:(id)arg1 withSessionNumber:(id)arg2;
@property(nonatomic) double timeoutSessionInterval; // @synthesize timeoutSessionInterval=_timeoutSessionInterval;
- (_Bool)shouldStartNewSession;
- (void)updatePropertiesForNewSessionStart;

@end

