//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface BLYConsoleLog : NSObject
{
    NSDate *_date;
    NSString *_sender;
    NSString *_messageText;
    long long _messageID;
    NSString *_PID;
}

+ (id)allLogMessagesForCurrentProcess;
+ (id)logContent:(id)arg1;
+ (id)logMessageFromASLMessage:(struct __asl_object_s *)arg1;
+ (id)logs;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *PID; // @synthesize PID=_PID;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(nonatomic) long long messageID; // @synthesize messageID=_messageID;
@property(copy, nonatomic) NSString *messageText; // @synthesize messageText=_messageText;
- (id)searchResultOfLog:(id)arg1;
@property(copy, nonatomic) NSString *sender; // @synthesize sender=_sender;

@end

