//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BLYJCEBaseObject.h"

#import "NSSecureCoding-Protocol.h"

@interface BLYJceObject : BLYJCEBaseObject <NSSecureCoding>
{
}

+ (id)fromData:(id)arg1;
+ (id)jceType;
+ (id)object;
+ (id)objectWithName:(id)arg1 andType:(id)arg2 inAttributes:(id)arg3;
+ (_Bool)supportsSecureCoding;
- (void)__pack:(id)arg1;
- (void)__unpack:(id)arg1;
- (Class)classForCoder;
- (Class)classForKeyedArchiver;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)fromData:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)jceType;
- (void)setInAttributes:(id)arg1 withName:(id)arg2 andType:(id)arg3;
- (id)toData;

@end

