//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BU_AFURLSessionManager.h"

#import "NSCopying-Protocol.h"
#import "NSSecureCoding-Protocol.h"

@class BU_AFHTTPRequestSerializer, BU_AFHTTPResponseSerializer, BU_AFSecurityPolicy, NSURL;
@protocol BU_AFURLRequestSerialization, BU_AFURLResponseSerialization;

@interface BU_AFHTTPSessionManager : BU_AFURLSessionManager <NSSecureCoding, NSCopying>
{
    NSURL *_baseURL;
    BU_AFHTTPRequestSerializer<BU_AFURLRequestSerialization> *_requestSerializer;
}

+ (id)manager;
+ (_Bool)supportsSecureCoding;
- (void).cxx_destruct;
- (id)GET:(id)arg1 parameters:(id)arg2 progress:(CDUnknownBlockType)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)GET:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)POST:(id)arg1 parameters:(id)arg2 constructingBodyWithBlock:(CDUnknownBlockType)arg3 progress:(CDUnknownBlockType)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (id)POST:(id)arg1 parameters:(id)arg2 constructingBodyWithBlock:(CDUnknownBlockType)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)POST:(id)arg1 parameters:(id)arg2 progress:(CDUnknownBlockType)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)POST:(id)arg1 parameters:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
@property(retain, nonatomic) NSURL *baseURL; // @synthesize baseURL=_baseURL;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)dataTaskWithHTTPMethod:(id)arg1 URLString:(id)arg2 parameters:(id)arg3 uploadProgress:(CDUnknownBlockType)arg4 downloadProgress:(CDUnknownBlockType)arg5 success:(CDUnknownBlockType)arg6 failure:(CDUnknownBlockType)arg7;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithBaseURL:(id)arg1;
- (id)initWithBaseURL:(id)arg1 sessionConfiguration:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithSessionConfiguration:(id)arg1;
@property(retain, nonatomic) BU_AFHTTPRequestSerializer<BU_AFURLRequestSerialization> *requestSerializer; // @synthesize requestSerializer=_requestSerializer;
@property(retain, nonatomic) BU_AFHTTPResponseSerializer<BU_AFURLResponseSerialization> *responseSerializer; // @dynamic responseSerializer;
@property(retain, nonatomic) BU_AFSecurityPolicy *securityPolicy; // @dynamic securityPolicy;

@end

