//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

#import "CALayerDelegate-Protocol.h"

@class CADisplayLink, NSMutableDictionary, NSObject, NSOperationQueue, NSString, UIImage;
@protocol OS_dispatch_semaphore, SDAnimatedImage;

@interface BU_SDAnimatedImageView : UIImageView <CALayerDelegate>
{
    NSString *_runLoopMode;
    _Bool _initFinished;
    _Bool _shouldCustomLoopCount;
    _Bool _shouldIncrementalLoad;
    _Bool _clearBufferWhenStopped;
    _Bool _resetFrameIndexWhenStopped;
    _Bool _bufferMiss;
    _Bool _shouldAnimate;
    _Bool _isProgressive;
    UIImage *_currentFrame;
    unsigned long long _currentFrameIndex;
    unsigned long long _currentLoopCount;
    unsigned long long _maxBufferSize;
    unsigned long long _totalFrameCount;
    unsigned long long _totalLoopCount;
    UIImage<SDAnimatedImage> *_animatedImage;
    NSMutableDictionary *_frameBuffer;
    double _currentTime;
    unsigned long long _maxBufferCount;
    NSOperationQueue *_fetchQueue;
    NSObject<OS_dispatch_semaphore> *_lock;
    double _animatedImageScale;
    CADisplayLink *_displayLink;
}

+ (id)defaultRunLoopMode;
- (void).cxx_destruct;
@property(retain, nonatomic) UIImage<SDAnimatedImage> *animatedImage; // @synthesize animatedImage=_animatedImage;
@property(nonatomic) double animatedImageScale; // @synthesize animatedImageScale=_animatedImageScale;
@property(nonatomic) _Bool bufferMiss; // @synthesize bufferMiss=_bufferMiss;
- (void)calculateMaxBufferCount;
@property(nonatomic) _Bool clearBufferWhenStopped; // @synthesize clearBufferWhenStopped=_clearBufferWhenStopped;
- (void)clearFrameBuffer;
- (void)commonInit;
@property(retain, nonatomic) UIImage *currentFrame; // @synthesize currentFrame=_currentFrame;
@property(nonatomic) unsigned long long currentFrameIndex; // @synthesize currentFrameIndex=_currentFrameIndex;
@property(nonatomic) unsigned long long currentLoopCount; // @synthesize currentLoopCount=_currentLoopCount;
@property(nonatomic) double currentTime; // @synthesize currentTime=_currentTime;
- (void)dealloc;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (void)didReceiveMemoryWarning:(id)arg1;
- (void)displayDidRefresh:(id)arg1;
- (void)displayLayer:(id)arg1;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(retain, nonatomic) NSOperationQueue *fetchQueue; // @synthesize fetchQueue=_fetchQueue;
@property(retain, nonatomic) NSMutableDictionary *frameBuffer; // @synthesize frameBuffer=_frameBuffer;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithImage:(id)arg1;
- (id)initWithImage:(id)arg1 highlightedImage:(id)arg2;
- (_Bool)isAnimating;
@property(nonatomic) _Bool isProgressive; // @synthesize isProgressive=_isProgressive;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *lock; // @synthesize lock=_lock;
@property(nonatomic) unsigned long long maxBufferCount; // @synthesize maxBufferCount=_maxBufferCount;
@property(nonatomic) unsigned long long maxBufferSize; // @synthesize maxBufferSize=_maxBufferSize;
- (void)resetAnimatedImage;
- (void)resetCurrentFrameIndex;
@property(nonatomic) _Bool resetFrameIndexWhenStopped; // @synthesize resetFrameIndexWhenStopped=_resetFrameIndexWhenStopped;
- (void)resetProgressiveImage;
@property(copy, nonatomic) NSString *runLoopMode;
- (void)sdBu_setImageWithURL:(id)arg1;
- (void)sdBu_setImageWithURL:(id)arg1 completed:(CDUnknownBlockType)arg2;
- (void)sdBu_setImageWithURL:(id)arg1 placeholderImage:(id)arg2;
- (void)sdBu_setImageWithURL:(id)arg1 placeholderImage:(id)arg2 completed:(CDUnknownBlockType)arg3;
- (void)sdBu_setImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned long long)arg3;
- (void)sdBu_setImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned long long)arg3 completed:(CDUnknownBlockType)arg4;
- (void)sdBu_setImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned long long)arg3 context:(id)arg4;
- (void)sdBu_setImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned long long)arg3 context:(id)arg4 progress:(CDUnknownBlockType)arg5 completed:(CDUnknownBlockType)arg6;
- (void)sdBu_setImageWithURL:(id)arg1 placeholderImage:(id)arg2 options:(unsigned long long)arg3 progress:(CDUnknownBlockType)arg4 completed:(CDUnknownBlockType)arg5;
- (void)setAlpha:(double)arg1;
- (void)setHidden:(_Bool)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setImage:(id)arg1;
@property(nonatomic) _Bool shouldAnimate; // @synthesize shouldAnimate=_shouldAnimate;
@property(nonatomic) _Bool shouldCustomLoopCount; // @synthesize shouldCustomLoopCount=_shouldCustomLoopCount;
@property(nonatomic) _Bool shouldIncrementalLoad; // @synthesize shouldIncrementalLoad=_shouldIncrementalLoad;
@property(nonatomic) unsigned long long totalFrameCount; // @synthesize totalFrameCount=_totalFrameCount;
@property(nonatomic) unsigned long long totalLoopCount; // @synthesize totalLoopCount=_totalLoopCount;
- (void)startAnimating;
- (void)stopAnimating;
- (void)updateIsProgressiveWithImage:(id)arg1;
- (void)updateShouldAnimate;

// Remaining properties
@property(nonatomic) long long animationRepeatCount; // @dynamic animationRepeatCount;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

