//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDateFormatter, NSMutableArray, NSString;
@protocol OS_dispatch_queue;

@interface BUAdLogManager : NSObject
{
    _Bool _hasFirstLogSetup;
    NSObject<OS_dispatch_queue> *_ioQueue;
    NSObject<OS_dispatch_queue> *_logQueue;
    long long _maxFileCount;
    NSMutableArray *_cachMessageArray;
    NSString *_currentFilePath;
    NSDateFormatter *_messageDateFormatter;
}

+ (void)logWithFormat:(id)arg1;
+ (void)logWithFormat:(id)arg1 arguments:(char *)arg2;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)_prx_currentFilePath;
- (id)_prx_currentParentDir;
- (void)_prx_optimizeFileCount;
@property(retain, nonatomic) NSMutableArray *cachMessageArray; // @synthesize cachMessageArray=_cachMessageArray;
@property(copy, nonatomic) NSString *currentFilePath; // @synthesize currentFilePath=_currentFilePath;
- (id)filePathWithFileName:(id)arg1;
@property(nonatomic) _Bool hasFirstLogSetup; // @synthesize hasFirstLogSetup=_hasFirstLogSetup;
- (id)init;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *ioQueue; // @synthesize ioQueue=_ioQueue;
- (id)logFileNameArray;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *logQueue; // @synthesize logQueue=_logQueue;
- (void)logWithMessage:(id)arg1;
@property(nonatomic) long long maxFileCount; // @synthesize maxFileCount=_maxFileCount;
@property(retain, nonatomic) NSDateFormatter *messageDateFormatter; // @synthesize messageDateFormatter=_messageDateFormatter;

@end

