//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BUCacheControl : NSObject
{
}

+ (void)clearAllCache;
+ (void)clearDynamicLayout;
+ (void)clearEventTacker;
+ (void)clearFullscreenVideo;
+ (void)clearNative;
+ (void)clearRewardVideo;
+ (void)clearSetting;
+ (void)clearSplash;
+ (void)clearSplashVideo;
+ (void)crashMessageSend:(id)arg1;
+ (id)sharedInstance;
- (void)dealloc;

@end

