//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextViewDelegate-Protocol.h"

@class NSString, UIButton, UIColor, UILabel, UITextView;

@interface BUDislikeNewRealInputView : UIView <UITextViewDelegate>
{
    CDUnknownBlockType _cancelBlock;
    CDUnknownBlockType _submitBlock;
    UIView *_headerView;
    UIButton *_cancelButton;
    UILabel *_titleLabel;
    UIButton *_submitButton;
    UIView *_lineView;
    UITextView *_textView;
    UILabel *_placeholderLabel;
    UILabel *_countLabel;
    UIColor *_normalTextColor;
    UIColor *_normalButtonColor;
    UIColor *_disableButtonColor;
    UIColor *_lineColor;
    long long _maxInputLength;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
- (void)cancelButtonTouchUpInside:(id)arg1;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) UIColor *disableButtonColor; // @synthesize disableButtonColor=_disableButtonColor;
- (id)disableEmoji:(id)arg1;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(nonatomic) long long maxInputLength; // @synthesize maxInputLength=_maxInputLength;
@property(retain, nonatomic) UIColor *normalButtonColor; // @synthesize normalButtonColor=_normalButtonColor;
@property(retain, nonatomic) UIColor *normalTextColor; // @synthesize normalTextColor=_normalTextColor;
@property(retain, nonatomic) UILabel *placeholderLabel; // @synthesize placeholderLabel=_placeholderLabel;
@property(copy, nonatomic) CDUnknownBlockType submitBlock; // @synthesize submitBlock=_submitBlock;
@property(retain, nonatomic) UIButton *submitButton; // @synthesize submitButton=_submitButton;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)submitButtonTouchUpInside:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

