//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

#import "BUAnimationImageView-Protocol.h"

@class BUGifImage, CADisplayLink;

@interface BUGifImageView : UIImageView <BUAnimationImageView>
{
    _Bool _repeats;
    _Bool _delayDuration;
    CDUnknownBlockType _completionHandler;
    BUGifImage *_gifImage;
    CADisplayLink *_displayLink;
    double _startTime;
    double _duration;
}

- (void).cxx_destruct;
- (void)beginAnimation;
- (void)commonInit;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(nonatomic) long long currentPlayIndex;
- (void)dealloc;
@property(nonatomic) _Bool delayDuration; // @synthesize delayDuration=_delayDuration;
- (void)displayImage:(id)arg1;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(nonatomic) double duration; // @synthesize duration=_duration;
- (void)endAnimation;
@property(retain, nonatomic) BUGifImage *gifImage; // @synthesize gifImage=_gifImage;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithImage:(id)arg1;
- (id)initWithImage:(id)arg1 highlightedImage:(id)arg2;
- (void)removeFromSuperview;
@property(nonatomic) _Bool repeats; // @synthesize repeats=_repeats;
- (void)setImage:(id)arg1;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;

@end

