//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BUNativeExpressAdViewDelegate-Protocol.h"
#import "BUNativeExpressVideoAdDelegate-Protocol.h"
#import "BUVideoAdDelegate-Protocol.h"

@class BUAdSlot, BUDislikeContext, BUNativeAd, BUNativeExpressAdManager, BUNativeExpressRewardedVideoAdView, BURewardedVideoModel, NSDictionary, NSString;
@protocol BUNativeExpressRewardedVideoAdDelegate;

@interface BUNativeExpressRewardedVideoAd : NSObject <BUNativeExpressAdViewDelegate, BUNativeExpressVideoAdDelegate, BUVideoAdDelegate>
{
    _Bool isRewardedVideo;
    _Bool _isShow;
    _Bool _triggerNativeAdDidLoadCallback;
    _Bool _triggerNativeAdDidDownloadCallback;
    BURewardedVideoModel *_rewardedVideoModel;
    id <BUNativeExpressRewardedVideoAdDelegate> _delegate;
    BUNativeExpressAdManager *_nativeExpressAdManager;
    BUNativeExpressRewardedVideoAdView *_expressAdView;
    BUAdSlot *_adSlot;
    BUNativeAd *_purePlayableNativeAd;
    BUDislikeContext *_dislikeContext;
}

- (void).cxx_destruct;
@property(retain, nonatomic) BUAdSlot *adSlot; // @synthesize adSlot=_adSlot;
@property(nonatomic) __weak id <BUNativeExpressRewardedVideoAdDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) BUDislikeContext *dislikeContext; // @synthesize dislikeContext=_dislikeContext;
@property(retain, nonatomic) BUNativeExpressRewardedVideoAdView *expressAdView; // @synthesize expressAdView=_expressAdView;
- (unsigned long long)getNativeExpressVideoAdType;
- (void)handleSuccessLoadForPurePlayableWithNativeAd:(id)arg1;
- (id)initWithSlotID:(id)arg1 rewardedVideoModel:(id)arg2;
@property(readonly, nonatomic, getter=isAdValid) _Bool adValid;
@property(nonatomic) _Bool isRewardedVideo; // @synthesize isRewardedVideo;
@property(nonatomic) _Bool isShow; // @synthesize isShow=_isShow;
- (void)loadAdData;
@property(readonly, copy, nonatomic) NSDictionary *mediaExt;
- (void)nativeExpressAdFailToLoad:(id)arg1 error:(id)arg2;
@property(retain, nonatomic) BUNativeExpressAdManager *nativeExpressAdManager; // @synthesize nativeExpressAdManager=_nativeExpressAdManager;
- (void)nativeExpressAdSuccessToLoad:(id)arg1 views:(id)arg2;
- (void)nativeExpressAdViewDidClick:(id)arg1;
- (void)nativeExpressAdViewDidCloseOtherController:(id)arg1 interactionType:(long long)arg2;
- (void)nativeExpressAdViewRenderFail:(id)arg1 error:(id)arg2;
- (void)nativeExpressAdViewRenderSuccess:(id)arg1;
- (void)nativeExpressVideoAdDidClickSkip;
- (void)nativeExpressVideoAdDidPlayFinishWithError:(id)arg1;
- (void)nativeExpressVideoAdEndcardDidClose;
- (void)nativeExpressVideoAdEndcardWillClose;
- (void)nativeExpressVideoAdServerRewardDidFail;
- (void)nativeExpressVideoAdServerRewardDidSucceedVerify:(_Bool)arg1;
@property(retain, nonatomic) BUNativeAd *purePlayableNativeAd; // @synthesize purePlayableNativeAd=_purePlayableNativeAd;
- (void)purePlayableShow;
@property(retain, nonatomic) BURewardedVideoModel *rewardedVideoModel; // @synthesize rewardedVideoModel=_rewardedVideoModel;
- (void)safeDelegate_nativeExpressRewardedVideoAdCallback;
- (void)safeDelegate_nativeExpressRewardedVideoAdDidDownLoadVideo;
- (void)safeDelegate_nativeExpressRewardedVideoAdDidLoad;
@property(nonatomic) _Bool triggerNativeAdDidDownloadCallback; // @synthesize triggerNativeAdDidDownloadCallback=_triggerNativeAdDidDownloadCallback;
@property(nonatomic) _Bool triggerNativeAdDidLoadCallback; // @synthesize triggerNativeAdDidLoadCallback=_triggerNativeAdDidLoadCallback;
- (_Bool)showAdFromRootViewController:(id)arg1;
- (_Bool)showAdFromRootViewController:(id)arg1 ritScene:(long long)arg2 ritSceneDescribe:(id)arg3;
- (void)videoAdDidClick;
- (void)videoAdDidClickSkip;
- (void)videoAdDidClose;
- (void)videoAdDidPlayFinishWithError:(id)arg1;
- (void)videoAdServerRewardDidFail;
- (void)videoAdServerRewardDidSucceedVerify:(_Bool)arg1;
- (void)videoAdWillClose;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

