//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BUNativeExpressAdView.h"

@class BUReachability, BUTimer, UIImageView;

@interface BUNativeExpressFeedVideoAdView : BUNativeExpressAdView
{
    _Bool _muteSwitch;
    _Bool _isCurrentVideoCompletion;
    _Bool _hasReportBreak;
    _Bool _drawVideo_tapPaused;
    _Bool _last_paused;
    _Bool _codeExecuted;
    BUTimer *_autoPlayTimer;
    BUReachability *_reachability;
    UIImageView *_finishBackgroundView;
    long long _videoAutoPlayType;
    long long _presentationType;
}

- (void).cxx_destruct;
- (void)_initPlayer;
- (void)addNotification;
- (void)appStoreControllerDidAppear:(id)arg1;
- (void)appStoreControllerDidDisappear:(id)arg1;
@property(retain, nonatomic) BUTimer *autoPlayTimer; // @synthesize autoPlayTimer=_autoPlayTimer;
@property(nonatomic) _Bool codeExecuted; // @synthesize codeExecuted=_codeExecuted;
- (void)continuePlay;
- (void)dealloc;
@property(nonatomic) _Bool drawVideo_tapPaused; // @synthesize drawVideo_tapPaused=_drawVideo_tapPaused;
@property(retain, nonatomic) UIImageView *finishBackgroundView; // @synthesize finishBackgroundView=_finishBackgroundView;
- (_Bool)getAutoPlayVideoSwitch;
- (void)handleClickEventInvideo:(id)arg1;
@property(nonatomic) _Bool hasReportBreak; // @synthesize hasReportBreak=_hasReportBreak;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)innerContinuePlay;
- (void)innerPause;
- (void)innerPlay;
@property(nonatomic) _Bool isCurrentVideoCompletion; // @synthesize isCurrentVideoCompletion=_isCurrentVideoCompletion;
- (_Bool)isDrawVideo;
@property(nonatomic) _Bool last_paused; // @synthesize last_paused=_last_paused;
@property(nonatomic) _Bool muteSwitch; // @synthesize muteSwitch=_muteSwitch;
- (void)pause;
- (void)play;
- (void)player:(id)arg1 stateDidChanged:(long long)arg2;
- (void)playerDidPlayFinish:(id)arg1 error:(id)arg2;
- (void)playerReadyToPlay:(id)arg1;
- (void)playerSeekToTime:(double)arg1;
@property(nonatomic) long long presentationType; // @synthesize presentationType=_presentationType;
@property(retain, nonatomic) BUReachability *reachability; // @synthesize reachability=_reachability;
- (void)receiveEnterBackgroundNotification;
- (void)receiveWillEnterForegroundNotification;
- (void)recordCurrentTapPaused;
- (void)registregistReachability;
- (void)replay;
- (void)resetCurrentTapPaused;
- (void)setNativeAd:(id)arg1;
- (void)setSettingConfig:(id)arg1;
@property(nonatomic) long long videoAutoPlayType; // @synthesize videoAutoPlayType=_videoAutoPlayType;
- (_Bool)shouldAutoPlay;
- (void)startPlayVideo;
- (void)stop;
- (void)tick:(id)arg1;
- (void)videoInfoSetting;

@end

