//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BUWebViewController.h"

#import "BURewardedVideoWebDefaultViewDelegate-Protocol.h"

@class BUMaterialMeta, BURewardedVideoWebDefaultView, BUTimer, BUURitSetingModel, MPVolumeView, NSString, UIButton, UISlider;
@protocol BURewardedVideoWebViewDelegate;

@interface BURewardedVideoWebViewController : BUWebViewController <BURewardedVideoWebDefaultViewDelegate>
{
    _Bool _isTransform;
    _Bool _isRewardedVideo;
    _Bool _mute;
    _Bool _hiddenEndCardClose;
    _Bool _isLandscape;
    _Bool _supportLandscapeOnly;
    _Bool _isNativeExpress;
    _Bool _isMuteBtnTap;
    _Bool _isBtnChangeVolume;
    _Bool _codeOnceChangeOnceFlag;
    _Bool _isRenderSuc;
    _Bool _viewHasShown;
    id <BURewardedVideoWebViewDelegate> _delegate;
    unsigned long long _transformDirection;
    BUMaterialMeta *_materialMeta;
    NSString *_ritScene;
    UIButton *_closeButton;
    UIButton *_superVCCloseBtn;
    BUTimer *_closeTimer;
    BUURitSetingModel *_ritModel;
    BURewardedVideoWebDefaultView *_defaultView;
    long long _VCLifeCycleStatus;
    double _showTime;
    UISlider *_volumeViewSlider;
    double _originalVolumeValue;
    double _lastVolumeValue;
    MPVolumeView *_volumeView;
    UIButton *_silentButton;
    UIButton *_dislikeButton;
    struct CGSize _originSize;
}

- (void).cxx_destruct;
@property(nonatomic) long long VCLifeCycleStatus; // @synthesize VCLifeCycleStatus=_VCLifeCycleStatus;
- (void)addAccessibilityIdentifier;
- (void)addVolumeMonitor;
- (void)appDidEnterBackgroundNotification:(id)arg1;
- (void)appWillEnterForegroundNotification:(id)arg1;
- (void)appendNativeExpressOrientation;
- (void)appendURLParameters;
- (void)buildWebviewFrame;
- (id)c_xyDict;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) BUTimer *closeTimer; // @synthesize closeTimer=_closeTimer;
@property(nonatomic) _Bool codeOnceChangeOnceFlag; // @synthesize codeOnceChangeOnceFlag=_codeOnceChangeOnceFlag;
- (void)codeOnceChangeVolume:(double)arg1 updateVolumeState:(_Bool)arg2;
- (void)dealloc;
@property(retain, nonatomic) BURewardedVideoWebDefaultView *defaultView; // @synthesize defaultView=_defaultView;
@property(nonatomic) __weak id <BURewardedVideoWebViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didReceiveMemoryWarning;
@property(retain, nonatomic) UIButton *dislikeButton; // @synthesize dislikeButton=_dislikeButton;
- (void)dislikeButtonTapped:(id)arg1;
- (void)downloadButtonTapped:(id)arg1 extraDic:(id)arg2;
- (void)eventReloadTrackMethod;
- (double)getDislikeButtonWidthWithStr:(id)arg1;
- (id)getTrackTag;
- (void)handleError:(id)arg1;
@property(nonatomic) _Bool hiddenEndCardClose; // @synthesize hiddenEndCardClose=_hiddenEndCardClose;
- (id)initViewControllerWithAd:(id)arg1 isNativeExpress:(_Bool)arg2;
@property(nonatomic) _Bool isBtnChangeVolume; // @synthesize isBtnChangeVolume=_isBtnChangeVolume;
@property(nonatomic) _Bool isLandscape; // @synthesize isLandscape=_isLandscape;
@property(nonatomic) _Bool isMuteBtnTap; // @synthesize isMuteBtnTap=_isMuteBtnTap;
@property(nonatomic) _Bool isNativeExpress; // @synthesize isNativeExpress=_isNativeExpress;
- (_Bool)isPlayableH5;
@property(nonatomic) _Bool isRenderSuc; // @synthesize isRenderSuc=_isRenderSuc;
@property(nonatomic) _Bool isRewardedVideo; // @synthesize isRewardedVideo=_isRewardedVideo;
@property(nonatomic) _Bool isTransform; // @synthesize isTransform=_isTransform;
@property(nonatomic) double lastVolumeValue; // @synthesize lastVolumeValue=_lastVolumeValue;
- (void)layoutSubViewsForNativeExpress;
@property(retain, nonatomic) BUMaterialMeta *materialMeta; // @synthesize materialMeta=_materialMeta;
@property(nonatomic) _Bool mute; // @synthesize mute=_mute;
@property(nonatomic) struct CGSize originSize; // @synthesize originSize=_originSize;
@property(nonatomic) double originalVolumeValue; // @synthesize originalVolumeValue=_originalVolumeValue;
- (void)registerJSB_Plugin;
- (void)reportDownloadButtonClickTrackExtraDic:(id)arg1;
@property(retain, nonatomic) BUURitSetingModel *ritModel; // @synthesize ritModel=_ritModel;
@property(copy, nonatomic) NSString *ritScene; // @synthesize ritScene=_ritScene;
- (void)sendTrackDataWithParameters:(id)arg1;
- (void)setAdSlot:(id)arg1;
@property(nonatomic) double showTime; // @synthesize showTime=_showTime;
@property(retain, nonatomic) UIButton *silentButton; // @synthesize silentButton=_silentButton;
@property(nonatomic) __weak UIButton *superVCCloseBtn; // @synthesize superVCCloseBtn=_superVCCloseBtn;
@property(nonatomic) _Bool supportLandscapeOnly; // @synthesize supportLandscapeOnly=_supportLandscapeOnly;
@property(nonatomic) unsigned long long transformDirection; // @synthesize transformDirection=_transformDirection;
- (void)setUpSystemVolume;
@property(nonatomic) _Bool viewHasShown; // @synthesize viewHasShown=_viewHasShown;
@property(retain, nonatomic) MPVolumeView *volumeView; // @synthesize volumeView=_volumeView;
@property(retain, nonatomic) UISlider *volumeViewSlider; // @synthesize volumeViewSlider=_volumeViewSlider;
- (void)showCloseButton;
- (void)showCloseCountDown;
- (void)silentButtonTapped:(id)arg1;
- (void)startInterceptRequest;
- (void)supportLandscape;
- (void)trackLoadFinish;
- (void)updateDislikeButtonFrame;
- (void)updateVolumState:(_Bool)arg1;
- (_Bool)useCache;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)webCloseButtonTapped;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

