//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BUSecGuardManager : NSObject
{
    NSString *_device_id;
    NSString *_dc;
    id _SGMSafeGuardManager;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) id SGMSafeGuardManager; // @synthesize SGMSafeGuardManager=_SGMSafeGuardManager;
- (id)bodyEncry:(id)arg1;
- (_Bool)canAddPrivacy;
@property(copy, nonatomic) NSString *dc; // @synthesize dc=_dc;
@property(copy, nonatomic) NSString *device_id; // @synthesize device_id=_device_id;
- (_Bool)respondsToSelector:(SEL)arg1;
- (void)sendDid;
- (id)sgm_appKey;
- (id)sgm_customDeviceID;
- (id)sgm_customInfoDic;
- (id)sgm_hostType;
- (id)sgm_hostVersion;
- (id)sgm_idfa;
- (id)sgm_installChannel;
- (id)sgm_sessionID;
- (void)startSecGuard;

@end

