//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class CADisplayLink, NSDate;

@interface BUSkipButton : UIButton
{
    CDUnknownBlockType _timeOut;
    CADisplayLink *_displayLinkTimer;
    NSDate *_beginTimeStamp;
    double _countdownTimeInterval;
}

- (void).cxx_destruct;
- (void)beginCountDown:(double)arg1;
@property(retain, nonatomic) NSDate *beginTimeStamp; // @synthesize beginTimeStamp=_beginTimeStamp;
@property(nonatomic) double countdownTimeInterval; // @synthesize countdownTimeInterval=_countdownTimeInterval;
@property(retain, nonatomic) CADisplayLink *displayLinkTimer; // @synthesize displayLinkTimer=_displayLinkTimer;
- (id)initWithFrame:(struct CGRect)arg1;
@property(copy, nonatomic) CDUnknownBlockType timeOut; // @synthesize timeOut=_timeOut;
- (void)stopCoutDown;
- (void)tick:(id)arg1;
- (void)updateText:(double)arg1;

@end

