//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber;

@interface BUSplashloadModel : NSObject
{
    long long _adLogStateType;
    NSNumber *_loadLocalImageSuccess;
}

- (void).cxx_destruct;
@property(nonatomic) long long adLogStateType; // @synthesize adLogStateType=_adLogStateType;
@property(retain, nonatomic) NSNumber *loadLocalImageSuccess; // @synthesize loadLocalImageSuccess=_loadLocalImageSuccess;

@end

