//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BUUser : NSObject
{
    NSString *_phone;
    NSString *_keywords;
    NSString *_data;
    long long _coppa;
    long long _is_gdpr_user;
    long long _gdpr;
}

- (void).cxx_destruct;
@property(nonatomic) long long coppa; // @synthesize coppa=_coppa;
@property(copy, nonatomic) NSString *data; // @synthesize data=_data;
- (id)dictionaryValue;
@property(nonatomic) long long gdpr; // @synthesize gdpr=_gdpr;
@property(nonatomic) long long is_gdpr_user; // @synthesize is_gdpr_user=_is_gdpr_user;
@property(copy, nonatomic) NSString *keywords; // @synthesize keywords=_keywords;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;

@end

