//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString;

@interface BUVolumeMonitor : NSObject
{
    _Bool _forMuteBlock;
    _Bool _forRealVolumeBlock;
    CDUnknownBlockType _muteBlock;
    CDUnknownBlockType _realVolumeBlock;
    CDUnknownBlockType _volumeChangeBlock;
    NSDate *_beginPlayDate;
    NSString *_originalCategory;
}

+ (id)defaultMonitor;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *beginPlayDate; // @synthesize beginPlayDate=_beginPlayDate;
- (void)endVolumeMonitor;
@property(nonatomic) _Bool forMuteBlock; // @synthesize forMuteBlock=_forMuteBlock;
@property(nonatomic) _Bool forRealVolumeBlock; // @synthesize forRealVolumeBlock=_forRealVolumeBlock;
- (void)monitorMute;
@property(copy, nonatomic) CDUnknownBlockType muteBlock; // @synthesize muteBlock=_muteBlock;
@property(copy, nonatomic) NSString *originalCategory; // @synthesize originalCategory=_originalCategory;
- (void)playToEnd;
@property(copy, nonatomic) CDUnknownBlockType realVolumeBlock; // @synthesize realVolumeBlock=_realVolumeBlock;
@property(copy, nonatomic) CDUnknownBlockType volumeChangeBlock; // @synthesize volumeChangeBlock=_volumeChangeBlock;
- (void)startVolumeMonitor;
- (void)volumeChangeNotification:(id)arg1;

@end

