//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface checkVersionManager : NSObject
{
    NSDictionary *_infoDict;
}

+ (void)checkNewEditionWithAppID:(id)arg1 CustomAlert:(CDUnknownBlockType)arg2;
+ (void)checkNewEditionWithAppID:(id)arg1 ctrl:(id)arg2;
+ (id)shareManager;
- (void).cxx_destruct;
- (void)checkNewVersion:(id)arg1 ctrl:(id)arg2;
- (void)getAppStoreInfo:(id)arg1 success:(CDUnknownBlockType)arg2;
- (void)getAppStoreVersion:(id)arg1 sucess:(CDUnknownBlockType)arg2;
- (void)ignoreNewVersion:(id)arg1;
@property(retain, nonatomic) NSDictionary *infoDict; // @synthesize infoDict=_infoDict;
- (_Bool)isEqualEdition:(id)arg1;
- (void)updateRightNow:(id)arg1;

@end

