//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSCalendar, NSDate, NSDateFormatter;

@interface DateManager : NSObject
{
    NSDateFormatter *_format;
    NSCalendar *_calender_CN;
    NSDate *_todayDate;
}

+ (id)share;
- (void).cxx_destruct;
@property(retain, nonatomic) NSCalendar *calender_CN; // @synthesize calender_CN=_calender_CN;
- (id)conversionTimeStamp:(id)arg1;
- (id)conversionTimeStampVer2:(id)arg1;
@property(readonly, nonatomic) NSDate *currentDate;
@property(readonly, nonatomic) long long currentWeek;
- (id)dateByTodayAddingDays:(long long)arg1;
@property(readonly, nonatomic) NSDateFormatter *format; // @synthesize format=_format;
- (id)init;
@property(retain, nonatomic) NSDate *todayDate; // @synthesize todayDate=_todayDate;
- (id)timeStampWithDate:(id)arg1;
- (id)timeWithTimeStamp:(long long)arg1;

@end

