//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface EBAppLogBaseTable : NSObject
{
    NSString *_tableName;
}

+ (id)dataBasePathComponent;
+ (id)sharedDatabaseQueue;
+ (id)tableWithName:(id)arg1;
- (void).cxx_destruct;
- (id)allTracks;
- (id)bd_JSONRepresentation:(id)arg1;
- (id)bd_JSONValueForString:(id)arg1;
- (void)checkDBFile;
- (id)createTableSql;
- (id)init;
- (id)initWithTableName:(id)arg1;
- (id)insertSql;
- (void)insertTrack:(id)arg1;
- (void)insertTrack:(id)arg1 trackID:(id)arg2;
- (void)removeTracksByID:(id)arg1;
@property(copy, nonatomic) NSString *tableName; // @synthesize tableName=_tableName;

@end

