//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface EBAppLogDeviceHelper : NSObject
{
}

+ (id)IDFAString;
+ (id)IDFVString;
+ (id)currentLanguage;
+ (id)currentRegion;
+ (id)currentSystemLanguage;
+ (id)decivceModel;
+ (id)fetchOpenUDIDFromKeychain;
+ (_Bool)isJailBroken;
+ (id)machineModel;
+ (id)openUDID;
+ (id)platformName;
+ (struct CGSize)resolution;
+ (id)resolutionString;
+ (void)saveOpenUDIDToKeychain:(id)arg1;
+ (double)screenScale;
+ (id)systemVersion;
+ (id)timeZoneName;
+ (long long)timeZoneOffset;

@end

