//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface EncryptString : NSObject
{
}

- (unsigned char)GDTfunctionh23kIY;
- (unsigned char)GDTfunctionh60LPH;
- (unsigned char)GDTfunctionk8ZpK1;
- (int)GDTfunctiono8ZWML;
- (int)GDTfunctionp1HLjZ;
- (int)GDTfunctionp6SVKO;
- (id)GDTfunctiont1U5Yw:(id)arg1 withSeed:(long long)arg2 withContent:(id)arg3;
- (id)GDTfunctionu7jkQa:(id)arg1 withSeed:(long long)arg2 withContent:(id)arg3;
- (id)GDTfunctionx3sZ3k:(id)arg1;
- (unsigned char)GDTfunctionx84ask;
- (int)X__WC__;
- (id)base64StringWithData:(id)arg1;
- (id)encryptWithMuid:(id)arg1 withSeed:(long long)arg2 withContent:(id)arg3;

@end

