//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GADResponseInfo, NSString;

@interface GADAdRenderingMetadata : NSObject
{
    NSString *_adNetworkClassName;
    GADResponseInfo *_responseInfoOverride;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *adNetworkClassName; // @synthesize adNetworkClassName=_adNetworkClassName;
- (id)initWithAdNetworkClassName:(id)arg1;
@property(retain, nonatomic) GADResponseInfo *responseInfoOverride; // @synthesize responseInfoOverride=_responseInfoOverride;

@end

