//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDecimalNumber, NSString;

@interface GADAdValue : NSObject <NSCopying>
{
    long long _precision;
    NSDecimalNumber *_value;
    NSString *_currencyCode;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) NSString *currencyCode; // @synthesize currencyCode=_currencyCode;
- (id)description;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithValue:(id)arg1 currencyCode:(id)arg2 precision:(long long)arg3;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) long long precision; // @synthesize precision=_precision;
@property(readonly, nonatomic) NSDecimalNumber *value; // @synthesize value=_value;

@end

