//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GADAdLoaderOptions.h"

@interface GADNativeMuteThisAdLoaderOptions : GADAdLoaderOptions
{
    _Bool _customMuteThisAdRequested;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
@property(nonatomic) _Bool customMuteThisAdRequested; // @synthesize customMuteThisAdRequested=_customMuteThisAdRequested;
- (id)init;
- (id)requestParameters;

@end

