//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GADOMIDVASTProperties : NSObject
{
    _Bool _skippable;
    _Bool _autoPlay;
    double _skipOffset;
    unsigned long long _position;
}

- (id)initWithAutoPlay:(_Bool)arg1 position:(unsigned long long)arg2;
- (id)initWithSkipOffset:(double)arg1 autoPlay:(_Bool)arg2 position:(unsigned long long)arg3;
- (id)initWithSkippable:(_Bool)arg1 skipOffset:(double)arg2 autoPlay:(_Bool)arg3 position:(unsigned long long)arg4;
@property(readonly, nonatomic, getter=isAutoPlay) _Bool autoPlay; // @synthesize autoPlay=_autoPlay;
@property(readonly, nonatomic, getter=isSkippable) _Bool skippable; // @synthesize skippable=_skippable;
@property(readonly, nonatomic) unsigned long long position; // @synthesize position=_position;
- (id)positionString;
@property(readonly, nonatomic) double skipOffset; // @synthesize skipOffset=_skipOffset;
- (id)toJSON;

@end

