//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADAdRendering-Protocol.h"
#import "GADMediationNativeAdEventDelegate-Protocol.h"

@class GADAdRenderingMetadata, GADInternalNativeAd, GADMediationNativeAdConfiguration, NSString;
@protocol GADMediationAdapter, GADMediationNativeAd;

@interface GADRTBMediationNativeAdRenderer : NSObject <GADMediationNativeAdEventDelegate, GADAdRendering>
{
    id <GADMediationAdapter> _loadingAdapter;
    id <GADMediationNativeAd> _mediatedAd;
    GADInternalNativeAd *_internalNativeAd;
    GADMediationNativeAdConfiguration *_mediationConfiguration;
    GADAdRenderingMetadata *_metadata;
}

- (void).cxx_destruct;
- (id)adEventDelegateForNativeAd:(id)arg1 adapter:(id)arg2 adConfiguration:(struct NSDictionary *)arg3 transaction:(id)arg4 renderCompletionHandler:(CDUnknownBlockType)arg5;
- (void)didDismissFullScreenView;
- (void)didEndVideo;
- (void)didFailToPresentWithError:(id)arg1;
- (void)didMuteVideo;
- (void)didPauseVideo;
- (void)didPlayVideo;
- (void)didUnmuteVideo;
- (void)renderWithServerTransaction:(id)arg1 adConfiguration:(struct NSDictionary *)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)reportClick;
- (void)reportImpression;
- (void)willBackgroundApplication;
- (void)willDismissFullScreenView;
- (void)willPresentFullScreenView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

