//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableDictionary;

@interface GADRewardBasedVideoAdController : NSObject
{
    NSMutableDictionary *_connectors;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *connectors; // @synthesize connectors=_connectors;
- (void)createConnectorForAdapter:(id)arg1 withAdConfiguration:(struct NSDictionary *)arg2 renderer:(id)arg3;
- (id)init;
- (void)removeConnectorForAdapterName:(id)arg1;

@end

