//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GADInternalNativeAd, GADMediaContent, GADNativeAdImage, GADObserverCollection, GADResponseInfo, GADVideoController, NSArray, NSDecimalNumber, NSDictionary, NSString, UIView, UIViewController;
@protocol GADUnifiedNativeAdDelegate, GADUnifiedNativeAdUnconfirmedClickDelegate;

@interface GADUnifiedNativeAd : NSObject
{
    GADObserverCollection *_adObservers;
    _Bool _mediaContentStatusReported;
    _Bool _mediaContentRendered;
    UIView *_adChoicesContentView;
    _Bool _adMutedReported;
    _Bool _customClickGestureEnabledByPublisher;
    id <GADUnifiedNativeAdUnconfirmedClickDelegate> _unconfirmedClickDelegate;
    _Bool _customClickGestureEnabled;
    GADMediaContent *_mediaContent;
    id <GADUnifiedNativeAdDelegate> _delegate;
    UIViewController *_rootViewController;
    GADResponseInfo *_responseInfo;
    CDUnknownBlockType _paidEventHandler;
    GADVideoController *_videoController;
    GADInternalNativeAd *_internalNativeAd;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIView *adChoicesContentView;
@property(readonly, nonatomic) GADNativeAdImage *adChoicesIcon;
- (void)adIsMuted;
@property(readonly, copy, nonatomic) NSString *adNetworkClassName;
@property(readonly, copy, nonatomic) NSString *advertiser;
@property(readonly, copy, nonatomic) NSString *body;
@property(readonly, copy, nonatomic) NSString *callToAction;
- (void)cancelUnconfirmedClick;
- (void)dealloc;
@property(nonatomic) __weak id <GADUnifiedNativeAdDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didCancelUnconfirmedClick;
- (void)enableCustomClickGestures;
@property(readonly, copy, nonatomic) NSDictionary *extraAssets;
@property(readonly, copy, nonatomic) NSString *headline;
@property(readonly, nonatomic) GADNativeAdImage *icon;
@property(readonly, nonatomic) NSArray *images;
- (id)init;
- (id)initWithInternalNativeAd:(id)arg1 responseInfo:(id)arg2;
- (id)internalMediaContent;
@property(readonly, nonatomic) GADInternalNativeAd *internalNativeAd; // @synthesize internalNativeAd=_internalNativeAd;
- (_Bool)isCustomClickGestureEnabled;
@property(readonly, nonatomic, getter=isCustomMuteThisAdAvailable) _Bool customMuteThisAdAvailable;
@property(readonly, nonatomic) GADMediaContent *mediaContent; // @synthesize mediaContent=_mediaContent;
@property(readonly, nonatomic) NSArray *muteThisAdReasons;
- (void)muteThisAdWithReason:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType paidEventHandler; // @synthesize paidEventHandler=_paidEventHandler;
- (void)performClickWithData:(id)arg1;
- (void)postDidMakeImpressionNotificationWithUserInfo:(id)arg1;
- (void)postDidReceiveUnapprovedClickNotificationWithUserInfo:(id)arg1;
@property(readonly, copy, nonatomic) NSString *price;
- (void)recordCustomClickGesture;
- (_Bool)recordImpressionWithData:(id)arg1;
- (void)registerAdView:(id)arg1 clickableAssetViews:(id)arg2 nonclickableAssetViews:(id)arg3;
- (void)registerClickConfirmingView:(id)arg1;
- (void)reportIsMediaContentRendered:(_Bool)arg1;
- (void)reportTouchEventWithData:(id)arg1;
@property(readonly, nonatomic) GADResponseInfo *responseInfo; // @synthesize responseInfo=_responseInfo;
@property(nonatomic) __weak UIViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
- (void)setUnconfirmedClickDelegate:(id)arg1;
@property(readonly, copy, nonatomic) NSDecimalNumber *starRating;
@property(readonly, copy, nonatomic) NSString *store;
- (id)unconfirmedClickDelegate;
- (void)unregisterAdView;
- (void)updateAdChoicesView:(id)arg1;
- (void)updateMediaView:(id)arg1;
@property(readonly, nonatomic) GADVideoController *videoController; // @synthesize videoController=_videoController;

@end

