//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GDTAntiSpamUtil : NSObject
{
}

+ (id)finalAntispamExposeUrlWithAdView:(id)arg1 referenceView:(id)arg2 adType:(int)arg3 exposeUrl:(id)arg4 adViewType:(long long)arg5 pageSource:(long long)arg6;

@end

