//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface GDTAntiSpam : NSObject
{
    _Bool _closeBtnDisplayed;
    _Bool _needP;
    int _antiSpamAdType;
    int _xo;
    int _yo;
    long long _playBeginTime;
    long long _aa;
    long long _ab;
    long long _ba;
    long long _bb;
    long long _g;
    long long _ec;
    long long _sc;
    NSString *_d;
    NSString *_f;
    NSString *_sz;
    long long _p;
    NSString *_x;
    long long _preClickTime;
    long long _postClickTime;
    double _tp;
    double _ts;
    long long _dx;
    long long _dy;
    long long _pw;
    long long _ph;
    long long _ra;
    long long _rb;
    long long _da;
    long long _db;
    NSString *_tid;
    long long _dataType;
    long long _clickArea;
    long long _vp;
    long long _pageSource;
}

+ (id)addPParamToExposureUrl:(id)arg1 currentViewFrame:(struct CGRect)arg2 rootViewFrame:(struct CGRect)arg3 antiSpamAdType:(int)arg4 antiSpamClickData:(id)arg5 baseUrl:(id)arg6 needP:(_Bool)arg7 dataType:(long long)arg8;
+ (id)addParamToBaseUrlString:(id)arg1 withKeyString:(id)arg2 valueString:(id)arg3;
+ (id)addParamWith:(id)arg1 frameA:(struct CGRect)arg2 frameB:(struct CGRect)arg3 antiSpamAdType:(int)arg4 antiSpamClickData:(id)arg5 baseUrl:(id)arg6 needP:(_Bool)arg7;
+ (id)antiSpamParamWithAntiSpam:(int)arg1 templateId:(id)arg2 isCloseBtnDisplayed:(_Bool)arg3 playBeginTime:(long long)arg4;
+ (long long)currentTime;
+ (id)encodeURL:(id)arg1;
+ (struct CGRect)getAdToScreenWithView:(id)arg1 frame:(struct CGRect)arg2;
+ (struct CGSize)getAdValidateAreaWithView:(id)arg1 frameA:(struct CGRect)arg2 frameB:(struct CGRect)arg3;
+ (long long)getChannelFromDeviceManager;
+ (id)jsonStringFromObject:(id)arg1;
+ (id)urlParamForAntiSpam:(int)arg1 templateId:(id)arg2 antiSpamClickData:(id)arg3 isCloseBtnDisplayed:(_Bool)arg4 playBeginTime:(long long)arg5 dataType:(long long)arg6;
+ (id)urlParamForAntiSpam:(int)arg1 templateId:(id)arg2 antiSpamClickData:(id)arg3 isCloseBtnDisplayed:(_Bool)arg4 time:(long long)arg5;
- (void).cxx_destruct;
- (id)GDTfunctiona8klFn:(id)arg1;
- (id)GDTfunctionb5KXA7;
- (id)GDTfunctionh1qUOH;
- (id)GDTfunctionl18JaU:(id)arg1;
- (id)GDTfunctionl2ej8l:(id)arg1;
- (id)GDTfunctionl7IS5v;
- (id)GDTfunctiono9dbXL;
- (id)GDTfunctionr2HJvB;
- (id)GDTfunctionu7d0fg:(id)arg1;
- (void)GDTfunctionv8VNQa:(id)arg1;
- (void)GDTfunctionx0LJW0:(id)arg1;
@property(nonatomic) long long aa; // @synthesize aa=_aa;
@property(nonatomic) long long ab; // @synthesize ab=_ab;
- (id)addPParamsToJsonString:(id)arg1;
@property(nonatomic) int antiSpamAdType; // @synthesize antiSpamAdType=_antiSpamAdType;
@property(nonatomic) long long ba; // @synthesize ba=_ba;
@property(nonatomic) long long bb; // @synthesize bb=_bb;
@property(nonatomic) long long clickArea; // @synthesize clickArea=_clickArea;
@property(nonatomic) _Bool closeBtnDisplayed; // @synthesize closeBtnDisplayed=_closeBtnDisplayed;
@property(copy, nonatomic) NSString *d; // @synthesize d=_d;
@property(nonatomic) long long da; // @synthesize da=_da;
@property(nonatomic) long long dataType; // @synthesize dataType=_dataType;
@property(nonatomic) long long db; // @synthesize db=_db;
@property(nonatomic) long long dx; // @synthesize dx=_dx;
@property(nonatomic) long long dy; // @synthesize dy=_dy;
@property(nonatomic) long long ec; // @synthesize ec=_ec;
@property(copy, nonatomic) NSString *f; // @synthesize f=_f;
@property(nonatomic) long long g; // @synthesize g=_g;
- (id)initWithAntiSpamAdType:(int)arg1;
@property(nonatomic) _Bool needP; // @synthesize needP=_needP;
@property(nonatomic) long long p; // @synthesize p=_p;
- (id)pParamEncryptedString;
- (id)pParamWithClickData:(id)arg1;
@property(nonatomic) long long pageSource; // @synthesize pageSource=_pageSource;
@property(nonatomic) long long ph; // @synthesize ph=_ph;
@property(nonatomic) long long playBeginTime; // @synthesize playBeginTime=_playBeginTime;
@property(nonatomic) long long postClickTime; // @synthesize postClickTime=_postClickTime;
@property(nonatomic) long long preClickTime; // @synthesize preClickTime=_preClickTime;
@property(nonatomic) long long pw; // @synthesize pw=_pw;
@property(nonatomic) long long ra; // @synthesize ra=_ra;
@property(nonatomic) long long rb; // @synthesize rb=_rb;
@property(nonatomic) long long sc; // @synthesize sc=_sc;
@property(copy, nonatomic) NSString *sz; // @synthesize sz=_sz;
@property(copy, nonatomic) NSString *tid; // @synthesize tid=_tid;
@property(nonatomic) double tp; // @synthesize tp=_tp;
@property(nonatomic) double ts; // @synthesize ts=_ts;
@property(nonatomic) long long vp; // @synthesize vp=_vp;
@property(copy, nonatomic) NSString *x; // @synthesize x=_x;
@property(nonatomic) int xo; // @synthesize xo=_xo;
@property(nonatomic) int yo; // @synthesize yo=_yo;

@end

