//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDTCustomGestureRecognizerDelegate-Protocol.h"

@class GDTAntiSpamClickData, NSString, UIView;
@protocol GDTAdViewClickWithAntiSpamCheckerDelegate;

@interface GDTAdViewClickWithAntiSpamChecker : NSObject <GDTCustomGestureRecognizerDelegate>
{
    id <GDTAdViewClickWithAntiSpamCheckerDelegate> _delegate;
    UIView *_gestureView;
    UIView *_adView;
    UIView *_referenceView;
    GDTAntiSpamClickData *_antiSpamClickData;
}

- (void).cxx_destruct;
- (void)GDTfunctionf3xR9R:(id)arg1;
- (void)GDTfunctioni9oEo6:(id)arg1 beganWithTouches:(id)arg2 andEvent:(id)arg3;
- (void)GDTfunctioni9oEo6:(id)arg1 endedWithTouches:(id)arg2 andEvent:(id)arg3;
- (void)GDTfunctions5sJGL:(id)arg1 referenceView:(id)arg2;
@property(nonatomic) __weak UIView *adView; // @synthesize adView=_adView;
@property(retain, nonatomic) GDTAntiSpamClickData *antiSpamClickData; // @synthesize antiSpamClickData=_antiSpamClickData;
@property(nonatomic) __weak id <GDTAdViewClickWithAntiSpamCheckerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIView *gestureView; // @synthesize gestureView=_gestureView;
@property(nonatomic) __weak UIView *referenceView; // @synthesize referenceView=_referenceView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

