//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class GDTContentInfo, NSMutableArray, NSString, NSURL;

@interface GDTCacheConfiguration : NSObject <NSCoding, NSCopying>
{
    NSString *_filePath;
    GDTContentInfo *_contentInfo;
    NSURL *_url;
    NSString *_fileName;
    NSMutableArray *_internalCacheFragments;
    NSMutableArray *_downloadInfo;
}

+ (id)configurationFilePathForFilePath:(id)arg1;
+ (id)configurationWithFilePath:(id)arg1;
- (void).cxx_destruct;
- (void)addCacheFragment:(struct _NSRange)arg1;
- (void)addDownloadedBytes:(long long)arg1 spent:(double)arg2;
- (id)cacheFragments;
@property(retain, nonatomic) GDTContentInfo *contentInfo; // @synthesize contentInfo=_contentInfo;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSMutableArray *downloadInfo; // @synthesize downloadInfo=_downloadInfo;
@property(readonly, nonatomic) float downloadSpeed;
@property(readonly, nonatomic) long long downloadedBytes;
- (void)encodeWithCoder:(id)arg1;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) NSMutableArray *internalCacheFragments; // @synthesize internalCacheFragments=_internalCacheFragments;
@property(readonly, nonatomic) float progress;
- (void)save;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;

@end

