//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol GDTClickManagerDelegate <NSObject>

@optional
- (void)GDTfunctionh2ItK6;
- (void)GDTfunctionk0G1Hq;
- (void)GDTfunctionp3u4cU;
- (void)GDTfunctions0qikE;
- (void)GDTfunctionv2H4A7;
- (void)gdt_clickManagerOpenCustomizeWebView:(NSString *)arg1;
@end

