//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTBaseClickChainHandler.h"

@class GDTOpenWebviewCommand;
@protocol GDTClickFacadeDelegate;

@interface GDTDeepLinkClickChainHandler : GDTBaseClickChainHandler
{
    id <GDTClickFacadeDelegate> _delegate;
    GDTOpenWebviewCommand *_openWebViewCMD;
}

- (void).cxx_destruct;
- (void)GDTfunctionc1rP9g:(id)arg1;
- (void)GDTfunctioni78kcx:(_Bool)arg1 clickParam:(id)arg2 request:(id)arg3;
- (void)GDTfunctiony7o7YN:(id)arg1 viewController:(id)arg2;
- (_Bool)canHandleRequest:(id)arg1;
@property(nonatomic) __weak id <GDTClickFacadeDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) GDTOpenWebviewCommand *openWebViewCMD; // @synthesize openWebViewCMD=_openWebViewCMD;

@end

