//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GDTAdViewClickWithAntiSpamCheckerDelegate-Protocol.h"
#import "GDTCustomGestureRecognizerDelegate-Protocol.h"
#import "GDTFullScreenOverlayMediatorViewProtocol-Protocol.h"

@class GDTAdViewClickWithAntiSpamChecker, GDTAntiSpamClickData, GDTFullScreenVideoControl, GDTPlayer, GDTUnifiedTemplateModel, NSString, UIButton;
@protocol GDTFullScreenOverlayMediatorViewDelegate;

@interface GDTFullScreenOverlayView : UIView <GDTCustomGestureRecognizerDelegate, GDTAdViewClickWithAntiSpamCheckerDelegate, GDTFullScreenOverlayMediatorViewProtocol>
{
    _Bool _bottomCardAppearReported;
    GDTPlayer *_player;
    id <GDTFullScreenOverlayMediatorViewDelegate> _delegate;
    UIView *_bottomCardView;
    UIView *_eventView;
    long long _closeButtonShowTime;
    GDTUnifiedTemplateModel *_adModel;
    GDTAntiSpamClickData *_antiSpamBodyClickData;
    GDTAntiSpamClickData *_antiSpamBottomCardClickData;
    UIButton *_closeButton;
    GDTFullScreenVideoControl *_videoControl;
    GDTAdViewClickWithAntiSpamChecker *_clickChecker;
}

- (void).cxx_destruct;
- (void)GDTfunctiond5dBik:(double)arg1;
- (void)GDTfunctioni2Mcjm;
- (void)GDTfunctioni9oEo6:(id)arg1 beganWithTouches:(id)arg2 andEvent:(id)arg3;
- (void)GDTfunctioni9oEo6:(id)arg1 endedWithTouches:(id)arg2 andEvent:(id)arg3;
- (id)GDTfunctionq2VL8d:(id)arg1 currentAntiSpanParam:(id)arg2;
- (id)GDTfunctionu4SzLH:(id)arg1 currentAntiSpanParam:(id)arg2;
- (void)GDTfunctionv88LPm;
- (void)GDTfunctionx51ozf;
@property(retain, nonatomic) GDTUnifiedTemplateModel *adModel; // @synthesize adModel=_adModel;
@property(retain, nonatomic) GDTAntiSpamClickData *antiSpamBodyClickData; // @synthesize antiSpamBodyClickData=_antiSpamBodyClickData;
@property(retain, nonatomic) GDTAntiSpamClickData *antiSpamBottomCardClickData; // @synthesize antiSpamBottomCardClickData=_antiSpamBottomCardClickData;
@property(nonatomic) _Bool bottomCardAppearReported; // @synthesize bottomCardAppearReported=_bottomCardAppearReported;
@property(retain, nonatomic) UIView *bottomCardView; // @synthesize bottomCardView=_bottomCardView;
@property(retain, nonatomic) GDTAdViewClickWithAntiSpamChecker *clickChecker; // @synthesize clickChecker=_clickChecker;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(nonatomic) long long closeButtonShowTime; // @synthesize closeButtonShowTime=_closeButtonShowTime;
@property(nonatomic) __weak id <GDTFullScreenOverlayMediatorViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *eventView; // @synthesize eventView=_eventView;
- (void)gestureView:(id)arg1 didClickWithClickData:(id)arg2;
- (id)initLGDTfunctiond8PfLr:(id)arg1;
- (void)layoutSubviews;
@property(nonatomic) __weak GDTPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) GDTFullScreenVideoControl *videoControl; // @synthesize videoControl=_videoControl;
- (void)showCloseButton;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

