//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol GDTHandlerRewardVideoProtocol <NSObject>

@optional
- (void)GDTfunctiond8A8LV:(NSString *)arg1;
- (void)GDTfunctionl4rwuD:(NSString *)arg1;
- (void)GDTfunctionv48fQJ:(NSString *)arg1 params:(NSDictionary *)arg2;
- (void)endCardButtonClickedWithParams:(NSDictionary *)arg1;
@property(retain, nonatomic) NSDictionary *endCardDict;
@end

