//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GDTLogger : NSObject
{
}

+ (void)GDTfunctions04OLy:(id)arg1;
+ (void)GDTfunctions04OLy:(id)arg1 level:(long long)arg2;
+ (void)GDTfunctions04OLy:(id)arg1 level:(long long)arg2 customId:(long long)arg3;
+ (void)beginEventId:(long long)arg1;
+ (void)endEventId:(long long)arg1 ext:(id)arg2;
+ (void)endEventId:(long long)arg1 ext:(id)arg2 placementId:(id)arg3 aId:(id)arg4 traceId:(id)arg5;
+ (void)onDidApplicationBecomeActive;
+ (void)onWillApplicationEnterBackground;
+ (void)recordEventId:(long long)arg1;
+ (void)recordEventId:(long long)arg1 value:(long long)arg2;
+ (void)recordEventId:(long long)arg1 value:(long long)arg2 ext:(id)arg3;
+ (void)recordEventId:(long long)arg1 value:(long long)arg2 ext:(id)arg3 biz:(id)arg4;
+ (void)recordEventId:(long long)arg1 value:(long long)arg2 ext:(id)arg3 placementId:(id)arg4;
+ (void)recordEventId:(long long)arg1 value:(long long)arg2 ext:(id)arg3 placementId:(id)arg4 aId:(id)arg5 traceId:(id)arg6;
+ (void)recordEventId:(long long)arg1 value:(long long)arg2 placementId:(id)arg3;
+ (void)recordPerformanceLog:(long long)arg1 resourceSize:(unsigned long long)arg2 duration:(unsigned long long)arg3 ext:(id)arg4;
+ (void)recordPerformanceLog:(long long)arg1 resourceSize:(unsigned long long)arg2 duration:(unsigned long long)arg3 ext:(id)arg4 biz:(id)arg5;
+ (void)recordPerformanceLog:(long long)arg1 resourceSize:(unsigned long long)arg2 duration:(unsigned long long)arg3 ext:(id)arg4 placementId:(id)arg5 aId:(id)arg6 traceId:(id)arg7;
+ (void)registerEvent;

@end

