//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GDTMAppConfigModel, GDTMNetworkConfigModel, GDTMPosConfigModel, NSArray, NSDate, NSMutableArray, NSMutableDictionary, NSString;
@protocol GDTBaseAdNetworkAdapterProtocol;

@interface GDTMBaseAdMediator : NSObject
{
    _Bool _processing;
    NSString *_placementId;
    NSArray *_networkConfigModelArray;
    NSMutableArray *_serialModelArray;
    GDTMAppConfigModel *_appConfigModel;
    GDTMPosConfigModel *_configModel;
    GDTMNetworkConfigModel *_networkConfigModel;
    NSMutableArray *_resultArray;
    id <GDTBaseAdNetworkAdapterProtocol> _adapter;
    NSDate *_loadBeginTime;
    NSMutableDictionary *_reportDict;
    long long _timeout;
}

- (void).cxx_destruct;
- (void)GDTfunctione3SPId;
- (void)GDTfunctionf5rGLO;
- (void)GDTfunctionk74VXu:(id)arg1;
- (void)GDTfunctionn4pmCq;
- (void)GDTfunctionq8ce0N;
- (void)GDTfunctiont1GeDb;
- (void)GDTfunctiont7czMQ:(long long)arg1;
- (void)GDTfunctiont9f3T9:(id)arg1;
- (void)GDTfunctionv1xI1L:(id)arg1 filled:(_Bool)arg2;
- (void)GDTfunctionw1p5cm;
- (id)GDTfunctionw6tYCh;
- (void)GDTfunctionx0UGNk;
- (void)GDTfunctionz27yvA;
@property(retain, nonatomic) id <GDTBaseAdNetworkAdapterProtocol> adapter; // @synthesize adapter=_adapter;
@property(retain, nonatomic) GDTMAppConfigModel *appConfigModel; // @synthesize appConfigModel=_appConfigModel;
@property(retain, nonatomic) GDTMPosConfigModel *configModel; // @synthesize configModel=_configModel;
- (id)initWithPlacementId:(id)arg1;
- (id)initWithPlacementId:(id)arg1 serverType:(long long)arg2;
- (void)loadAd;
@property(retain, nonatomic) NSDate *loadBeginTime; // @synthesize loadBeginTime=_loadBeginTime;
@property(retain, nonatomic) GDTMNetworkConfigModel *networkConfigModel; // @synthesize networkConfigModel=_networkConfigModel;
@property(retain, nonatomic) NSArray *networkConfigModelArray; // @synthesize networkConfigModelArray=_networkConfigModelArray;
@property(copy, nonatomic) NSString *placementId; // @synthesize placementId=_placementId;
@property(nonatomic) _Bool processing; // @synthesize processing=_processing;
@property(retain, nonatomic) NSMutableDictionary *reportDict; // @synthesize reportDict=_reportDict;
@property(retain, nonatomic) NSMutableArray *resultArray; // @synthesize resultArray=_resultArray;
@property(retain, nonatomic) NSMutableArray *serialModelArray; // @synthesize serialModelArray=_serialModelArray;
@property(nonatomic) long long timeout; // @synthesize timeout=_timeout;

@end

