//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GDTMAppConfigModel, NSArray, NSString;

@interface GDTMPosConfigModel : NSObject
{
    NSString *_placementId;
    double _timeoutDuration;
    long long _requestType;
    NSString *_posViewId;
    NSString *_emptyOrderViewId;
    NSArray *_networkConfigArray;
    GDTMAppConfigModel *_parentModel;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *emptyOrderViewId; // @synthesize emptyOrderViewId=_emptyOrderViewId;
- (id)initLGDTfunctione8RtpY:(id)arg1 parentModel:(id)arg2;
@property(retain, nonatomic) NSArray *networkConfigArray; // @synthesize networkConfigArray=_networkConfigArray;
@property(nonatomic) __weak GDTMAppConfigModel *parentModel; // @synthesize parentModel=_parentModel;
@property(copy, nonatomic) NSString *placementId; // @synthesize placementId=_placementId;
@property(copy, nonatomic) NSString *posViewId; // @synthesize posViewId=_posViewId;
@property(nonatomic) long long requestType; // @synthesize requestType=_requestType;
@property(nonatomic) double timeoutDuration; // @synthesize timeoutDuration=_timeoutDuration;

@end

