//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GDTMBiddingManager : NSObject
{
}

+ (long long)finalECPMWithNetworkConfigModel:(id)arg1;
+ (id)finalNetworkConfigModelWithArray:(id)arg1 resultAdapterArray:(id)arg2;
+ (long long)finalPriorityWithWithNetworkConfigModel:(id)arg1;
+ (id)networkConfigModelArrayWithConfigModel:(id)arg1 adapterProtocol:(id)arg2 delegate:(id)arg3;
+ (id)sortNetworkArrayWithConfigModel:(id)arg1;

@end

