//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GDTAdContentViewCheckerDelegate-Protocol.h"
#import "GDTClickFacadeDelegate-Protocol.h"
#import "GDTVideoPlayerViewDelegate-Protocol.h"
#import "GDTVideoStoreViewControllerDelegate-Protocol.h"
#import "GDTWebViewDelegate-Protocol.h"

@class GDTAdParams, GDTAdViewExposeRuleChecker, GDTAdWKWebView, GDTAntiSpamClickData, GDTCTAClickManager, GDTClickFacade, GDTNativeExpressProAdModel, GDTVideoPlayerView, NSString, UIViewController;
@protocol GDTNativeExpressProAdViewDelegate;

@interface GDTNativeExpressProAdView : UIView <GDTVideoPlayerViewDelegate, GDTVideoStoreViewControllerDelegate, GDTWebViewDelegate, GDTClickFacadeDelegate, GDTAdContentViewCheckerDelegate>
{
    _Bool _isReady;
    _Bool _isVideoAd;
    _Bool _isRendering;
    _Bool _viewable;
    _Bool _isDarkMode;
    id <GDTNativeExpressProAdViewDelegate> _delegate;
    UIViewController *_controller;
    GDTNativeExpressProAdModel *_adModel;
    GDTAdParams *_adParams;
    GDTAdViewExposeRuleChecker *_checker;
    GDTClickFacade *_clickFacade;
    GDTAntiSpamClickData *_antiSpamClickData;
    GDTCTAClickManager *_ctaClickManager;
    GDTAdWKWebView *_webView;
    GDTVideoPlayerView *_videoPlayerView;
    double _startRenderingTime;
}

- (void).cxx_destruct;
- (void)GDTfunctiona0a6KJ:(id)arg1;
- (void)GDTfunctiona4IpSH:(id)arg1;
- (void)GDTfunctiona7dDb1;
- (void)GDTfunctionc0NZEm:(_Bool)arg1;
- (_Bool)GDTfunctione6bSPR:(id)arg1 GDTfunctionh1EwgM:(id)arg2;
- (void)GDTfunctione6bSPR:(id)arg1 handleJsRequest:(id)arg2;
- (void)GDTfunctionf1ZxNg:(id)arg1;
- (void)GDTfunctionf4e7Jp:(id)arg1;
- (void)GDTfunctionf9iEYb:(id)arg1;
- (long long)GDTfunctiong7DYse;
- (void)GDTfunctionh01PCT;
- (void)GDTfunctionh43k2v;
- (void)GDTfunctioni0Bfez:(id)arg1;
- (void)GDTfunctioni7YKW1:(id)arg1;
- (_Bool)GDTfunctionj3HMPi;
- (void)GDTfunctionj7eJmK:(id)arg1 params:(id)arg2;
- (void)GDTfunctionl0NAuH;
- (void)GDTfunctionl3yMFy:(id)arg1;
- (void)GDTfunctionl6bJR6:(id)arg1;
- (void)GDTfunctionm3kbTl:(id)arg1;
- (void)GDTfunctionm643bx;
- (void)GDTfunctionm7iiGR:(id)arg1;
- (void)GDTfunctionm8IDSd;
- (id)GDTfunctionn274J5;
- (_Bool)GDTfunctiono5kHjz;
- (void)GDTfunctionp4hDKX;
- (void)GDTfunctionp8hgyp:(id)arg1;
- (void)GDTfunctionq610Kb:(id)arg1;
- (void)GDTfunctions4qmva:(id)arg1;
- (void)GDTfunctionu408Lp;
- (id)GDTfunctionv0iAMt;
- (void)GDTfunctionv4xSQA:(id)arg1;
- (void)GDTfunctionw3Cb1c;
- (void)GDTfunctionw9mJMT;
- (void)GDTfunctionx116OI:(id)arg1;
- (void)GDTfunctionx2DKrz;
- (void)GDTfunctionx2jsJP;
- (void)GDTfunctiony4VMDW:(unsigned long long)arg1 duration:(long long)arg2;
- (void)GDTfunctiony5e4C3;
- (void)GDTfunctionz1thDS;
- (_Bool)GDTfunctionz3Pcmw:(_Bool)arg1;
- (void)GDTfunctionz9rNdo;
@property(retain, nonatomic) GDTNativeExpressProAdModel *adModel; // @synthesize adModel=_adModel;
@property(retain, nonatomic) GDTAdParams *adParams; // @synthesize adParams=_adParams;
@property(retain, nonatomic) GDTAntiSpamClickData *antiSpamClickData; // @synthesize antiSpamClickData=_antiSpamClickData;
- (void)autoPlay;
@property(retain, nonatomic) GDTAdViewExposeRuleChecker *checker; // @synthesize checker=_checker;
- (void)click:(id)arg1;
@property(retain, nonatomic) GDTClickFacade *clickFacade; // @synthesize clickFacade=_clickFacade;
@property(nonatomic) __weak UIViewController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) GDTCTAClickManager *ctaClickManager; // @synthesize ctaClickManager=_ctaClickManager;
- (void)dealloc;
@property(nonatomic) __weak id <GDTNativeExpressProAdViewDelegate> delegate; // @synthesize delegate=_delegate;
- (long long)eCPM;
- (id)eCPMLevel;
- (id)initLGDTfunctiond8PfLr:(id)arg1 adParams:(id)arg2;
- (void)initViews;
@property(nonatomic) _Bool isDarkMode; // @synthesize isDarkMode=_isDarkMode;
@property(nonatomic) _Bool isReady; // @synthesize isReady=_isReady;
@property(nonatomic) _Bool isRendering; // @synthesize isRendering=_isRendering;
@property(readonly, nonatomic) _Bool isVideoAd; // @synthesize isVideoAd=_isVideoAd;
- (void)pause;
- (void)play;
- (void)render;
@property(nonatomic) double startRenderingTime; // @synthesize startRenderingTime=_startRenderingTime;
@property(retain, nonatomic) GDTVideoPlayerView *videoPlayerView; // @synthesize videoPlayerView=_videoPlayerView;
@property(nonatomic) _Bool viewable; // @synthesize viewable=_viewable;
@property(retain, nonatomic) GDTAdWKWebView *webView; // @synthesize webView=_webView;
- (double)videoDuration;
- (double)videoPlayTime;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

