//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDTNativeExpressAdDelegete-Protocol.h"
#import "GDTNativeExpressAdImpProtocol-Protocol.h"

@class GDTNativeExpressAd, NSString;
@protocol GDTNativeExpressAdImpDelegete;

@interface GDTNativeExpressAdImp : NSObject <GDTNativeExpressAdDelegete, GDTNativeExpressAdImpProtocol>
{
    _Bool videoAutoPlayOnWWAN;
    _Bool videoMuted;
    _Bool detailPageVideoMuted;
    _Bool _disableServerMediation;
    id <GDTNativeExpressAdImpDelegete> delegate;
    GDTNativeExpressAd *nativeExpressAd;
    NSString *adNetworkName;
    long long minVideoDuration;
    long long maxVideoDuration;
    NSString *fixedVideoDuration;
    unsigned long long videoRenderType;
    NSString *_placementId;
    NSString *_threadId;
    long long _serverType;
    struct CGSize adSize;
}

- (void).cxx_destruct;
- (void)GDTfunctiond7FBs7:(unsigned long long)arg1;
- (void)GDTfunctiond7FBs7:(unsigned long long)arg1 detailErrorCode:(unsigned long long)arg2;
- (_Bool)GDTfunctiong46OFE;
@property(copy, nonatomic) NSString *adNetworkName; // @synthesize adNetworkName;
@property(nonatomic) struct CGSize adSize; // @synthesize adSize;
@property(nonatomic) __weak id <GDTNativeExpressAdImpDelegete> delegate; // @synthesize delegate;
@property(nonatomic) _Bool detailPageVideoMuted; // @synthesize detailPageVideoMuted;
@property(nonatomic) _Bool disableServerMediation; // @synthesize disableServerMediation=_disableServerMediation;
@property(copy, nonatomic) NSString *fixedVideoDuration; // @synthesize fixedVideoDuration;
- (id)initWithPlacementId:(id)arg1;
- (id)initWithPlacementId:(id)arg1 serverType:(long long)arg2;
- (void)loadAd;
- (void)loadAdWithAdCount:(long long)arg1;
@property(nonatomic) long long maxVideoDuration; // @synthesize maxVideoDuration;
@property(nonatomic) long long minVideoDuration; // @synthesize minVideoDuration;
@property(nonatomic) __weak GDTNativeExpressAd *nativeExpressAd; // @synthesize nativeExpressAd;
- (void)nativeExpressAdView:(id)arg1 playerStatusChanged:(unsigned long long)arg2;
- (void)nativeExpressAdViewApplicationWillEnterBackground:(id)arg1;
- (void)nativeExpressAdViewClicked:(id)arg1;
- (void)nativeExpressAdViewClosed:(id)arg1;
- (void)nativeExpressAdViewDidDismissScreen:(id)arg1;
- (void)nativeExpressAdViewDidDismissVideoVC:(id)arg1;
- (void)nativeExpressAdViewDidPresentScreen:(id)arg1;
- (void)nativeExpressAdViewDidPresentVideoVC:(id)arg1;
- (void)nativeExpressAdViewExposure:(id)arg1;
- (void)nativeExpressAdViewRenderFail:(id)arg1;
- (void)nativeExpressAdViewRenderSuccess:(id)arg1;
- (void)nativeExpressAdViewWillDismissScreen:(id)arg1;
- (void)nativeExpressAdViewWillDismissVideoVC:(id)arg1;
- (void)nativeExpressAdViewWillPresentScreen:(id)arg1;
- (void)nativeExpressAdViewWillPresentVideoVC:(id)arg1;
@property(copy, nonatomic) NSString *placementId; // @synthesize placementId=_placementId;
@property(nonatomic) long long serverType; // @synthesize serverType=_serverType;
@property(copy, nonatomic) NSString *threadId; // @synthesize threadId=_threadId;
@property(nonatomic) _Bool videoAutoPlayOnWWAN; // @synthesize videoAutoPlayOnWWAN;
@property(nonatomic) _Bool videoMuted; // @synthesize videoMuted;
@property(nonatomic) unsigned long long videoRenderType; // @synthesize videoRenderType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

