//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDTNativeExpressAdImpDelegete-Protocol.h"
#import "GDTNativeExpressAdNetworkAdapterProtocol-Protocol.h"

@class GDTNativeExpressAdImp, GDTNativeExpressAdMediator, NSArray, NSString;

@interface GDTNativeExpressAdAdapter : NSObject <GDTNativeExpressAdNetworkAdapterProtocol, GDTNativeExpressAdImpDelegete>
{
    GDTNativeExpressAdMediator *_connector;
    GDTNativeExpressAdImp *_nativeExpressImp;
    NSArray *_viewArray;
}

+ (id)adapterVersion;
- (void).cxx_destruct;
- (void)GDTfunctionb1Sg66:(id)arg1;
- (void)GDTfunctiond2ZZ7M:(id)arg1;
- (void)GDTfunctiond3rTJL:(id)arg1;
- (void)GDTfunctionh6r4za:(id)arg1;
- (void)GDTfunctionk21eVD:(long long)arg1;
- (void)GDTfunctionk6TTQX:(id)arg1;
- (void)GDTfunctionl4MFbI:(id)arg1 views:(id)arg2;
- (void)GDTfunctiono293f5:(id)arg1 playerStatusChanged:(unsigned long long)arg2;
- (void)GDTfunctiono7kQ1o:(id)arg1;
- (void)GDTfunctionp61b4k:(id)arg1;
- (void)GDTfunctionr3ptDh:(id)arg1;
- (void)GDTfunctionr5bygn:(id)arg1;
- (void)GDTfunctionr9MLrr:(id)arg1;
- (void)GDTfunctionu0AGmy:(id)arg1;
- (void)GDTfunctionu2c1Hd:(id)arg1;
- (void)GDTfunctionu48EwP:(id)arg1;
- (void)GDTfunctiony1A7GV:(id)arg1 error:(id)arg2;
- (void)GDTfunctiony340u8:(id)arg1;
@property(nonatomic) __weak GDTNativeExpressAdMediator *connector; // @synthesize connector=_connector;
- (long long)eCPM;
- (id)initWithAdNetworkConnector:(id)arg1 posId:(id)arg2 extStr:(id)arg3;
- (_Bool)isContractAd;
- (long long)mediationPrice;
@property(retain, nonatomic) GDTNativeExpressAdImp *nativeExpressImp; // @synthesize nativeExpressImp=_nativeExpressImp;
- (long long)priority;
@property(retain, nonatomic) NSArray *viewArray; // @synthesize viewArray=_viewArray;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool detailPageVideoMuted;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long maxVideoDuration;
@property(nonatomic) long long minVideoDuration;
@property(readonly) Class superclass;
@property(nonatomic) _Bool videoAutoPlayOnWWAN;
@property(nonatomic) _Bool videoMuted;

@end

