//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GDTNativeExpressAdView, NSArray, NSError;
@protocol GDTNativeExpressAdNetworkAdapterProtocol;

@protocol GDTNativeExpressAdNetworkConnectorProtocol <NSObject>
- (void)GDTfunctiona0DtcR:(GDTNativeExpressAdView *)arg1;
- (void)GDTfunctionb4mr8C:(GDTNativeExpressAdView *)arg1;
- (void)GDTfunctionb4zyQ4:(GDTNativeExpressAdView *)arg1;
- (void)GDTfunctiong2spno:(id <GDTNativeExpressAdNetworkAdapterProtocol>)arg1 error:(NSError *)arg2;
- (void)GDTfunctiong6OVE9:(GDTNativeExpressAdView *)arg1;
- (void)GDTfunctionl8iSJ7:(GDTNativeExpressAdView *)arg1;
- (void)GDTfunctiono30Ycf:(GDTNativeExpressAdView *)arg1;
- (void)GDTfunctiono8XMHN:(GDTNativeExpressAdView *)arg1;
- (void)GDTfunctionp080oM:(id <GDTNativeExpressAdNetworkAdapterProtocol>)arg1 views:(NSArray *)arg2;
- (void)GDTfunctionp17cCu:(GDTNativeExpressAdView *)arg1;
- (void)GDTfunctionr1ztSw:(GDTNativeExpressAdView *)arg1;
- (void)GDTfunctions1wyTO:(GDTNativeExpressAdView *)arg1;
- (void)GDTfunctiont89i6D:(GDTNativeExpressAdView *)arg1;
- (void)GDTfunctionu0h3El:(GDTNativeExpressAdView *)arg1;
- (void)GDTfunctionu312fJ:(GDTNativeExpressAdView *)arg1 playerStatusChanged:(unsigned long long)arg2;
- (void)GDTfunctionw9IHKA:(GDTNativeExpressAdView *)arg1;
- (void)GDTfunctiony8koKi:(GDTNativeExpressAdView *)arg1;
@end

