//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GDTOrphanBusinessUtil : NSObject
{
}

+ (_Bool)adShouldOffline;
+ (id)addAntiSpamParamsForDict:(id)arg1 withBaseView:(id)arg2 currentFrame:(struct CGRect)arg3 rootViewFrame:(struct CGRect)arg4 clickArea:(long long)arg5 adViewType:(long long)arg6 pageSource:(long long)arg7;
+ (unsigned long long)convertToMediaPlayerStatusFromPlayerStatus:(unsigned long long)arg1;
+ (long long)getValidVideoDuration:(long long)arg1;
+ (void)reportThirdPartyClickUrlWithAdModel:(id)arg1;
+ (void)updateMMAConfigIfNeccessary;
+ (id)webViewCommandParamDictFromReq:(id)arg1;

@end

