//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIView;

@interface GDTOrientationObserver : NSObject
{
    _Bool _fullScreen;
    _Bool _lockedScreen;
    _Bool _statusBarHidden;
    _Bool _allowOrentitaionRotation;
    float _duration;
    UIView *_fullScreenContainerView;
    UIView *_containerView;
    CDUnknownBlockType _orientationWillChange;
    CDUnknownBlockType _orientationDidChanged;
    unsigned long long _fullScreenMode;
    long long _currentOrientation;
    unsigned long long _supportInterfaceOrientation;
    UIView *_view;
    UIView *_cell;
    long long _playerViewTag;
    unsigned long long _roateType;
    UIView *_blackView;
}

- (void).cxx_destruct;
- (void)addDeviceOrientationObserver;
@property(nonatomic) _Bool allowOrentitaionRotation; // @synthesize allowOrentitaionRotation=_allowOrentitaionRotation;
@property(retain, nonatomic) UIView *blackView; // @synthesize blackView=_blackView;
@property(retain, nonatomic) UIView *cell; // @synthesize cell=_cell;
- (void)cellModelRotateView:(id)arg1 rotateViewAtCell:(id)arg2 playerViewTag:(long long)arg3;
- (void)cellSmallModelRotateView:(id)arg1 containerView:(id)arg2;
@property(nonatomic) __weak UIView *containerView; // @synthesize containerView=_containerView;
@property(readonly, nonatomic) long long currentOrientation; // @synthesize currentOrientation=_currentOrientation;
- (void)dealloc;
@property(nonatomic) float duration; // @synthesize duration=_duration;
- (void)enterLandscapeFullScreen:(long long)arg1 animated:(_Bool)arg2;
- (void)enterPortraitFullScreen:(_Bool)arg1 animated:(_Bool)arg2;
- (void)exitFullScreenWithAnimated:(_Bool)arg1;
@property(retain, nonatomic) UIView *fullScreenContainerView; // @synthesize fullScreenContainerView=_fullScreenContainerView;
@property(nonatomic) unsigned long long fullScreenMode; // @synthesize fullScreenMode=_fullScreenMode;
- (struct CGAffineTransform)getTransformRotationAngle:(long long)arg1;
- (void)handleDeviceOrientationChange;
- (id)init;
- (void)interfaceOrientation:(long long)arg1;
@property(nonatomic, getter=isFullScreen) _Bool fullScreen; // @synthesize fullScreen=_fullScreen;
@property(nonatomic, getter=isLockedScreen) _Bool lockedScreen; // @synthesize lockedScreen=_lockedScreen;
- (_Bool)isNeedAdaptiveiOS8Rotation;
@property(nonatomic, getter=isStatusBarHidden) _Bool statusBarHidden; // @synthesize statusBarHidden=_statusBarHidden;
- (_Bool)isSupportedLandscapeLeft;
- (_Bool)isSupportedLandscapeRight;
- (_Bool)isSupportedPortrait;
@property(copy, nonatomic) CDUnknownBlockType orientationDidChanged; // @synthesize orientationDidChanged=_orientationDidChanged;
@property(copy, nonatomic) CDUnknownBlockType orientationWillChange; // @synthesize orientationWillChange=_orientationWillChange;
@property(nonatomic) long long playerViewTag; // @synthesize playerViewTag=_playerViewTag;
- (void)removeDeviceOrientationObserver;
@property(nonatomic) unsigned long long roateType; // @synthesize roateType=_roateType;
@property(nonatomic) unsigned long long supportInterfaceOrientation; // @synthesize supportInterfaceOrientation=_supportInterfaceOrientation;
@property(nonatomic) __weak UIView *view; // @synthesize view=_view;
- (void)updateRotateView:(id)arg1 containerView:(id)arg2;

@end

