//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface GDTPODS_GDataXMLNode : NSObject
{
    struct _xmlNode *xmlNode_;
    _Bool shouldFreeXMLNode_;
    NSString *cachedName_;
    NSArray *cachedChildren_;
    NSArray *cachedAttributes_;
}

+ (id)attributeWithName:(id)arg1 URI:(id)arg2 stringValue:(id)arg3;
+ (id)attributeWithName:(id)arg1 stringValue:(id)arg2;
+ (id)elementWithName:(id)arg1;
+ (id)elementWithName:(id)arg1 URI:(id)arg2;
+ (id)elementWithName:(id)arg1 stringValue:(id)arg2;
+ (void)load;
+ (id)localNameForName:(id)arg1;
+ (id)namespaceWithName:(id)arg1 stringValue:(id)arg2;
+ (id)nodeBorrowingXMLNode:(struct _xmlNode *)arg1;
+ (id)nodeConsumingXMLNode:(struct _xmlNode *)arg1;
+ (id)prefixForName:(id)arg1;
+ (id)textWithStringValue:(id)arg1;
- (id)URI;
- (struct _xmlNode *)XMLNode;
- (struct _xmlNode *)XMLNodeCopy;
- (id)XMLString;
- (id)childAtIndex:(unsigned int)arg1;
- (unsigned long long)childCount;
- (id)children;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (unsigned long long)hash;
- (id)initBorrowingXMLNode:(struct _xmlNode *)arg1;
- (id)initConsumingXMLNode:(struct _xmlNode *)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)kind;
- (id)localName;
- (id)methodSignatureForSelector:(SEL)arg1;
- (id)name;
- (id)nodesForXPath:(id)arg1 error:(id *)arg2;
- (id)nodesForXPath:(id)arg1 namespaces:(id)arg2 error:(id *)arg3;
- (id)prefix;
- (id)qualifiedName;
- (void)releaseCachedValues;
- (void)setShouldFreeXMLNode:(_Bool)arg1;
- (void)setStringValue:(id)arg1;
- (_Bool)shouldFreeXMLNode;
- (id)stringFromXMLString:(const char *)arg1;
- (id)stringValue;

@end

