//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GDTOrientationObserver, GDTPlayerGestureControl, GDTPlayerNotification, NSArray, NSMutableArray, NSURL, UISlider, UIView;
@protocol GDTPlayerControlProtocol, GDTPlayerMediaProtocol;

@interface GDTPlayer : NSObject
{
    UIView *_containerView;
    id <GDTPlayerMediaProtocol> _currentPlayerManager;
    UIView<GDTPlayerControlProtocol> *_controlView;
    GDTPlayerNotification *_notification;
    UISlider *_volumeViewSlider;
    long long _containerViewTag;
    NSMutableArray *_playerControlObserverArray;
}

+ (id)gdt_playerWithPlayerManager:(id)arg1 containerView:(id)arg2;
+ (id)playerWithPlayerManager:(id)arg1 containerView:(id)arg2;
- (void).cxx_destruct;
- (void)addDeviceOrientationObserver;
- (void)addPlayerControlProtocolObserver:(id)arg1;
@property(nonatomic) _Bool allowOrentitaionRotation;
@property(retain, nonatomic) NSURL *assetURL;
@property(copy, nonatomic) NSArray *assetURLs;
@property(nonatomic) float brightness;
- (float)bufferProgress;
- (double)bufferTime;
- (void)configureVolume;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) long long containerViewTag; // @synthesize containerViewTag=_containerViewTag;
@property(retain, nonatomic) UIView<GDTPlayerControlProtocol> *controlView; // @synthesize controlView=_controlView;
@property(readonly, nonatomic) long long currentOrientation;
@property(nonatomic) long long currentPlayIndex;
@property(retain, nonatomic) id <GDTPlayerMediaProtocol> currentPlayerManager; // @synthesize currentPlayerManager=_currentPlayerManager;
- (double)currentTime;
- (void)dealloc;
@property(nonatomic) _Bool disableBackgroundNotification;
@property(nonatomic) unsigned long long disableGestureTypes;
- (void)enterFullScreen:(_Bool)arg1 animated:(_Bool)arg2;
- (void)enterLandscapeFullScreen:(long long)arg1 animated:(_Bool)arg2;
- (void)enterPortraitFullScreen:(_Bool)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) GDTPlayerGestureControl *gestureControl;
- (id)init;
- (id)initWithPlayerManager:(id)arg1 containerView:(id)arg2;
@property(readonly, nonatomic) _Bool isFirstAssetURL;
@property(readonly, nonatomic) _Bool isFullScreen;
@property(readonly, nonatomic) _Bool isLastAssetURL;
@property(nonatomic, getter=isLockedScreen) _Bool lockedScreen;
@property(nonatomic, getter=isMuted) _Bool muted;
- (_Bool)isNeedAdaptiveiOS8Rotation;
@property(nonatomic, getter=isPauseByEvent) _Bool pauseByEvent;
- (_Bool)isPlaying;
@property(nonatomic, getter=isStatusBarHidden) _Bool statusBarHidden;
@property(nonatomic, getter=isViewControllerDisappear) _Bool viewControllerDisappear;
- (float)lastVolumeValue;
- (void)layoutPlayerSubViews;
@property(retain, nonatomic) GDTPlayerNotification *notification; // @synthesize notification=_notification;
@property(copy, nonatomic) CDUnknownBlockType orientationDidChanged;
@property(readonly, nonatomic) GDTOrientationObserver *orientationObserver;
@property(copy, nonatomic) CDUnknownBlockType orientationWillChange;
@property(nonatomic) _Bool pauseWhenAppResignActive;
- (unsigned long long)playState;
- (void)playTheIndex:(long long)arg1;
- (void)playTheNext;
- (void)playThePrevious;
@property(copy, nonatomic) CDUnknownBlockType playerBufferTimeChanged;
@property(retain, nonatomic) NSMutableArray *playerControlObserverArray; // @synthesize playerControlObserverArray=_playerControlObserverArray;
@property(copy, nonatomic) CDUnknownBlockType playerDidToEnd;
@property(copy, nonatomic) CDUnknownBlockType playerLoadStateChanged;
- (void)playerManagerCallbcak;
@property(copy, nonatomic) CDUnknownBlockType playerPlayFailed;
@property(copy, nonatomic) CDUnknownBlockType playerPlayStateChanged;
@property(copy, nonatomic) CDUnknownBlockType playerPlayTimeChanged;
@property(copy, nonatomic) CDUnknownBlockType playerPrepareToPlay;
- (float)progress;
- (void)removeDeviceOrientationObserver;
- (void)removePlayerControlProtocolObserver:(id)arg1;
- (void)replaceCurrentPlayerManager:(id)arg1;
- (void)seekToTime:(double)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)setLastVolumeValue:(float)arg1;
@property(nonatomic) _Bool useDefaultAudioSessionCategory;
@property(nonatomic) float volume;
@property(retain, nonatomic) UISlider *volumeViewSlider; // @synthesize volumeViewSlider=_volumeViewSlider;
@property(readonly, nonatomic) _Bool shouldAutorotate;
- (void)stop;
- (double)totalTime;

@end

