//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTMBaseAdMediator.h"

#import "GDTRewardVideoAdImpProtocol-Protocol.h"
#import "GDTRewardVideoAdNetworkConnectorProtocol-Protocol.h"

@class GDTRewardVideoAd, NSDictionary, NSMutableArray, NSString;
@protocol GDTRewardedVideoAdImpDelegate;

@interface GDTRewardVideoAdMediator : GDTMBaseAdMediator <GDTRewardVideoAdImpProtocol, GDTRewardVideoAdNetworkConnectorProtocol>
{
    _Bool videoMuted;
    id <GDTRewardedVideoAdImpDelegate> delegate;
    GDTRewardVideoAd *rewardVideoAd;
    NSDictionary *tagDict;
    NSString *adNetworkName;
    NSMutableArray *_loadedAdapterArray;
}

- (void).cxx_destruct;
- (void)GDTfunctionf5rGLO;
- (void)GDTfunctionk74VXu:(id)arg1;
- (void)GDTfunctionn4pmCq;
- (id)GDTfunctionw6tYCh;
- (void)GDTfunctionz27yvA;
@property(copy, nonatomic) NSString *adNetworkName; // @synthesize adNetworkName;
- (void)adapter_rewardVideoAd:(id)arg1 didFailWithError:(id)arg2;
- (void)adapter_rewardVideoAdDidClicked:(id)arg1;
- (void)adapter_rewardVideoAdDidClose:(id)arg1;
- (void)adapter_rewardVideoAdDidExposed:(id)arg1;
- (void)adapter_rewardVideoAdDidLoad:(id)arg1;
- (void)adapter_rewardVideoAdDidPlayFinish:(id)arg1;
- (void)adapter_rewardVideoAdDidRewardEffective:(id)arg1;
- (void)adapter_rewardVideoAdVideoDidLoad:(id)arg1;
- (void)adapter_rewardVideoAdWillVisible:(id)arg1;
@property(nonatomic) __weak id <GDTRewardedVideoAdImpDelegate> delegate; // @synthesize delegate;
- (long long)eCPM;
- (id)eCPMLevel;
@property(readonly, nonatomic) long long expiredTimestamp;
@property(readonly, nonatomic, getter=isAdValid) _Bool adValid;
- (void)loadAd;
@property(retain, nonatomic) NSMutableArray *loadedAdapterArray; // @synthesize loadedAdapterArray=_loadedAdapterArray;
@property(nonatomic) __weak GDTRewardVideoAd *rewardVideoAd; // @synthesize rewardVideoAd;
@property(retain, nonatomic) NSDictionary *tagDict; // @synthesize tagDict;
@property(nonatomic) _Bool videoMuted; // @synthesize videoMuted;
- (_Bool)showAdFromRootViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *placementId;
@property(readonly) Class superclass;

@end

