//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GDTRewardVideoAd, NSDictionary, NSString, UIViewController;
@protocol GDTRewardedVideoAdImpDelegate;

@protocol GDTRewardVideoAdImpProtocol <NSObject>
@property(copy, nonatomic) NSString *adNetworkName;
@property(nonatomic) __weak id <GDTRewardedVideoAdImpDelegate> delegate;
- (long long)eCPM;
- (NSString *)eCPMLevel;
@property(readonly, nonatomic) long long expiredTimestamp;
- (id)initWithPlacementId:(NSString *)arg1;
- (id)initWithPlacementId:(NSString *)arg1 serverType:(long long)arg2;
@property(readonly, nonatomic, getter=isAdValid) _Bool adValid;
- (void)loadAd;
@property(readonly, nonatomic) NSString *placementId;
@property(nonatomic) __weak GDTRewardVideoAd *rewardVideoAd;
@property(retain, nonatomic) NSDictionary *tagDict;
@property(nonatomic) _Bool videoMuted;
- (_Bool)showAdFromRootViewController:(UIViewController *)arg1;
@end

