//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDTRewardedVideoAdImpDelegate-Protocol.h"

@class NSDictionary, NSString;
@protocol GDTRewardVideoAdImpProtocol, GDTRewardedVideoAdDelegate;

@interface GDTRewardVideoAd : NSObject <GDTRewardedVideoAdImpDelegate>
{
    id <GDTRewardedVideoAdDelegate> _delegate;
    NSString *_placementId;
    id <GDTRewardVideoAdImpProtocol> _mediator;
}

- (void).cxx_destruct;
- (void)GDTfunctionc0YqbA:(id)arg1;
- (void)GDTfunctione7LjlL:(id)arg1;
- (void)GDTfunctionl7e3RH:(id)arg1 didFailWithError:(id)arg2;
@property(copy, nonatomic) NSString *GDTfunctionq4VuEN;
- (void)GDTfunctionq7MVEp:(id)arg1;
- (void)GDTfunctionr7e4bi:(id)arg1;
- (void)GDTfunctiont03LYK:(id)arg1;
- (void)GDTfunctionv8J8Gh:(id)arg1;
- (void)GDTfunctionw3PosV:(id)arg1;
- (void)GDTfunctionx28V5y:(id)arg1;
- (id)adNetworkName;
- (id)bridgeName;
@property(copy, nonatomic) NSString *callbackId;
@property(nonatomic) __weak id <GDTRewardedVideoAdDelegate> delegate; // @synthesize delegate=_delegate;
- (long long)eCPM;
- (id)eCPMLevel;
@property(readonly, nonatomic) long long expiredTimestamp;
@property(retain, nonatomic) NSDictionary *extDict;
- (id)initWithAppId:(id)arg1 placementId:(id)arg2;
- (id)initWithPlacementId:(id)arg1;
@property(readonly, nonatomic, getter=isAdValid) _Bool adValid;
- (void)loadAd;
@property(retain, nonatomic) id <GDTRewardVideoAdImpProtocol> mediator; // @synthesize mediator=_mediator;
@property(copy, nonatomic) NSString *placementId; // @synthesize placementId=_placementId;
- (long long)rewardType;
- (void)setBridgeName:(id)arg1;
- (void)setHybridAdHostUrl:(id)arg1;
@property(retain, nonatomic) NSDictionary *tagDict;
@property(nonatomic) _Bool videoMuted;
- (void)setXflowPosId:(id)arg1;
- (_Bool)showAdFromRootViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

