//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError;
@protocol GDTSplashAdNetworkAdapterProtocol;

@protocol GDTSplashAdNetworkConnectorProtocol <NSObject>

@optional
- (void)GDTfunctionc7CmaX:(id <GDTSplashAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctiong9bejl:(id <GDTSplashAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionh3rVfT:(id <GDTSplashAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionh8QhHF:(id <GDTSplashAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionk0YrTV:(id <GDTSplashAdNetworkAdapterProtocol>)arg1 withError:(NSError *)arg2;
- (void)GDTfunctionk5REtY:(id <GDTSplashAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionm1unWL:(id <GDTSplashAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionn7Lptg:(id <GDTSplashAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionq0p1EQ:(id <GDTSplashAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionr6u12U:(id <GDTSplashAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctiont137hI:(id <GDTSplashAdNetworkAdapterProtocol>)arg1 lifeTime:(unsigned long long)arg2;
- (void)GDTfunctiont16gcO:(id <GDTSplashAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionx7aAx6:(id <GDTSplashAdNetworkAdapterProtocol>)arg1;
@end

