//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GDTCustomGestureRecognizerDelegate-Protocol.h"

@class GDTSplashAdModel, GDTSplashAlignImageView, GDTSplashBottomView, NSString, NSValue, UIImageView;
@protocol GDTSplashViewDelegate;

@interface GDTSplashView : UIView <GDTCustomGestureRecognizerDelegate>
{
    GDTSplashAdModel *_adModel;
    id <GDTSplashViewDelegate> _delegate;
    NSValue *_adLogoOrigin;
    GDTSplashBottomView *_bottomView;
    GDTSplashAlignImageView *_adImageView;
    UIImageView *_logoImageView;
}

- (void).cxx_destruct;
- (void)GDTfunctioni9oEo6:(id)arg1 endedWithTouches:(id)arg2 andEvent:(id)arg3;
- (void)GDTfunctiont3bLC7:(_Bool)arg1;
@property(retain, nonatomic) GDTSplashAlignImageView *adImageView; // @synthesize adImageView=_adImageView;
@property(retain, nonatomic) NSValue *adLogoOrigin; // @synthesize adLogoOrigin=_adLogoOrigin;
@property(retain, nonatomic) GDTSplashAdModel *adModel; // @synthesize adModel=_adModel;
@property(retain, nonatomic) GDTSplashBottomView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) __weak id <GDTSplashViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
- (void)setFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

