//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTMBaseAdMediator.h"

#import "GDTSplashAdImpProtocol-Protocol.h"
#import "GDTSplashAdNetworkConnectorProtocol-Protocol.h"

@class GDTSplashAd, NSString, UIColor, UIImage, UIView, UIWindow;
@protocol GDTSplashAdDelegate;

@interface GDTSplashAdMediator : GDTMBaseAdMediator <GDTSplashAdImpProtocol, GDTSplashAdNetworkConnectorProtocol>
{
    _Bool loading;
    _Bool _isParallelLoad;
    id <GDTSplashAdDelegate> delegate;
    GDTSplashAd *splashAd;
    NSString *adNetworkName;
    double _fetchDelay;
    UIColor *backgroundColor;
    UIImage *backgroundImage;
    UIWindow *_window;
    UIView *_bottomView;
    UIView *_skipView;
    struct CGPoint skipButtonCenter;
}

- (void).cxx_destruct;
- (void)GDTfunctionc7CmaX:(id)arg1;
- (void)GDTfunctionf5rGLO;
- (void)GDTfunctiong9bejl:(id)arg1;
- (void)GDTfunctionh3rVfT:(id)arg1;
- (void)GDTfunctionh8P00N;
- (void)GDTfunctionh8QhHF:(id)arg1;
- (void)GDTfunctionk0YrTV:(id)arg1 withError:(id)arg2;
- (void)GDTfunctionk5REtY:(id)arg1;
- (void)GDTfunctionk74VXu:(id)arg1;
- (void)GDTfunctionm1unWL:(id)arg1;
- (void)GDTfunctionn4pmCq;
- (void)GDTfunctionn7Lptg:(id)arg1;
- (void)GDTfunctionq0p1EQ:(id)arg1;
- (void)GDTfunctionr6u12U:(id)arg1;
- (void)GDTfunctiont137hI:(id)arg1 lifeTime:(unsigned long long)arg2;
- (void)GDTfunctiont16gcO:(id)arg1;
- (id)GDTfunctionw6tYCh;
- (void)GDTfunctionx7aAx6:(id)arg1;
- (void)GDTfunctionz27yvA;
@property(copy, nonatomic) NSString *adNetworkName; // @synthesize adNetworkName;
@property(copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) __weak id <GDTSplashAdDelegate> delegate; // @synthesize delegate;
@property(nonatomic) double fetchDelay; // @synthesize fetchDelay=_fetchDelay;
- (_Bool)isAdValid;
@property(nonatomic) _Bool isParallelLoad; // @synthesize isParallelLoad=_isParallelLoad;
- (void)loadAd;
- (void)loadAdAndShowInWindow:(id)arg1 withBottomView:(id)arg2 skipView:(id)arg3;
@property(nonatomic) _Bool loading; // @synthesize loading;
@property(nonatomic) struct CGPoint skipButtonCenter; // @synthesize skipButtonCenter;
@property(retain, nonatomic) UIView *skipView; // @synthesize skipView=_skipView;
@property(nonatomic) __weak GDTSplashAd *splashAd; // @synthesize splashAd;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)showAdInWindow:(id)arg1 withBottomView:(id)arg2 skipView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

