//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSTimer;
@protocol GDTSplashViewDelegate;

@interface GDTSplashSkipView : UIView
{
    long long _exposureTime;
    id <GDTSplashViewDelegate> _delegate;
    NSTimer *_timer;
}

- (void).cxx_destruct;
- (void)GDTfunctionr5yJYL:(long long)arg1;
- (void)GDTfunctionr8Ss8x;
- (void)GDTfunctionv9gco9:(long long)arg1;
@property(nonatomic) __weak id <GDTSplashViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long exposureTime; // @synthesize exposureTime=_exposureTime;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
- (void)tick;

@end

