//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GDTAppSettings, NSMutableDictionary, NSString;

@interface GDTSettingManager : NSObject
{
    int _eventSeq;
    int _logSeq;
    int _perfSeq;
    NSString *rootFolder;
    NSString *appPath;
    NSString *suidPath;
    NSString *sdkPath;
    NSString *_app_sig;
    NSString *_sdk_sig;
    NSString *_suid;
    NSString *_sid;
    GDTAppSettings *_contextSettings;
    GDTAppSettings *_appSettings;
    GDTAppSettings *_devSettings;
    NSMutableDictionary *_sdkSettings;
    NSMutableDictionary *_systemSettings;
    long long _sdkServerType;
    NSString *_launchId;
    NSMutableDictionary *_baseInfoDict;
}

+ (id)defaultManager;
- (void).cxx_destruct;
- (id)GDTfunctiona0koTN:(id)arg1;
- (_Bool)GDTfunctionb9VEJ4;
- (int)GDTfunctionc09jZx;
- (void)GDTfunctionc2Yfv9;
- (id)GDTfunctionc3XIzC;
- (void)GDTfunctionc6Qbzg:(id)arg1;
- (id)GDTfunctiond3eRXB:(id)arg1 placementId:(id)arg2;
- (void)GDTfunctiond8LFUV;
- (int)GDTfunctione1PVOk;
- (int)GDTfunctionh50pCm;
- (void)GDTfunctioni1sbYC:(id)arg1;
- (_Bool)GDTfunctioni7SHMO;
- (id)GDTfunctioni90CBO;
- (void)GDTfunctionm5iJRo:(id)arg1;
- (void)GDTfunctionn6tDw3;
- (void)GDTfunctiono4sslA:(id)arg1;
- (void)GDTfunctionq1Puwe:(id)arg1;
- (void)GDTfunctiont3w3NN;
- (void)GDTfunctionv2OcAZ;
- (void)GDTfunctionx9jhss;
- (int)GDTfunctiony9wqKM;
- (void)GDTfunctionz7ak1J:(id)arg1;
@property(retain, nonatomic) NSString *appPath; // @synthesize appPath;
@property(retain, nonatomic) GDTAppSettings *appSettings; // @synthesize appSettings=_appSettings;
@property(copy, nonatomic) NSString *app_sig; // @synthesize app_sig=_app_sig;
@property(retain, nonatomic) NSMutableDictionary *baseInfoDict; // @synthesize baseInfoDict=_baseInfoDict;
@property(retain, nonatomic) GDTAppSettings *contextSettings; // @synthesize contextSettings=_contextSettings;
@property(retain, nonatomic) GDTAppSettings *devSettings; // @synthesize devSettings=_devSettings;
@property(nonatomic) int eventSeq; // @synthesize eventSeq=_eventSeq;
- (id)init;
@property(copy, nonatomic) NSString *launchId; // @synthesize launchId=_launchId;
@property(nonatomic) int logSeq; // @synthesize logSeq=_logSeq;
@property(nonatomic) int perfSeq; // @synthesize perfSeq=_perfSeq;
@property(retain, nonatomic) NSString *rootFolder; // @synthesize rootFolder;
@property(retain, nonatomic) NSString *sdkPath; // @synthesize sdkPath;
@property(nonatomic) long long sdkServerType; // @synthesize sdkServerType=_sdkServerType;
@property(retain, nonatomic) NSMutableDictionary *sdkSettings; // @synthesize sdkSettings=_sdkSettings;
@property(copy, nonatomic) NSString *sdk_sig; // @synthesize sdk_sig=_sdk_sig;
- (void)setGDTfunctiona2l7tT:(id)arg1 ForKey:(id)arg2;
- (void)setGDTfunctionx4ph4V:(id)arg1 ForKey:(id)arg2 ForPlacementId:(id)arg3;
@property(copy, nonatomic) NSString *sid; // @synthesize sid=_sid;
@property(retain, nonatomic) NSString *suidPath; // @synthesize suidPath;
@property(retain, nonatomic) NSMutableDictionary *systemSettings; // @synthesize systemSettings=_systemSettings;
@property(readonly, copy, nonatomic) NSString *suid; // @synthesize suid=_suid;

@end

