//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface GDTSplashAdSelectionModel : NSObject
{
    _Bool _needEmptyReport;
    _Bool _isEmpty;
    NSString *_adid;
    NSString *_uoid;
    long long _rotIndex;
    NSString *_exposureURL;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *adid; // @synthesize adid=_adid;
@property(copy, nonatomic) NSString *exposureURL; // @synthesize exposureURL=_exposureURL;
- (id)initWithAdDict:(id)arg1;
@property(nonatomic) _Bool isEmpty; // @synthesize isEmpty=_isEmpty;
@property(nonatomic) _Bool needEmptyReport; // @synthesize needEmptyReport=_needEmptyReport;
@property(nonatomic) long long rotIndex; // @synthesize rotIndex=_rotIndex;
@property(retain, nonatomic) NSString *uoid; // @synthesize uoid=_uoid;

@end

