//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class GDTAdViewExposeRuleChecker, GDTSplashSkipView, NSString, UIColor, UIView;
@protocol GDTSplashViewDelegate><GDTSplashViewControllerDelegate><GDTAdContentViewCheckerDelegate;

@interface GDTSplashViewController : UIViewController
{
    _Bool _shouldHideAdLogo;
    UIView *_bottomView;
    UIColor *_backgroundColor;
    NSString *_placementId;
    NSString *_adId;
    NSString *_traceId;
    double _vcPresentedTime;
    GDTSplashSkipView *_skipView;
    GDTAdViewExposeRuleChecker *_checker;
    id <GDTSplashViewDelegate><GDTSplashViewControllerDelegate><GDTAdContentViewCheckerDelegate> _delegate;
    UIView *_splashView;
    long long _exposureDuration;
}

- (void).cxx_destruct;
- (void)GDTfunctionc8k1vl;
- (id)GDTfunctionf7Ret6;
- (void)GDTfunctionm3mIBj;
- (void)GDTfunctionm6sHI0;
- (void)GDTfunctionp0qZFo;
- (void)GDTfunctiont3bLC7;
- (void)GDTfunctiony3rs2r;
@property(copy, nonatomic) NSString *adId; // @synthesize adId=_adId;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) GDTAdViewExposeRuleChecker *checker; // @synthesize checker=_checker;
@property(nonatomic) __weak id <GDTSplashViewDelegate><GDTSplashViewControllerDelegate><GDTAdContentViewCheckerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long exposureDuration; // @synthesize exposureDuration=_exposureDuration;
- (id)initLGDTfunctionw2JH1P:(id)arg1 bottomView:(id)arg2 adModel:(id)arg3;
@property(copy, nonatomic) NSString *placementId; // @synthesize placementId=_placementId;
- (_Bool)prefersStatusBarHidden;
@property(nonatomic) _Bool shouldHideAdLogo; // @synthesize shouldHideAdLogo=_shouldHideAdLogo;
@property(retain, nonatomic) GDTSplashSkipView *skipView; // @synthesize skipView=_skipView;
@property(retain, nonatomic) UIView *splashView; // @synthesize splashView=_splashView;
@property(copy, nonatomic) NSString *traceId; // @synthesize traceId=_traceId;
@property(nonatomic) double vcPresentedTime; // @synthesize vcPresentedTime=_vcPresentedTime;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

