//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class GDTVideoConfig, NSString, UILabel, UIScrollView, UISlider, UISwitch, UITextField;

@interface GDTUnifiedNativeAdVideoConfigView : UIView <UIGestureRecognizerDelegate>
{
    CDUnknownBlockType _callBackBlock;
    UITextField *_autoPlayPolicyTextField;
    UISwitch *_shouldMuteOnVideoSwitch;
    UISwitch *_videoDetailPageEnableSwitch;
    UISwitch *_userControlEnableSwitch;
    UISwitch *_autoResumeEnableSwitch;
    UISwitch *_progressViewEnableSwitch;
    UISwitch *_coverImageEnableSwitch;
    UILabel *_autoPlayPolicyTextFieldLabel;
    UILabel *_shouldMuteOnVideoSwitchLabel;
    UILabel *_videoDetailPageEnableSwitchLabel;
    UILabel *_userControlEnableSwitchLabel;
    UILabel *_autoResumeEnableSwitchLabel;
    UILabel *_progressViewEnableSwitchLabel;
    UILabel *_coverImageEnableSwitchLabel;
    UILabel *_minVideoDurationLabel;
    UISlider *_minVideoDurationSlider;
    UILabel *_maxVideoDurationLabel;
    UISlider *_maxVideoDurationSlider;
    UISwitch *_videoDetailPageMuteSwitch;
    UILabel *_videoDetailPageMuteSwitchLabel;
    GDTVideoConfig *_videoConfig;
    UIScrollView *_contentView;
}

- (void).cxx_destruct;
- (void)GDTfunctionl5t3NQ;
- (void)GDTfunctionp2eg80;
- (void)GDTfunctiony756cC;
@property(retain, nonatomic) UITextField *autoPlayPolicyTextField; // @synthesize autoPlayPolicyTextField=_autoPlayPolicyTextField;
@property(retain, nonatomic) UILabel *autoPlayPolicyTextFieldLabel; // @synthesize autoPlayPolicyTextFieldLabel=_autoPlayPolicyTextFieldLabel;
@property(retain, nonatomic) UISwitch *autoResumeEnableSwitch; // @synthesize autoResumeEnableSwitch=_autoResumeEnableSwitch;
@property(retain, nonatomic) UILabel *autoResumeEnableSwitchLabel; // @synthesize autoResumeEnableSwitchLabel=_autoResumeEnableSwitchLabel;
@property(copy, nonatomic) CDUnknownBlockType callBackBlock; // @synthesize callBackBlock=_callBackBlock;
@property(nonatomic) __weak UIScrollView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UISwitch *coverImageEnableSwitch; // @synthesize coverImageEnableSwitch=_coverImageEnableSwitch;
@property(retain, nonatomic) UILabel *coverImageEnableSwitchLabel; // @synthesize coverImageEnableSwitchLabel=_coverImageEnableSwitchLabel;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)initLGDTfunctionn3ESXd;
- (id)initWithFrame:(struct CGRect)arg1 theVideoConfig:(id)arg2;
@property(retain, nonatomic) UILabel *maxVideoDurationLabel; // @synthesize maxVideoDurationLabel=_maxVideoDurationLabel;
@property(retain, nonatomic) UISlider *maxVideoDurationSlider; // @synthesize maxVideoDurationSlider=_maxVideoDurationSlider;
@property(retain, nonatomic) UILabel *minVideoDurationLabel; // @synthesize minVideoDurationLabel=_minVideoDurationLabel;
@property(retain, nonatomic) UISlider *minVideoDurationSlider; // @synthesize minVideoDurationSlider=_minVideoDurationSlider;
@property(retain, nonatomic) UISwitch *progressViewEnableSwitch; // @synthesize progressViewEnableSwitch=_progressViewEnableSwitch;
@property(retain, nonatomic) UILabel *progressViewEnableSwitchLabel; // @synthesize progressViewEnableSwitchLabel=_progressViewEnableSwitchLabel;
- (void)removeView;
@property(retain, nonatomic) UISwitch *shouldMuteOnVideoSwitch; // @synthesize shouldMuteOnVideoSwitch=_shouldMuteOnVideoSwitch;
@property(retain, nonatomic) UILabel *shouldMuteOnVideoSwitchLabel; // @synthesize shouldMuteOnVideoSwitchLabel=_shouldMuteOnVideoSwitchLabel;
@property(retain, nonatomic) UISwitch *userControlEnableSwitch; // @synthesize userControlEnableSwitch=_userControlEnableSwitch;
@property(retain, nonatomic) UILabel *userControlEnableSwitchLabel; // @synthesize userControlEnableSwitchLabel=_userControlEnableSwitchLabel;
@property(retain, nonatomic) GDTVideoConfig *videoConfig; // @synthesize videoConfig=_videoConfig;
@property(retain, nonatomic) UISwitch *videoDetailPageEnableSwitch; // @synthesize videoDetailPageEnableSwitch=_videoDetailPageEnableSwitch;
@property(retain, nonatomic) UILabel *videoDetailPageEnableSwitchLabel; // @synthesize videoDetailPageEnableSwitchLabel=_videoDetailPageEnableSwitchLabel;
@property(retain, nonatomic) UISwitch *videoDetailPageMuteSwitch; // @synthesize videoDetailPageMuteSwitch=_videoDetailPageMuteSwitch;
@property(retain, nonatomic) UILabel *videoDetailPageMuteSwitchLabel; // @synthesize videoDetailPageMuteSwitchLabel=_videoDetailPageMuteSwitchLabel;
- (void)showInView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

