//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTFullScreenModel.h"

@class NSString;

@interface GDTUnifiedTemplateModel : GDTFullScreenModel
{
    NSString *_htmlTemplate;
    double _templateHeight;
    double _templateWidth;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *htmlTemplate; // @synthesize htmlTemplate=_htmlTemplate;
- (id)initWithAdDict:(id)arg1;
- (id)initWithAdDict:(id)arg1 htmlTemplate:(id)arg2;
@property(nonatomic) double templateHeight; // @synthesize templateHeight=_templateHeight;
@property(nonatomic) double templateWidth; // @synthesize templateWidth=_templateWidth;

@end

