//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError;
@protocol GDTUnifiedinterstitialAdNetworkAdapterProtocol;

@protocol GDTUnifiedInterstitialAdNetworkConnectorProtocol <NSObject>
- (void)GDTfunctiona5Qo5w:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionf3WjUh:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionf3tzMY:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionf7igMB:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionh5KUJj:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctioni1TezJ:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionm0f2KX:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionm38hoM:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionm5TBas:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctiono9Yx6E:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionq7Gssj:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionr7vip0:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctions9B4Fq:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1 error:(NSError *)arg2;
- (void)GDTfunctiont74a0g:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctiont8t6Ye:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1 playerStatusChanged:(unsigned long long)arg2;
- (void)GDTfunctionx3nDF6:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
- (void)GDTfunctionz0hjPk:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1 error:(NSError *)arg2;
- (void)GDTfunctionz1VIql:(id <GDTUnifiedinterstitialAdNetworkAdapterProtocol>)arg1;
@end

