//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTAdBaseModel.h"

#import "GDTUnifiedNativeAdDataObjectAdapterProtocol-Protocol.h"

@class GDTVideoConfig, NSArray, NSNumber, NSString;

@interface GDTUnifiedNativeAdModel : GDTAdBaseModel <GDTUnifiedNativeAdDataObjectAdapterProtocol>
{
    _Bool _isThreeImgsAd;
    NSArray *_imageList;
    long long _playBeginTime;
}

- (void).cxx_destruct;
- (_Bool)GDTfunctionc2bb2T:(id)arg1;
@property(readonly, nonatomic) double appRating;
@property(readonly, copy, nonatomic) NSString *callToAction;
@property(readonly, nonatomic) double duration;
@property(readonly, nonatomic) long long eCPM;
@property(readonly, copy, nonatomic) NSString *eCPMLevel;
- (_Bool)equalsAdData:(id)arg1;
@property(retain, nonatomic) NSArray *imageList; // @synthesize imageList=_imageList;
@property(readonly, copy, nonatomic) NSString *imageUrl;
- (id)initWithAdDict:(id)arg1;
@property(nonatomic) _Bool isThreeImgsAd; // @synthesize isThreeImgsAd=_isThreeImgsAd;
@property(readonly, nonatomic) _Bool isVastAd;
@property(readonly, copy, nonatomic) NSArray *mediaUrlList;
@property(nonatomic) long long playBeginTime; // @synthesize playBeginTime=_playBeginTime;
@property(readonly, nonatomic) _Bool skippable;
@property(readonly, copy, nonatomic) NSString *vastContent;
@property(readonly, copy, nonatomic) NSString *vastTagUrl;

// Remaining properties
@property(readonly, nonatomic) NSNumber *appPrice;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy, nonatomic) NSString *desc;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy, nonatomic) NSString *iconUrl;
@property(readonly, nonatomic) long long imageHeight;
@property(readonly, nonatomic) long long imageWidth;
@property(readonly, nonatomic) _Bool isAppAd;
@property(readonly, nonatomic) _Bool isVideoAd;
@property(readonly) Class superclass;
@property(readonly, copy, nonatomic) NSString *title;
@property(retain, nonatomic) GDTVideoConfig *videoConfig;

@end

