//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;
@protocol OS_dispatch_queue;

@interface GDTVideoCardViewRenderConfig : NSObject
{
    _Bool _useWebViewRending;
    NSString *_url;
    long long _dataLength;
    NSObject<OS_dispatch_queue> *_queue;
    NSString *_htmlString;
}

- (void).cxx_destruct;
- (void)GDTfunctione4sfbb:(CDUnknownBlockType)arg1;
- (void)GDTfunctionh2dnYy:(CDUnknownBlockType)arg1;
@property(nonatomic) long long dataLength; // @synthesize dataLength=_dataLength;
@property(copy, nonatomic) NSString *htmlString; // @synthesize htmlString=_htmlString;
- (id)initWithURL:(id)arg1;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) _Bool useWebViewRending; // @synthesize useWebViewRending=_useWebViewRending;

@end

