//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GDTPlayerControlProtocol-Protocol.h"
#import "GDTVideoCardViewProtocol-Protocol.h"
#import "GDTWebViewDelegate-Protocol.h"

@class GDTAdWKWebView, GDTPlayer, GDTRewardVideoAdModel, GDTVideoCardViewRenderConfig, NSString;

@interface GDTWebViewVideoCardView : UIView <GDTWebViewDelegate, GDTVideoCardViewProtocol, GDTPlayerControlProtocol>
{
    int _adType;
    CDUnknownBlockType _closeButtonClickCallback;
    CDUnknownBlockType _adClickCallback;
    CDUnknownBlockType _loadFailCallback;
    long long _cardShowTime;
    long long _closeButtonShowTime;
    GDTPlayer *_player;
    long long _pageSource;
    double _playBeginTime;
    GDTVideoCardViewRenderConfig *_viewRenderConfig;
    GDTAdWKWebView *_webView;
    GDTRewardVideoAdModel *_adModel;
    NSString *_noticeString;
}

- (void).cxx_destruct;
- (_Bool)GDTfunctione6bSPR:(id)arg1 GDTfunctionh1EwgM:(id)arg2;
- (void)GDTfunctione6bSPR:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)GDTfunctione6bSPR:(id)arg1 didFinishNavigation:(id)arg2;
- (void)GDTfunctione6bSPR:(id)arg1 handleJsRequest:(id)arg2;
- (void)GDTfunctionh2KuTN;
- (struct CGRect)GDTfunctiont6F8M7;
- (void)GDTfunctiont9zSCy:(id)arg1 adType:(int)arg2 noticeString:(id)arg3;
@property(copy, nonatomic) CDUnknownBlockType adClickCallback; // @synthesize adClickCallback=_adClickCallback;
@property(retain, nonatomic) GDTRewardVideoAdModel *adModel; // @synthesize adModel=_adModel;
@property(nonatomic) int adType; // @synthesize adType=_adType;
@property(nonatomic) long long cardShowTime; // @synthesize cardShowTime=_cardShowTime;
@property(copy, nonatomic) CDUnknownBlockType closeButtonClickCallback; // @synthesize closeButtonClickCallback=_closeButtonClickCallback;
@property(nonatomic) long long closeButtonShowTime; // @synthesize closeButtonShowTime=_closeButtonShowTime;
- (void)gdt_player:(id)arg1 currentTime:(double)arg2 totalTime:(double)arg3;
- (id)init;
@property(copy, nonatomic) CDUnknownBlockType loadFailCallback; // @synthesize loadFailCallback=_loadFailCallback;
@property(copy, nonatomic) NSString *noticeString; // @synthesize noticeString=_noticeString;
@property(nonatomic) long long pageSource; // @synthesize pageSource=_pageSource;
@property(nonatomic) double playBeginTime; // @synthesize playBeginTime=_playBeginTime;
@property(nonatomic) __weak GDTPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) GDTVideoCardViewRenderConfig *viewRenderConfig; // @synthesize viewRenderConfig=_viewRenderConfig;
@property(retain, nonatomic) GDTAdWKWebView *webView; // @synthesize webView=_webView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

