//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSURLSessionDataDelegate-Protocol.h"

@class NSMutableDictionary, NSString, NSURLSession;
@protocol HMDBUURLBackgrounSessionManagerDelegate;

@interface HMDBUURLBackgrounSessionManager : NSObject <NSURLSessionDataDelegate>
{
    id <HMDBUURLBackgrounSessionManagerDelegate> _delegate;
    NSURLSession *_session;
    NSMutableDictionary *_responseDataDict;
}

- (void).cxx_destruct;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
@property(nonatomic) __weak id <HMDBUURLBackgrounSessionManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)getAllUploadTasks;
- (id)init;
- (id)initWithDelegate:(id)arg1 configuration:(id)arg2;
- (void)queryAllUploadTasks:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSMutableDictionary *responseDataDict; // @synthesize responseDataDict=_responseDataDict;
- (id)responseDataWithTask:(id)arg1;
@property(retain, nonatomic) NSURLSession *session; // @synthesize session=_session;
- (id)uploadWithRequest:(id)arg1 filePath:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

