//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIColor, UIFont, UIImage, UIImageView, UILabel;

@interface ImageWithLabel : UIView
{
    NSString *_image;
    NSString *_text;
    double _radius;
    UIFont *_labelFont;
    UIColor *_labelColor;
    long long _numberOfLines;
    long long _textAlign;
    UIColor *_labelBacgroudColor;
    long long _labelLocation;
    long long _labelOffsetX;
    long long _labelOffsetY;
    long long _contentMode;
    double _imageScale;
    UIImageView *_imageView;
    UILabel *_label;
    UIImage *_placeHolder;
    struct CGSize _imageSize;
}

+ (id)imageLabelWithFrame:(struct CGRect)arg1 Image:(id)arg2 LabelText:(id)arg3;
+ (id)imageLabelWithFrame:(struct CGRect)arg1 placeHolder:(id)arg2 LabelText:(id)arg3;
- (void).cxx_destruct;
@property(nonatomic) long long contentMode; // @synthesize contentMode=_contentMode;
@property(copy, nonatomic) NSString *image; // @synthesize image=_image;
@property(nonatomic) double imageScale; // @synthesize imageScale=_imageScale;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize=_imageSize;
@property(nonatomic) __weak UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1 Image:(id)arg2 LabelTest:(id)arg3;
@property(nonatomic) __weak UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIColor *labelBacgroudColor; // @synthesize labelBacgroudColor=_labelBacgroudColor;
@property(retain, nonatomic) UIColor *labelColor; // @synthesize labelColor=_labelColor;
@property(retain, nonatomic) UIFont *labelFont; // @synthesize labelFont=_labelFont;
@property(nonatomic) long long labelLocation; // @synthesize labelLocation=_labelLocation;
@property(nonatomic) long long labelOffsetX; // @synthesize labelOffsetX=_labelOffsetX;
@property(nonatomic) long long labelOffsetY; // @synthesize labelOffsetY=_labelOffsetY;
- (void)layoutSubviews;
@property(nonatomic) long long numberOfLines; // @synthesize numberOfLines=_numberOfLines;
@property(retain, nonatomic) UIImage *placeHolder; // @synthesize placeHolder=_placeHolder;
@property(nonatomic) double radius; // @synthesize radius=_radius;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) long long textAlign; // @synthesize textAlign=_textAlign;
- (void)setlabelOffsetY:(long long)arg1;

@end

