//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JCORECacheChannel : NSObject
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)badgeNumberUserDefault;
+ (id)batteryInfoCheckTime;
+ (id)collectLocationCheckTime;
+ (id)crashCheckTime;
+ (id)crashLog;
+ (id)deviceInfoCheckTime;
+ (id)deviceTokenUpdateTime;
+ (id)lastApnsState;
+ (id)lastDeviceInfo;
+ (id)lastLocation;
+ (id)locationCheckTime;
+ (id)locationCollectFrequency;
+ (id)locationLog;
+ (id)locationReportDisable;
+ (id)locationReportFrequency;
+ (id)read:(id)arg1;
+ (void)read:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)serverUnavailableFreeze;
+ (id)sessionLeftTime;
+ (id)sessionStartTime;
+ (void)setBadgeNumberUserDefault:(id)arg1;
+ (void)setBatteryInfoCheckTime:(id)arg1;
+ (void)setCollectLocationCheckTime:(id)arg1;
+ (void)setCrashCheckTime:(id)arg1;
+ (void)setCrashLog:(id)arg1;
+ (void)setDeviceInfoCheckTime:(id)arg1;
+ (void)setDeviceTokenUpdateTime:(id)arg1;
+ (void)setLastApnsState:(id)arg1;
+ (void)setLastDeviceInfo:(id)arg1;
+ (void)setLastLocation:(id)arg1;
+ (void)setLocationCheckTime:(id)arg1;
+ (void)setLocationCollectFrequency:(id)arg1;
+ (void)setLocationLog:(id)arg1;
+ (void)setLocationReportDisable:(id)arg1;
+ (void)setLocationReportFrequency:(id)arg1;
+ (void)setServerUnavailableFreeze:(id)arg1;
+ (void)setSessionLeftTime:(id)arg1;
+ (void)setSessionStartTime:(id)arg1;
+ (void)setUserProperty:(id)arg1;
+ (id)sharedChannel;
+ (id)userProperty;
+ (_Bool)write:(id)arg1;
+ (void)write:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)read:(id)arg1;
- (void)read:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)write:(id)arg1;
- (void)write:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

