//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JCOREInterface : NSObject
{
}

+ (id)JAnalyticsVersion;
+ (id)JMessageVersion;
+ (id)JPushVersion;
+ (id)JShareVersion;
+ (id)JiGuangPushConfig;
+ (id)JiGuangPushConfigAndReset;
+ (id)JiGuangUserDefaults;
+ (id)accountID;
+ (void)addMessageBlock:(CDUnknownBlockType)arg1;
+ (void)addTcpProcotolBlock:(CDUnknownBlockType)arg1;
+ (id)advertisingIdentifier;
+ (_Bool)analyticsExist;
+ (id)appKey;
+ (id)appVersion;
+ (id)applicationKey;
+ (id)carrierName;
+ (void)changeLoggerLevel:(long long)arg1;
+ (id)clientNotificationCenter;
+ (id)currentDeviceToken;
+ (id)currentLocation;
+ (void)dequeueRequest:(id)arg1;
+ (_Bool)deviceTokenUpdated;
+ (void)dispatchMessage:(id)arg1;
+ (id)findBlockedRequest:(unsigned short)arg1;
+ (id)findSendingRequest:(unsigned short)arg1;
+ (id)generation;
+ (unsigned char)generationNumber;
+ (void)getRegistrationIDCompletionHandler:(CDUnknownBlockType)arg1;
+ (_Bool)hasMultiBusiness;
+ (_Bool)isAppRegistered;
+ (_Bool)isCloseSocket;
+ (_Bool)isSetup;
+ (_Bool)jpushOnly;
+ (_Bool)loadWithUrl:(id)arg1;
+ (id)macAddress;
+ (_Bool)messageExist;
+ (id)modelName;
+ (id)objectForKey:(id)arg1 position:(long long)arg2;
+ (id)oldDeviceToken;
+ (void)onAckOrRespReceived:(id)arg1;
+ (id)password;
+ (void)performSelInWorkThread:(SEL)arg1 target:(id)arg2 withObject:(id)arg3;
+ (_Bool)pushConfigController;
+ (_Bool)pushExist;
+ (id)readRegistrationID;
+ (void)removeAllObjectsposition:(long long)arg1;
+ (void)removeBlockedRequestWith:(unsigned long long)arg1;
+ (void)removeObjectForKey:(id)arg1 position:(long long)arg2;
+ (void)removeObjectsForKeys:(id)arg1 position:(long long)arg2;
+ (void)reportWithInvaildToken:(id)arg1;
+ (_Bool)setAppKey:(id)arg1 channel:(id)arg2 apsProduction:(_Bool)arg3 advertisingIdentifier:(id)arg4;
+ (void)setCrashLogON;
+ (void)setCurrentDeviceToken:(id)arg1;
+ (void)setDeviceTokenUpdate:(_Bool)arg1;
+ (void)setLatitude:(id)arg1;
+ (void)setNewAdvertisingIdentifier:(id)arg1;
+ (void)setObject:(id)arg1 forKey:(id)arg2 position:(long long)arg3;
+ (void)setViewLogSecond:(id)arg1;
+ (void)setViewStart:(id)arg1;
+ (void)setViewStop:(id)arg1;
+ (void)setup;
+ (void)setupJPushLogger;
+ (_Bool)shareExist;
+ (id)ssid;
+ (void)synchronizeData;
+ (void)trySetupSession;
+ (void)tryUploadIDFA;
+ (unsigned long long)uid;
+ (id)userAddress;

@end

