//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface JCORESisReportModel : NSObject <NSCopying>
{
    unsigned char _type;
    unsigned char _net;
    NSString *_addr;
    unsigned long long _uid;
    unsigned long long _rtime;
    unsigned long long _interval;
    double _lat;
    double _lng;
    unsigned long long _ltime;
    long long _code;
    NSString *_appkey;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *addr; // @synthesize addr=_addr;
@property(copy, nonatomic) NSString *appkey; // @synthesize appkey=_appkey;
@property(nonatomic) long long code; // @synthesize code=_code;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)info;
@property(nonatomic) unsigned long long interval; // @synthesize interval=_interval;
@property(nonatomic) double lat; // @synthesize lat=_lat;
@property(nonatomic) double lng; // @synthesize lng=_lng;
@property(nonatomic) unsigned long long ltime; // @synthesize ltime=_ltime;
@property(nonatomic) unsigned char net; // @synthesize net=_net;
@property(nonatomic) unsigned long long rtime; // @synthesize rtime=_rtime;
@property(nonatomic) unsigned char type; // @synthesize type=_type;
@property(nonatomic) unsigned long long uid; // @synthesize uid=_uid;

@end

