//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "JCOREConnectManagerDelegate-Protocol.h"

@class JCORENetwork, JCORENetworkQueue, NSString;

@interface JCORETcpChannelController : NSObject <JCOREConnectManagerDelegate>
{
    _Bool _isLogined;
    unsigned short _serverVersion;
    JCORENetwork *_currentNetwork;
    JCORENetworkQueue *_tcpBlockedQueue;
    JCORENetworkQueue *_tcpSendingQueue;
}

- (void).cxx_destruct;
- (_Bool)ackOrRespRequired:(id)arg1;
- (_Bool)canBeQueuedIfNotLogin:(id)arg1;
- (void)closeSocket;
@property(retain, nonatomic) JCORENetwork *currentNetwork; // @synthesize currentNetwork=_currentNetwork;
- (void)dealloc;
- (void)dequeueRequest:(id)arg1;
- (void)didLogin:(id)arg1;
- (void)doSendTcpRequest:(id)arg1;
- (void)enqueueRequest:(id)arg1;
- (void)errorCallBack:(id)arg1 code:(long long)arg2 des:(id)arg3;
- (id)findBlockedRequest:(unsigned short)arg1;
- (id)findSendingRequest:(unsigned short)arg1;
- (_Bool)hasHighPriority:(unsigned char)arg1;
- (id)init;
- (_Bool)isCloseSocket;
- (_Bool)isExclusive:(unsigned char)arg1;
@property(nonatomic) _Bool isLogined; // @synthesize isLogined=_isLogined;
- (_Bool)loginRequired:(id)arg1;
- (void)onAckOrRespReceived:(id)arg1;
- (id)parsePacketData:(id)arg1;
- (void)reenqueueSendingRequests;
- (id)requestData:(id)arg1;
- (void)send:(id)arg1;
- (void)sendQueueEmpty:(id)arg1;
- (void)sendTcpData:(id)arg1;
@property(nonatomic) unsigned short serverVersion; // @synthesize serverVersion=_serverVersion;
@property(retain, nonatomic) JCORENetworkQueue *tcpBlockedQueue; // @synthesize tcpBlockedQueue=_tcpBlockedQueue;
@property(retain, nonatomic) JCORENetworkQueue *tcpSendingQueue; // @synthesize tcpSendingQueue=_tcpSendingQueue;
- (void)setupService;
- (void)socket:(id)arg1 connectStateChanged:(unsigned long long)arg2;
- (void)socket:(id)arg1 noRecvData:(id)arg2;
- (void)socket:(id)arg1 recvData:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (void)socket:(id)arg1 sentData:(id)arg2;
- (void)socket:(id)arg1 unsentData:(id)arg2;
- (void)startTcpConnect;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

