//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface JCOREBasicCache : NSObject
{
    struct _opaque_pthread_mutex_t _mutex;
    NSString *_path;
    _Bool _persistent;
    NSString *_dir;
}

- (void).cxx_destruct;
- (_Bool)createDirectory:(id)arg1;
@property(retain, nonatomic) NSString *dir; // @synthesize dir=_dir;
@property(nonatomic) struct _opaque_pthread_mutex_t mutex; // @synthesize mutex=_mutex;
@property(readonly, nonatomic) NSString *path;
@property(nonatomic) _Bool persistent; // @synthesize persistent=_persistent;
- (id)read:(id)arg1;
- (_Bool)read:(id)arg1 resultHandler:(CDUnknownBlockType)arg2;
- (void)readDirectoryWithHandler:(CDUnknownBlockType)arg1;
- (_Bool)write:(id)arg1;
- (_Bool)write:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

