//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JCORETcpObject.h"

#import "JCOREJSONProtocol-Protocol.h"
#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSMutableData, NSTimer;

@interface JPUSHRequest : JCORETcpObject <NSCopying, NSCoding, JCOREJSONProtocol>
{
    NSMutableData *_packetData;
    unsigned char _controlFlag;
    unsigned char _version;
    unsigned char _protocolType;
    unsigned short _rid;
    unsigned long long _uid;
    CDUnknownBlockType _packetLengthExceedBlk;
    NSTimer *_ackTimeoutTimer;
}

- (void).cxx_destruct;
- (_Bool)ackOrRespRequired;
- (_Bool)ackOrRespRequiredForVersion1;
@property(nonatomic) __weak NSTimer *ackTimeoutTimer; // @synthesize ackTimeoutTimer=_ackTimeoutTimer;
- (id)bodyData;
- (_Bool)canBeQueuedIfNotLogin;
@property(nonatomic) unsigned char controlFlag; // @synthesize controlFlag=_controlFlag;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)getRidID;
- (_Bool)hasHighPriority;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqualToRequest:(id)arg1;
- (_Bool)isExclusive;
- (_Bool)isIMMessageRequest;
- (void)jpush_fromJSONValue:(id)arg1;
- (id)jpush_jsonClassType;
- (id)jpush_toJSON;
- (_Bool)loginRequired;
- (void)onAckTimeout:(id)arg1;
- (_Bool)packData;
- (id)packetData;
@property(copy, nonatomic) CDUnknownBlockType packetLengthExceedBlk; // @synthesize packetLengthExceedBlk=_packetLengthExceedBlk;
- (unsigned char)protocolType;
- (unsigned short)rid;
- (void)send;
- (void)setProtocolType:(unsigned char)arg1;
- (void)setRid:(unsigned short)arg1;
- (void)setUid:(unsigned long long)arg1;
- (void)setVersion:(unsigned char)arg1;
- (void)startAckTimeoutTimer;
- (void)stopAckTimeoutTimer;
- (unsigned long long)uid;
- (unsigned char)version;

@end

