//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSArray;

@interface LBHamburgerButton : UIButton
{
    double _lineHeight;
    double _lineWidth;
    double _lineSpacing;
    struct CGPoint _lineCenter;
    NSArray *_lineArray;
    _Bool _lineCreated;
    int _hamburgerState;
    int _hamburgerType;
    double _hamburgerAnimationDuration;
}

+ (id)colorWithHexString:(id)arg1 alpha:(double)arg2;
- (void).cxx_destruct;
- (void)animateButtonForward:(_Bool)arg1;
- (id)createLayerWithFrame:(struct CGRect)arg1 andColor:(id)arg2 atPosition:(struct CGPoint)arg3;
@property double hamburgerAnimationDuration; // @synthesize hamburgerAnimationDuration=_hamburgerAnimationDuration;
@property(readonly) int hamburgerState; // @synthesize hamburgerState=_hamburgerState;
@property int hamburgerType; // @synthesize hamburgerType=_hamburgerType;
- (id)initWithFrame:(struct CGRect)arg1 withHamburgerType:(int)arg2 lineWidth:(double)arg3 lineHeight:(double)arg4 lineSpacing:(double)arg5 lineCenter:(struct CGPoint)arg6 color:(id)arg7;
- (id)keyframeAnimationsOfLineIndex:(long long)arg1 forward:(_Bool)arg2;
- (double)scale:(double)arg1;
- (void)setState:(int)arg1;
- (void)setUpHamburgerWithType:(int)arg1 lineWidth:(double)arg2 lineHeight:(double)arg3 lineSpacing:(double)arg4 lineCenter:(struct CGPoint)arg5 color:(id)arg6;
- (void)switchState;

@end

