//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class LEEAlertConfigModel, LEECustomView, NSString, UIVisualEffectView, UIWindow;

@interface LEEBaseViewController : UIViewController <UIGestureRecognizerDelegate>
{
    _Bool _isShowing;
    _Bool _isClosing;
    LEEAlertConfigModel *_config;
    UIWindow *_currentKeyWindow;
    UIVisualEffectView *_backgroundVisualEffectView;
    long long _orientationType;
    LEECustomView *_customView;
    CDUnknownBlockType _openFinishBlock;
    CDUnknownBlockType _closeFinishBlock;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIVisualEffectView *backgroundVisualEffectView; // @synthesize backgroundVisualEffectView=_backgroundVisualEffectView;
- (void)closeAnimationsWithCompletionBlock:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) CDUnknownBlockType closeFinishBlock; // @synthesize closeFinishBlock=_closeFinishBlock;
@property(retain, nonatomic) LEEAlertConfigModel *config; // @synthesize config=_config;
@property(retain, nonatomic) UIWindow *currentKeyWindow; // @synthesize currentKeyWindow=_currentKeyWindow;
@property(retain, nonatomic) LEECustomView *customView; // @synthesize customView=_customView;
- (void)dealloc;
@property(nonatomic) _Bool isClosing; // @synthesize isClosing=_isClosing;
@property(nonatomic) _Bool isShowing; // @synthesize isShowing=_isShowing;
@property(copy, nonatomic) CDUnknownBlockType openFinishBlock; // @synthesize openFinishBlock=_openFinishBlock;
@property(nonatomic) long long orientationType; // @synthesize orientationType=_orientationType;
- (_Bool)shouldAutorotate;
- (void)showAnimationsWithCompletionBlock:(CDUnknownBlockType)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

