//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSString, WNYD_NetworkManager;

@interface likeCountView : UIButton
{
    _Bool _islike;
    _Bool _isReplyComment;
    NSString *_requestID;
    long long _likeCount;
    CDUnknownBlockType _onClick;
    WNYD_NetworkManager *_netManager;
}

+ (id)likeCountViewWithCount:(long long)arg1 requestID:(id)arg2;
- (void).cxx_destruct;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) _Bool isReplyComment; // @synthesize isReplyComment=_isReplyComment;
@property(nonatomic) _Bool islike; // @synthesize islike=_islike;
- (void)like;
@property(nonatomic) long long likeCount; // @synthesize likeCount=_likeCount;
@property(retain, nonatomic) WNYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
@property(copy, nonatomic) CDUnknownBlockType onClick; // @synthesize onClick=_onClick;
@property(copy, nonatomic) NSString *requestID; // @synthesize requestID=_requestID;
- (void)setup;

@end

