//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MenuModel : NSObject
{
    NSString *_imageName;
    NSString *_itemName;
}

+ (id)MenuModelWithDict:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;
- (id)initWithDict:(id)arg1;
@property(copy, nonatomic) NSString *itemName; // @synthesize itemName=_itemName;

@end

