//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileManager, NSMutableDictionary, NSString;

@interface ModelCacheManager : NSObject
{
    NSString *_cacheDirectory;
    NSFileManager *_fileManager;
    NSMutableDictionary *_modelCache;
}

+ (id)manager;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *cacheDirectory; // @synthesize cacheDirectory=_cacheDirectory;
- (id)cacheForKey:(id)arg1;
- (id)cachePathForKey:(id)arg1;
- (void)clearCache;
- (void)dealloc;
@property(retain, nonatomic) NSFileManager *fileManager; // @synthesize fileManager=_fileManager;
- (id)init;
@property(retain, nonatomic) NSMutableDictionary *modelCache; // @synthesize modelCache=_modelCache;
- (void)removeAllCache;
- (void)removeCacheForKey:(id)arg1;
- (void)saveCache;
- (void)setCache:(id)arg1 forKey:(id)arg2;

@end

