//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MYApprentice : NSObject
{
    long long _task_type;
    NSString *_button;
    NSString *_url;
    NSString *_name;
    NSString *_explain;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *button; // @synthesize button=_button;
@property(copy, nonatomic) NSString *explain; // @synthesize explain=_explain;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long task_type; // @synthesize task_type=_task_type;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;

@end

