//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (Safe)
+ (id)hookArrayWithObject:(id)arg1;
+ (id)hookArrayWithObjects:(const id *)arg1 count:(unsigned long long)arg2;
+ (void)load;
- (id)hookObjectAtIndex:(unsigned long long)arg1;
- (id)hookObjectAtIndexedSubscript:(long long)arg1;
- (id)hookSubarrayWithRange:(struct _NSRange)arg1;
@end

