//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSData.h>

@interface NSData (AES128)
+ (id)AES128Decrypt:(id)arg1;
+ (id)AES128Decrypt:(id)arg1 withKey:(id)arg2 withIvStr:(id)arg3;
+ (id)AES128Encrypt:(id)arg1 withKey:(id)arg2 withIvStr:(id)arg3;
+ (id)processDecodedString:(id)arg1;
+ (_Bool)validKey:(id)arg1;
- (id)processDecodedString:(id)arg1;
@end

