//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableAttributedString.h>

@interface NSMutableAttributedString (Safe)
+ (void)load;
- (void)hookAddAttribute:(id)arg1 value:(id)arg2 range:(struct _NSRange)arg3;
- (void)hookAddAttributes:(id)arg1 range:(struct _NSRange)arg2;
- (id)hookAttribute:(id)arg1 atIndex:(unsigned long long)arg2 effectiveRange:(struct _NSRange *)arg3;
- (id)hookAttributedSubstringFromRange:(struct _NSRange)arg1;
- (void)hookDeleteCharactersInRange:(struct _NSRange)arg1;
- (void)hookEnumerateAttribute:(id)arg1 inRange:(struct _NSRange)arg2 options:(unsigned long long)arg3 usingBlock:(CDUnknownBlockType)arg4;
- (void)hookEnumerateAttributesInRange:(struct _NSRange)arg1 options:(unsigned long long)arg2 usingBlock:(CDUnknownBlockType)arg3;
- (id)hookInitWithString:(id)arg1;
- (id)hookInitWithString:(id)arg1 attributes:(id)arg2;
- (void)hookRemoveAttribute:(id)arg1 range:(struct _NSRange)arg2;
- (void)hookReplaceCharactersInRange:(struct _NSRange)arg1 withAttributedString:(id)arg2;
- (void)hookReplaceCharactersInRange:(struct _NSRange)arg1 withString:(id)arg2;
- (void)hookSetAttributes:(id)arg1 range:(struct _NSRange)arg2;
@end

