//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (Safe)
+ (id)hookStringWithCString:(const char *)arg1 encoding:(unsigned long long)arg2;
+ (id)hookStringWithUTF8String:(const char *)arg1;
+ (void)load;
- (id)hookInitWithCString:(const char *)arg1 encoding:(unsigned long long)arg2;
- (id)hookInitWithString:(id)arg1;
- (id)hookInitWithUTF8String:(const char *)arg1;
- (struct _NSRange)hookRangeOfString:(id)arg1 options:(unsigned long long)arg2 range:(struct _NSRange)arg3 locale:(id)arg4;
- (id)hookStringByAppendingString:(id)arg1;
- (id)hookSubstringFromIndex:(unsigned long long)arg1;
- (id)hookSubstringToIndex:(unsigned long long)arg1;
- (id)hookSubstringWithRange:(struct _NSRange)arg1;
@end

