//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CFNetwork/NSURLSession.h>

@interface NSURLSession (ResDownloader)
- (CDUnknownBlockType)GDTfunctionh2qlim;
- (CDUnknownBlockType)GDTfunctionp6f7pl;
- (unsigned long long)GDTfunctionr2Onlj;
- (unsigned long long)GDTfunctionw5xLcw;
- (void)setGDTfunctionh2qlim:(CDUnknownBlockType)arg1;
- (void)setGDTfunctionp6f7pl:(CDUnknownBlockType)arg1;
- (void)setGDTfunctionr2Onlj:(unsigned long long)arg1;
- (void)setGDTfunctionw5xLcw:(unsigned long long)arg1;
@end

