//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "BUNativeAdDelegate-Protocol.h"

@class BUNativeAd, NSString, UIButton, UIImageView, UILabel, UIView;
@protocol PangleNativeInterstitialViewDelegate;

@interface PangleNativeInterstitialView : UIViewController <BUNativeAdDelegate>
{
    id <PangleNativeInterstitialViewDelegate> _delegate;
    BUNativeAd *_nativeAd;
    UIView *_backgroundView;
    UIView *_whiteBackgroundView;
    UIImageView *_logoImgeView;
    UIButton *_dislikeButton;
    UILabel *_titleLable;
    UILabel *_describeLable;
    UIImageView *_interstitialAdView;
    UIButton *_dowloadButton;
    UIImageView *_mediaIcon;
    UIView *_starView;
}

- (void).cxx_destruct;
- (void)addAccessibilityIdentifier;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
- (void)buildupView;
@property(nonatomic) __weak id <PangleNativeInterstitialViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UILabel *describeLable; // @synthesize describeLable=_describeLable;
@property(retain, nonatomic) UIButton *dislikeButton; // @synthesize dislikeButton=_dislikeButton;
@property(retain, nonatomic) UIButton *dowloadButton; // @synthesize dowloadButton=_dowloadButton;
- (double)getStringHeightWithText:(id)arg1 font:(id)arg2 viewWidth:(double)arg3;
@property(retain, nonatomic) UIImageView *interstitialAdView; // @synthesize interstitialAdView=_interstitialAdView;
@property(readonly, nonatomic, getter=isAdValid) _Bool adValid;
@property(retain, nonatomic) UIImageView *logoImgeView; // @synthesize logoImgeView=_logoImgeView;
@property(retain, nonatomic) UIImageView *mediaIcon; // @synthesize mediaIcon=_mediaIcon;
@property(retain, nonatomic) BUNativeAd *nativeAd; // @synthesize nativeAd=_nativeAd;
- (void)refreshUIWithAd:(id)arg1;
@property(retain, nonatomic) UIView *starView; // @synthesize starView=_starView;
@property(retain, nonatomic) UILabel *titleLable; // @synthesize titleLable=_titleLable;
@property(retain, nonatomic) UIView *whiteBackgroundView; // @synthesize whiteBackgroundView=_whiteBackgroundView;
- (_Bool)showAdFromRootViewController:(id)arg1 delegate:(id)arg2;
- (void)tapCloseButton;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

