//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface PTModel : NSObject
{
    UIImage *_image;
    NSString *_text;
    NSString *_font;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *font; // @synthesize font=_font;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;

@end

