//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CADisplayLink, NSString, UIColor, UIFont, UIImageView, UILabel;

@interface SGHorseRaceLampView : UIView
{
    _Bool _isStop;
    NSString *_imageNage;
    NSString *_title;
    UIColor *_titleColor;
    UIFont *_titleFont;
    double _scrollTimeInterval;
    CDUnknownBlockType _selectedBlock;
    UIImageView *_imageView;
    UIView *_contentView;
    UILabel *_contentLabel;
    CADisplayLink *_displayLink;
    double _contentViewW;
}

- (void).cxx_destruct;
- (double)SG_widthWithString:(id)arg1 font:(id)arg2;
- (void)addAnimationWithContentLabel;
- (void)addAnimationWithFirstContentLabel;
- (void)awakeFromNib;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) double contentViewW; // @synthesize contentViewW=_contentViewW;
- (void)dealloc;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(copy, nonatomic) NSString *imageNage; // @synthesize imageNage=_imageNage;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)initialization;
@property(nonatomic) _Bool isStop; // @synthesize isStop=_isStop;
- (void)layoutSubviews;
@property(nonatomic) double scrollTimeInterval; // @synthesize scrollTimeInterval=_scrollTimeInterval;
@property(copy, nonatomic) CDUnknownBlockType selectedBlock; // @synthesize selectedBlock=_selectedBlock;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(retain, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
- (void)setupSubviews;
- (void)tapContentView;
- (void)viewRun;

@end

