//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, TKActionSheetOverlayWindow, UIPanGestureRecognizer, UITapGestureRecognizer, UIView;
@protocol TKActionSheetControllerDelegate;

@interface TKActionSheetController : UIViewController <UIGestureRecognizerDelegate>
{
    _Bool _dismissWhenTapWindow;
    _Bool _dragable;
    _Bool _vignetteBackground;
    UIView *_customView;
    id <TKActionSheetControllerDelegate> _delegate;
    UIView *_warpperView;
    UIView *_containerView;
    TKActionSheetOverlayWindow *_backgroundWindow;
    NSMutableDictionary *_titleColorDic;
    NSMutableArray *_actions;
    double _height;
    UITapGestureRecognizer *_tapGestureRecognizer;
    UIPanGestureRecognizer *_panGestureRecognizer;
    CDUnknownBlockType _dismissWhenTapWindowHandler;
}

+ (void)initialize;
+ (id)sheetWithCustomView:(id)arg1;
+ (id)sheetWithTitle:(id)arg1;
+ (id)sheetWithViewController:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *actions; // @synthesize actions=_actions;
- (void)addButtonWithTitle:(id)arg1 atIndex:(long long)arg2 block:(CDUnknownBlockType)arg3;
- (void)addButtonWithTitle:(id)arg1 atIndex:(long long)arg2 handler:(CDUnknownBlockType)arg3;
- (void)addButtonWithTitle:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)addButtonWithTitle:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)addButtonWithTitle:(id)arg1 type:(long long)arg2 handler:(CDUnknownBlockType)arg3 atIndex:(long long)arg4;
@property(retain, nonatomic) TKActionSheetOverlayWindow *backgroundWindow; // @synthesize backgroundWindow=_backgroundWindow;
- (void)buttonClicked:(id)arg1;
- (unsigned long long)buttonCount;
- (id)buttonWithAction:(id)arg1;
@property(readonly, nonatomic) long long cancelButtonIndex;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *customView; // @synthesize customView=_customView;
- (void)dealloc;
@property(nonatomic) __weak id <TKActionSheetControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool dismissWhenTapWindow; // @synthesize dismissWhenTapWindow=_dismissWhenTapWindow;
@property(copy, nonatomic) CDUnknownBlockType dismissWhenTapWindowHandler; // @synthesize dismissWhenTapWindowHandler=_dismissWhenTapWindowHandler;
- (void)dismissWithClickedButtonIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)dismissWithClickedButtonIndex:(long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
@property(nonatomic) _Bool dragable; // @synthesize dragable=_dragable;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
@property(nonatomic) double height; // @synthesize height=_height;
- (id)init;
- (id)initWithCustomView:(id)arg1;
- (id)initWithTitle:(id)arg1;
- (id)initWithViewController:(id)arg1;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
- (long long)preferredStatusBarStyle;
- (_Bool)prefersStatusBarHidden;
- (void)setCancelButtonWithTitle:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)setCancelButtonWithTitle:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)setDestructiveButtonWithTitle:(id)arg1 atIndex:(unsigned long long)arg2 block:(CDUnknownBlockType)arg3;
- (void)setDestructiveButtonWithTitle:(id)arg1 atIndex:(long long)arg2 handler:(CDUnknownBlockType)arg3;
- (void)setDestructiveButtonWithTitle:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)setDestructiveButtonWithTitle:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)setDismissWhenTapWindow:(_Bool)arg1 handler:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
- (void)setTitleColor:(id)arg1 forButton:(long long)arg2;
@property(retain, nonatomic) NSMutableDictionary *titleColorDic; // @synthesize titleColorDic=_titleColorDic;
@property(nonatomic) _Bool vignetteBackground; // @synthesize vignetteBackground=_vignetteBackground;
@property(retain, nonatomic) UIView *warpperView; // @synthesize warpperView=_warpperView;
- (_Bool)shouldAutorotate;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)showInViewController:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (unsigned long long)supportedInterfaceOrientations;
- (void)tapWindow:(id)arg1;
- (id)titleColorForButton:(long long)arg1;
- (void)updateFrameForDisplay;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:(struct CGSize)arg1 withTransitionCoordinator:(id)arg2;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

