//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TKAlertManager : NSObject
{
}

+ (void)addToStack:(id)arg1 dontDimBackground:(_Bool)arg2;
+ (id)alertSheetStack;
+ (_Bool)cancelAllAlertsAnimated:(_Bool)arg1;
+ (_Bool)cancelTopMostAlertAnimated:(_Bool)arg1;
+ (_Bool)cancelTopMostAlertAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
+ (_Bool)hideTopMostAlertAnimated:(_Bool)arg1;
+ (void)initialize;
+ (void)removeFromStack:(id)arg1;
+ (_Bool)stackContainsAlert:(id)arg1;
+ (id)topMostAlert;
+ (id)visibleAlert;

@end

