//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIColor.h>

@interface UIColor (Dark)
+ (id)WNYD_BookBaseColor;
+ (id)WNYD_DarkBaseColor;
+ (id)WNYD_appBaseBackGroundColor;
+ (id)WNYD_appCellColor;
+ (id)WNYD_appContainerBackGroundColor;
+ (id)WNYD_appTabbarColor;
+ (id)WNYD_appThemeColor;
+ (id)WNYD_blackColor;
+ (id)WNYD_color110;
+ (id)WNYD_color120;
+ (id)WNYD_color128;
+ (id)WNYD_color132;
+ (id)WNYD_color153;
+ (id)WNYD_color16;
+ (id)WNYD_color170;
+ (id)WNYD_color187;
+ (id)WNYD_color214;
+ (id)WNYD_color220;
+ (id)WNYD_color230;
+ (id)WNYD_color240;
+ (id)WNYD_color241;
+ (id)WNYD_color244;
+ (id)WNYD_color247;
+ (id)WNYD_color249;
+ (id)WNYD_color251;
+ (id)WNYD_color33;
+ (id)WNYD_color66;
+ (id)WNYD_color77;
+ (id)WNYD_color85;
+ (id)WNYD_color86;
+ (id)WNYD_colorBookStore;
+ (id)WNYD_colorCodeBG;
+ (id)WNYD_colorSearchBg;
+ (id)WNYD_colorSearchTextColor;
+ (id)WNYD_colorYellow;
+ (id)WNYD_horseBgColor;
+ (id)WNYD_horseBgNormalColor;
+ (id)WNYD_horseTextColor;
+ (id)WNYD_horseTextNormalColor;
+ (id)WNYD_membershipRedColor;
+ (id)WNYD_ownAdColor;
+ (id)WNYD_ownWanyiwanColor;
+ (id)WNYD_partingLineColor;
+ (id)WNYD_trueWhiteColor;
+ (id)WNYD_whiteColor;
@end

