//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (MultiFormat)
+ (id)sdBu_imageWithData:(id)arg1;
+ (id)sdBu_imageWithData:(id)arg1 scale:(double)arg2;
+ (id)sdBu_imageWithData:(id)arg1 scale:(double)arg2 firstFrameOnly:(_Bool)arg3;
- (id)sdBu_imageData;
- (id)sdBu_imageDataAsFormat:(long long)arg1;
- (id)sdBu_imageDataAsFormat:(long long)arg1 compressionQuality:(double)arg2;
- (id)sdBu_imageDataAsFormat:(long long)arg1 compressionQuality:(double)arg2 firstFrameOnly:(_Bool)arg3;
@end

