//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@interface UIImageView (WNYD_Extension)
+ (id)ClipToImageFromUIView:(id)arg1 CGRect:(struct CGRect)arg2;
- (void)setCircleHeader:(id)arg1;
- (void)setHeader:(id)arg1;
- (void)setRectHeader:(id)arg1;
@end

