//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class WNYD_ReaderSettings;

@interface UIView (YBFrame)
@property(nonatomic) double h;
@property(nonatomic) double maxX;
@property(nonatomic) double maxY;
@property(nonatomic) double midX;
@property(nonatomic) double midY;
@property(nonatomic) double w;
@property(nonatomic) double x;
@property(nonatomic) double y;

// Remaining properties
@property(retain, nonatomic) WNYD_ReaderSettings *settings;
@end

