//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (WXSTransitionProperty)
@property(nonatomic) _Bool wxs_addTransitionFlag;
@property(nonatomic) _Bool wxs_backGestureEnable;
@property(copy, nonatomic) CDUnknownBlockType wxs_callBackTransition;
@property(nonatomic) _Bool wxs_delegateFlag;
@property(nonatomic) __weak id wxs_tempNavDelegate;
@property(nonatomic) __weak id wxs_transitioningDelegate;
@end

