//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UMComEvent.h"

@class NSMutableDictionary, NSString;

@interface UMAAttribute : UMComEvent
{
    NSString *_id;
    NSMutableDictionary *_values;
    NSMutableDictionary *dplusDic;
    NSMutableDictionary *dplusPreDic;
}

+ (_Bool)checkValidArrayValue:(id)arg1;
+ (_Bool)checkValidKey:(id)arg1 type:(id)arg2;
+ (_Bool)checkValidNumberValue:(id)arg1;
+ (_Bool)checkValidStringValue:(id)arg1;
+ (id)filterValidArray:(id)arg1 containInOrgArray:(id)arg2;
+ (id)filterValidArrayValueWithFirstLaunchEvent:(id)arg1;
+ (id)filterValidArrayValueWithValueArray:(id)arg1;
+ (void)megerImpintAndLocalForFirstLaunch;
+ (id)propertyFilter:(id)arg1 type:(id)arg2;
+ (id)sharedInstance;
+ (id)truncateFirstLaunchEventStringKey:(id)arg1;
+ (id)truncateStringKey:(id)arg1;
+ (id)truncateValueStringKey:(id)arg1;
- (void).cxx_destruct;
- (void)clearPreProperties;
@property(retain) NSMutableDictionary *dplusDic; // @synthesize dplusDic;
@property(retain) NSMutableDictionary *dplusPreDic; // @synthesize dplusPreDic;
- (void)dplusWriteToFile:(id)arg1;
- (id)getPreProperties;
@property(copy, nonatomic) NSString *id; // @synthesize id=_id;
- (id)init;
- (void)registerPreProperties:(id)arg1;
- (void)setFirstLaunchEvent:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *values; // @synthesize values=_values;
- (void)unregisterPreProperty:(id)arg1;

@end

