//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UMComEvent.h"

@class NSString;

@interface UMANError : UMComEvent
{
    NSString *_context;
}

+ (void)clearDataInTable:(id)arg1;
+ (void)clearDataInTableWithVersion:(id)arg1;
+ (void)clearDataInTableWithVersion:(id)arg1 withSid:(id)arg2;
+ (void)insertTable:(id)arg1 context:(id)arg2;
+ (id)loadTable:(id)arg1;
+ (id)loadTableWithVersion:(id)arg1;
+ (id)loadTableWithVersion:(id)arg1 withSid:(id)arg2;
+ (int)rowCountInTable;
@property(copy, nonatomic) NSString *context; // @synthesize context=_context;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)outputUMLog;

@end

