//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UMComBaseEvent.h"

@class NSMutableDictionary, NSString;

@interface UMComEvent : UMComBaseEvent
{
    int _hws;
    int _sws;
    NSString *_session_id;
    NSString *_pn;
    NSString *_type;
    NSMutableDictionary *_values;
    NSString *_label;
}

+ (void)addEvent:(id)arg1;
+ (void)clearDataInTable:(id)arg1;
+ (void)clearDataInTableWithVersion:(id)arg1;
+ (void)clearDataInTableWithVersion:(id)arg1 withSid:(id)arg2;
+ (void)insertTable:(id)arg1 eventId:(id)arg2 event:(id)arg3 type:(id)arg4;
+ (id)loadTable:(id)arg1;
+ (id)loadTableWithVersion:(id)arg1;
+ (id)loadTableWithVersion:(id)arg1 withSid:(id)arg2;
+ (int)rowCountInTable;
- (void).cxx_destruct;
@property(nonatomic) int hws; // @synthesize hws=_hws;
- (id)init;
@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
- (void)outputUMLog;
@property(copy, nonatomic) NSString *pn; // @synthesize pn=_pn;
@property(copy, nonatomic) NSString *session_id; // @synthesize session_id=_session_id;
@property(nonatomic) int sws; // @synthesize sws=_sws;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSMutableDictionary *values; // @synthesize values=_values;
- (id)umComEventDic;

@end

