//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, UITapGestureRecognizer;

@interface UMInternalUtil : NSObject
{
    NSMutableArray *_muttaparray;
    UITapGestureRecognizer *_testTapRecognizer;
}

+ (id)Value1;
+ (id)Value2;
+ (id)Value3;
+ (id)Value4;
+ (id)Value6;
+ (id)Value7;
+ (id)Value8;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)formatIPV4Address:(struct in_addr)arg1;
+ (id)formatIPV6Address:(struct in6_addr)arg1;
+ (unsigned long long)getFreeDiskSize;
+ (unsigned long long)getFreeMemeorySize;
+ (int)getSysFontSize;
+ (unsigned long long)getTotalDiskSize;
+ (unsigned long long)getTotalMemeorySize;
+ (id)getWifiBSSID;
+ (id)getWifiInfo;
+ (id)getWifiSSID;
+ (id)getwinfo;
+ (id)getwinfoValue;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)appActivate;
- (void)connectGestureRecognized;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)createMotionManager;
- (struct UMCMRotationRate)getrotationRateWithObj:(id)arg1;
- (void)handlenetworknotification;
- (_Bool)isGAvailable:(id)arg1;
@property(retain, nonatomic) NSMutableArray *muttaparray; // @synthesize muttaparray=_muttaparray;
- (void)networkchange;
- (void)setObj:(id)arg1 updateInterval:(double)arg2;
@property(retain, nonatomic) UITapGestureRecognizer *testTapRecognizer; // @synthesize testTapRecognizer=_testTapRecognizer;
- (void)stopGyroUpdates:(id)arg1;

@end

