//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;

@interface userAuthenticationIcon : UIView
{
    _Bool _hasAuthentication;
    double _authenticatIconSize;
    UIImageView *_userIcon;
    UIImageView *_authenticatIcon;
}

- (void).cxx_destruct;
- (void)WNYD_setupLFUI;
@property(nonatomic) __weak UIImageView *authenticatIcon; // @synthesize authenticatIcon=_authenticatIcon;
@property(nonatomic) double authenticatIconSize; // @synthesize authenticatIconSize=_authenticatIconSize;
@property(nonatomic) _Bool hasAuthentication; // @synthesize hasAuthentication=_hasAuthentication;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)scaleImage:(id)arg1 toScale:(float)arg2;
@property(nonatomic) __weak UIImageView *userIcon; // @synthesize userIcon=_userIcon;
- (void)updateIconWithImageUrl:(id)arg1;

@end

