//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIWindow.h>

@class CAShapeLayer, UIButton, UILabel, UIView;

@interface WKAlertView : UIWindow
{
    UIView *_logoView;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    UIButton *_OkButton;
    UIButton *_canleButton;
    CAShapeLayer *_pathLayer;
    CDUnknownBlockType _clickBlock;
}

+ (id)shared;
+ (id)showAlertViewWithStyle:(long long)arg1 title:(id)arg2 detail:(id)arg3 canleButtonTitle:(id)arg4 okButtonTitle:(id)arg5 callBlock:(CDUnknownBlockType)arg6;
+ (id)showAlertViewWithTitle:(id)arg1 detail:(id)arg2 canleButtonTitle:(id)arg3 okButtonTitle:(id)arg4 callBlock:(CDUnknownBlockType)arg5;
- (void).cxx_destruct;
- (void)addButtonTitleWithCancle:(id)arg1 OK:(id)arg2;
- (void)addTitle:(id)arg1 detail:(id)arg2;
- (void)buttonClick:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType clickBlock; // @synthesize clickBlock=_clickBlock;
- (void)controlsInit;
- (void)drawRight;
- (void)drawWaring;
- (void)drawWrong;
- (id)init;
- (void)logoInit;
- (void)setInterFace;

@end

