//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WNYD_BaseViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, NSTimer, UIButton, UITableView, WNYD_BookListsDataModel, WNYD_BookStoreBookListsData, WNYD_NetworkManager, WNYD_Themes;

@interface WNYD_ThemeBookListController : WNYD_BaseViewController <UITableViewDelegate, UITableViewDataSource>
{
    WNYD_BookStoreBookListsData *_listData;
    WNYD_Themes *_theme;
    long long _index;
    WNYD_BookListsDataModel *_dataModel;
    CDUnknownBlockType _collectBlock;
    UIButton *_rightButton;
    WNYD_NetworkManager *_netManager;
    NSMutableArray *_themes;
    WNYD_Themes *_themeList;
    UITableView *_tableView;
    NSMutableArray *_adsArr;
    NSTimer *_wanTimer;
    long long _wanIndex;
}

- (void).cxx_destruct;
- (void)WNYD_addWanTimer;
- (void)WNYD_changeThemeFavStatus:(id)arg1;
- (void)WNYD_checkIsFav;
- (void)WNYD_loadNewLFData;
- (void)WNYD_reloadWanRow;
- (void)WNYD_setUpLFNav;
- (void)WNYD_setupLFUI;
- (void)WNYD_showWanYiWan;
@property(retain, nonatomic) NSMutableArray *adsArr; // @synthesize adsArr=_adsArr;
- (void)cancel;
@property(copy, nonatomic) CDUnknownBlockType collectBlock; // @synthesize collectBlock=_collectBlock;
@property(retain, nonatomic) WNYD_BookListsDataModel *dataModel; // @synthesize dataModel=_dataModel;
- (void)dealloc;
- (float)heightForString:(id)arg1 fontSize:(float)arg2 andWidth:(float)arg3;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(retain, nonatomic) WNYD_BookStoreBookListsData *listData; // @synthesize listData=_listData;
@property(retain, nonatomic) WNYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) WNYD_Themes *theme; // @synthesize theme=_theme;
@property(retain, nonatomic) WNYD_Themes *themeList; // @synthesize themeList=_themeList;
@property(retain, nonatomic) NSMutableArray *themes; // @synthesize themes=_themes;
@property(nonatomic) long long wanIndex; // @synthesize wanIndex=_wanIndex;
@property(retain, nonatomic) NSTimer *wanTimer; // @synthesize wanTimer=_wanTimer;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

