//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface WNYD_ChannelManager : NSObject
{
    NSMutableArray *_myTagArr;
    NSMutableArray *_recommandArr;
    NSMutableArray *_titlesArray;
}

+ (id)shareInstance;
- (void).cxx_destruct;
- (void)checkIsRepeat;
- (long long)fetchIndexOfTitleArr:(id)arg1;
- (id)getCurrentTitle:(long long)arg1;
- (id)getMyArr;
- (id)getRecommandArr;
- (id)getTitleArray;
- (id)init;
- (void)initData;
@property(retain, nonatomic) NSMutableArray *myTagArr; // @synthesize myTagArr=_myTagArr;
- (id)readLocalFileWithName:(id)arg1;
- (id)readNewFileWithName:(id)arg1;
@property(retain, nonatomic) NSMutableArray *recommandArr; // @synthesize recommandArr=_recommandArr;
- (void)save;
@property(retain, nonatomic) NSMutableArray *titlesArray; // @synthesize titlesArray=_titlesArray;
- (void)updateMyTagArr:(id)arg1 recommandArr:(id)arg2;

@end

