//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WNYD_BaseTableViewController.h"

@class NSMutableArray, NSString, NSURLSessionTask, WNYD_NetworkManager;

@interface WNYD_ThemeFavViewController : WNYD_BaseTableViewController
{
    _Bool _isLoading;
    WNYD_NetworkManager *_netManager;
    NSMutableArray *_listArr;
    NSURLSessionTask *_themeTask;
    NSString *_page;
    long long _page_id;
    NSMutableArray *_visitorRefeshArr;
    NSMutableArray *_themesArr;
}

- (void).cxx_destruct;
- (void)WNYD_setUpLFRefresh;
- (void)WNYD_setupLFUI;
- (void)cancelAllTasks;
- (void)dealloc;
- (void)getBookListWithIDArr:(id)arg1;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) NSMutableArray *listArr; // @synthesize listArr=_listArr;
- (void)loadMoreLFData;
- (void)loadNewLFData;
@property(retain, nonatomic) WNYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(retain, nonatomic) NSString *page; // @synthesize page=_page;
@property(nonatomic) long long page_id; // @synthesize page_id=_page_id;
@property(retain, nonatomic) NSURLSessionTask *themeTask; // @synthesize themeTask=_themeTask;
@property(retain, nonatomic) NSMutableArray *themesArr; // @synthesize themesArr=_themesArr;
@property(retain, nonatomic) NSMutableArray *visitorRefeshArr; // @synthesize visitorRefeshArr=_visitorRefeshArr;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

@end

