//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSAttributedString;

@interface WNYD_ReaderView : UIView
{
    NSAttributedString *_content;
    struct __CTFrame *_contentFrame;
    NSAttributedString *_sourceAttributedString;
}

+ (id)createTextFieldWithFrame:(struct CGRect)arg1 andPlaceholder:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSAttributedString *content; // @synthesize content=_content;
@property(nonatomic) struct __CTFrame *contentFrame; // @synthesize contentFrame=_contentFrame;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)fuwenbenLabel:(id)arg1 FontNumber:(id)arg2 AndRange:(struct _NSRange)arg3 AndColor:(id)arg4;
@property(retain, nonatomic) NSAttributedString *sourceAttributedString; // @synthesize sourceAttributedString=_sourceAttributedString;
- (void)updateSpeakString:(id)arg1;

@end

