//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class MYApprentice, UIButton, UILabel;

@interface WNYD_MineInviteCell : UITableViewCell
{
    MYApprentice *_model;
    UIButton *_InviteBtn;
    UILabel *_titleLabel;
    UILabel *_explainLabel;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIButton *InviteBtn; // @synthesize InviteBtn=_InviteBtn;
- (void)awakeFromNib;
@property(nonatomic) __weak UILabel *explainLabel; // @synthesize explainLabel=_explainLabel;
@property(retain, nonatomic) MYApprentice *model; // @synthesize model=_model;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

@end

