//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSLayoutConstraint, UIImageView, UILabel, UIView, WNYD_BookCategories;

@interface WNYD_ClassifyCollectiomnCell : UICollectionViewCell
{
    WNYD_BookCategories *_indexModel;
    UIImageView *_imageView1;
    UIImageView *_imageView2;
    UIImageView *_imageView3;
    UILabel *_ClassifyTitle;
    UILabel *_CateTitle;
    NSLayoutConstraint *_ClassifyTitleLeft;
    NSLayoutConstraint *_baseImageVW;
    NSLayoutConstraint *_baseImageVH;
    UIView *_lineView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UILabel *CateTitle; // @synthesize CateTitle=_CateTitle;
@property(nonatomic) __weak UILabel *ClassifyTitle; // @synthesize ClassifyTitle=_ClassifyTitle;
@property(nonatomic) __weak NSLayoutConstraint *ClassifyTitleLeft; // @synthesize ClassifyTitleLeft=_ClassifyTitleLeft;
- (void)awakeFromNib;
@property(nonatomic) __weak NSLayoutConstraint *baseImageVH; // @synthesize baseImageVH=_baseImageVH;
@property(nonatomic) __weak NSLayoutConstraint *baseImageVW; // @synthesize baseImageVW=_baseImageVW;
@property(nonatomic) __weak UIImageView *imageView1; // @synthesize imageView1=_imageView1;
@property(nonatomic) __weak UIImageView *imageView2; // @synthesize imageView2=_imageView2;
@property(nonatomic) __weak UIImageView *imageView3; // @synthesize imageView3=_imageView3;
@property(retain, nonatomic) WNYD_BookCategories *indexModel; // @synthesize indexModel=_indexModel;
@property(nonatomic) __weak UIView *lineView; // @synthesize lineView=_lineView;

@end

