//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CADisplayLink;

@interface WNYD_ProgressView : UIView
{
    long long _loadStatus;
    double _progress;
    CADisplayLink *_displayLink;
    double _startAngle;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
- (void)drawProgressArc;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawWaitingArc;
@property(nonatomic) long long loadStatus; // @synthesize loadStatus=_loadStatus;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(nonatomic) double startAngle; // @synthesize startAngle=_startAngle;
- (void)updateProgressView;

@end

