//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, WNYD_SQLiteManager;

@interface WNYD_UserSynManager : NSObject
{
    WNYD_SQLiteManager *_sqliteM;
    NSArray *_booksArr;
}

- (void).cxx_destruct;
- (void)UserFavSyn;
- (void)WNYD_bookShelfSynLFAdd:(id)arg1;
- (void)bookShelfSynLFDel:(id)arg1;
@property(retain, nonatomic) NSArray *booksArr; // @synthesize booksArr=_booksArr;
- (void)resetUser;
- (void)resetUserSyn;
@property(retain, nonatomic) WNYD_SQLiteManager *sqliteM; // @synthesize sqliteM=_sqliteM;

@end

