//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBarController.h>

#import "BUNativeExpresInterstitialAdDelegate-Protocol.h"
#import "GDTUnifiedInterstitialAdDelegate-Protocol.h"

@class BUNativeExpressInterstitialAd, GDTUnifiedInterstitialAd, NSMutableArray, NSString, NSTimer, UIImageView, WNYD_AdvertConfigModel, WNYD_NetworkManager;

@interface WNYD_TabBarController : UITabBarController <BUNativeExpresInterstitialAdDelegate, GDTUnifiedInterstitialAdDelegate>
{
    long long _messageCount;
    WNYD_NetworkManager *_netManager;
    WNYD_NetworkManager *_LoginShareManager;
    long long _loadCount;
    NSMutableArray *_childVCS;
    NSTimer *_StayReadTimer;
    BUNativeExpressInterstitialAd *_interstitialAd;
    GDTUnifiedInterstitialAd *_interstitial;
    long long _platForm;
    WNYD_AdvertConfigModel *_insertModel;
    UIImageView *_bgV;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WNYD_NetworkManager *LoginShareManager; // @synthesize LoginShareManager=_LoginShareManager;
@property(retain, nonatomic) NSTimer *StayReadTimer; // @synthesize StayReadTimer=_StayReadTimer;
- (void)WNYD_BecomeActive;
- (void)WNYD_checkAppPushPermission;
- (id)addChildVc:(id)arg1 title:(id)arg2 image:(id)arg3 selectImage:(id)arg4;
- (void)animationWithIndex:(long long)arg1;
- (void)appDidEnterBackgroundNotification:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
@property(retain, nonatomic) UIImageView *bgV; // @synthesize bgV=_bgV;
- (void)canShowAD;
- (void)canShowAd:(id)arg1;
@property(retain, nonatomic) NSMutableArray *childVCS; // @synthesize childVCS=_childVCS;
- (void)clearTabBarBadge;
- (void)dealloc;
- (void)forceTouch;
- (void)handleDeviceRotation:(id)arg1;
- (void)initIntersTitialAD;
@property(retain, nonatomic) WNYD_AdvertConfigModel *insertModel; // @synthesize insertModel=_insertModel;
@property(retain, nonatomic) GDTUnifiedInterstitialAd *interstitial; // @synthesize interstitial=_interstitial;
@property(retain, nonatomic) BUNativeExpressInterstitialAd *interstitialAd; // @synthesize interstitialAd=_interstitialAd;
@property(nonatomic) long long loadCount; // @synthesize loadCount=_loadCount;
@property(nonatomic) long long messageCount; // @synthesize messageCount=_messageCount;
- (void)nativeExpresInterstitialAd:(id)arg1 didFailWithError:(id)arg2;
- (void)nativeExpresInterstitialAdDidClick:(id)arg1;
- (void)nativeExpresInterstitialAdDidClose:(id)arg1;
- (void)nativeExpresInterstitialAdRenderFail:(id)arg1 error:(id)arg2;
- (void)nativeExpresInterstitialAdRenderSuccess:(id)arg1;
- (void)nativeExpresInterstitialAdWillClose:(id)arg1;
- (void)nativeExpresInterstitialAdWillVisible:(id)arg1;
@property(retain, nonatomic) WNYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
- (void)onBarItemClicked:(id)arg1;
@property(nonatomic) long long platForm; // @synthesize platForm=_platForm;
- (void)playSound;
- (void)setTabBarChildVC;
- (void)setUpChildVc:(id)arg1 title:(id)arg2 image:(id)arg3 selectImage:(id)arg4;
- (void)setUpTabBar;
- (void)setUptabBarItem;
- (void)setupTabbarBadge;
- (void)tabBar:(id)arg1 didSelectItem:(id)arg2;
- (void)traitCollectionDidChange:(id)arg1;
- (void)unifiedInterstitialDidDismissScreen:(id)arg1;
- (void)unifiedInterstitialDidPresentScreen:(id)arg1;
- (void)unifiedInterstitialFailToLoadAd:(id)arg1 error:(id)arg2;
- (void)unifiedInterstitialSuccessToLoadAd:(id)arg1;
- (void)unifiedInterstitialWillPresentScreen:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

