//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WNYD_BaseViewController.h"

#import "UIScrollViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "WNYD_AdvertContentViewDelegate-Protocol.h"

@class CommentSendViewContainer, NSMutableArray, NSString, UITableView, WNYD_AdvertContentView;

@interface WNYD_NewComTableViewController : WNYD_BaseViewController <UITableViewDelegate, UITableViewDataSource, UIScrollViewDelegate, WNYD_AdvertContentViewDelegate>
{
    _Bool _canScroll;
    _Bool _isShowTop;
    NSString *_type;
    NSString *_book_id;
    NSString *_bookName;
    CDUnknownBlockType _scrollBlock;
    CommentSendViewContainer *_sendViewContainer;
    CommentSendViewContainer *_sendViewContainer1;
    CommentSendViewContainer *_sendViewContainer2;
    WNYD_AdvertContentView *_topADContentView;
    WNYD_AdvertContentView *_middleADContentView;
    UITableView *_tableView;
    NSMutableArray *_dataArr;
    long long _Page;
    long long _lastPage;
    long long _item_key;
}

- (void).cxx_destruct;
@property(nonatomic) long long Page; // @synthesize Page=_Page;
- (void)WNYD_getCommentListData;
- (void)WNYD_initInfoADView;
- (void)WNYD_loadMoreLFData;
@property(copy, nonatomic) NSString *bookName; // @synthesize bookName=_bookName;
@property(copy, nonatomic) NSString *book_id; // @synthesize book_id=_book_id;
@property(nonatomic) _Bool canScroll; // @synthesize canScroll=_canScroll;
@property(retain, nonatomic) NSMutableArray *dataArr; // @synthesize dataArr=_dataArr;
@property(nonatomic) _Bool isShowTop; // @synthesize isShowTop=_isShowTop;
@property(nonatomic) long long item_key; // @synthesize item_key=_item_key;
@property(nonatomic) long long lastPage; // @synthesize lastPage=_lastPage;
@property(retain, nonatomic) WNYD_AdvertContentView *middleADContentView; // @synthesize middleADContentView=_middleADContentView;
- (void)reloadData;
@property(copy, nonatomic) CDUnknownBlockType scrollBlock; // @synthesize scrollBlock=_scrollBlock;
- (void)scrollViewDidScroll:(id)arg1;
@property(nonatomic) __weak CommentSendViewContainer *sendViewContainer; // @synthesize sendViewContainer=_sendViewContainer;
@property(nonatomic) __weak CommentSendViewContainer *sendViewContainer1; // @synthesize sendViewContainer1=_sendViewContainer1;
@property(nonatomic) __weak CommentSendViewContainer *sendViewContainer2; // @synthesize sendViewContainer2=_sendViewContainer2;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void)setTableViewCanScroll:(_Bool)arg1;
- (void)setTableViewH:(double)arg1;
@property(retain, nonatomic) WNYD_AdvertContentView *topADContentView; // @synthesize topADContentView=_topADContentView;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void)showADContentWith:(id)arg1 andADHeight:(float)arg2 andIsLoadSuccess:(_Bool)arg3 andSelfView:(id)arg4 andADView:(id)arg5;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

