//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AFHTTPSessionManager, NSString;

@interface WNYD_NetworkManager : NSObject
{
    long long _networkStatus;
    AFHTTPSessionManager *_manager;
    NSString *_userID;
    NSString *_token;
}

+ (id)LoginShareManager;
+ (_Bool)checkIsLogin;
+ (_Bool)checkIsMainthread;
+ (id)shareManager;
- (void).cxx_destruct;
- (id)arrayToJsonString:(id)arg1;
- (id)customSecurityPolicy;
- (id)dictionaryWithJsonString:(id)arg1;
- (id)formatWithResponseObject:(id)arg1 error:(id)arg2;
- (id)getHttpHeader;
- (id)getWithAPIWNYD_Type:(long long)arg1 parameter:(id)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (id)initLoginManager;
- (id)initManager;
@property(retain, nonatomic) AFHTTPSessionManager *manager; // @synthesize manager=_manager;
- (void)monitorNetWork;
@property(nonatomic) long long networkStatus; // @synthesize networkStatus=_networkStatus;
- (id)parsingResponseObject:(id)arg1 type:(long long)arg2;
@property(readonly, nonatomic) NSString *token; // @synthesize token=_token;
@property(readonly, nonatomic) NSString *userID; // @synthesize userID=_userID;

@end

