//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WNYD_AdvertModel : NSObject
{
    NSString *_desc;
    NSString *_down_type;
    NSString *_down_url;
    NSString *_image;
    NSString *_image_x;
    NSString *_name;
    NSString *_type;
    NSString *_down_package;
    long long _ad_id;
    NSString *_author;
    long long _is_video;
    long long _openType;
}

+ (id)modelCustomPropertyMapper;
- (void).cxx_destruct;
@property(nonatomic) long long ad_id; // @synthesize ad_id=_ad_id;
@property(copy, nonatomic) NSString *author; // @synthesize author=_author;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *down_package; // @synthesize down_package=_down_package;
@property(copy, nonatomic) NSString *down_type; // @synthesize down_type=_down_type;
@property(copy, nonatomic) NSString *down_url; // @synthesize down_url=_down_url;
@property(copy, nonatomic) NSString *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *image_x; // @synthesize image_x=_image_x;
@property(nonatomic) long long is_video; // @synthesize is_video=_is_video;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) long long openType; // @synthesize openType=_openType;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;

@end

