//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WNYD_BaseViewController.h"

#import "WNYD_ErrorStatusViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UIView, WNYD_ClassifyLeftTableView, WNYD_ClassifyRightTableView, WNYD_ErrorStatusView;

@interface WNYD_BookRankController : WNYD_BaseViewController <WNYD_ErrorStatusViewDelegate>
{
    NSString *_sexName;
    UIView *_baseView;
    WNYD_ClassifyLeftTableView *_leftTableView;
    WNYD_ClassifyRightTableView *_rightTableView;
    NSMutableArray *_leftArr;
    NSMutableArray *_rightArr;
    NSMutableArray *_femaleArr;
    NSMutableArray *_maleArr;
    WNYD_ErrorStatusView *_errorView;
}

- (void).cxx_destruct;
- (void)WNYD_buildUI;
- (void)WNYD_getData;
- (void)WNYD_getLeftData;
- (void)WNYD_resetBaseViewH:(double)arg1;
@property(nonatomic) __weak UIView *baseView; // @synthesize baseView=_baseView;
@property(retain, nonatomic) WNYD_ErrorStatusView *errorView; // @synthesize errorView=_errorView;
@property(retain, nonatomic) NSMutableArray *femaleArr; // @synthesize femaleArr=_femaleArr;
@property(retain, nonatomic) NSMutableArray *leftArr; // @synthesize leftArr=_leftArr;
@property(retain, nonatomic) WNYD_ClassifyLeftTableView *leftTableView; // @synthesize leftTableView=_leftTableView;
@property(retain, nonatomic) NSMutableArray *maleArr; // @synthesize maleArr=_maleArr;
- (void)refreshDataWithType:(id)arg1;
@property(retain, nonatomic) NSMutableArray *rightArr; // @synthesize rightArr=_rightArr;
@property(retain, nonatomic) WNYD_ClassifyRightTableView *rightTableView; // @synthesize rightTableView=_rightTableView;
@property(copy, nonatomic) NSString *sexName; // @synthesize sexName=_sexName;
- (void)setTableViewFrameWithY:(double)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

