//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDateFormatter;

@interface WNYD_DateModel : NSObject
{
    NSDateFormatter *_dateFormat;
}

+ (id)shareDateModel;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDateFormatter *dateFormat; // @synthesize dateFormat=_dateFormat;
- (id)dateWithCustomDateFormat:(id)arg1;
- (id)getTimeString;
- (id)getUpdateStringWith:(id)arg1;
- (id)init;

@end

