//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface WNYD_ClassifyMale : NSObject
{
    NSArray *_ltype_list;
    NSString *_ltype_id;
    NSString *_ltype_name;
    NSString *_ltype_image;
    NSString *_ltype_desc;
}

+ (id)modelContainerPropertyGenericClass;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *ltype_desc; // @synthesize ltype_desc=_ltype_desc;
@property(copy, nonatomic) NSString *ltype_id; // @synthesize ltype_id=_ltype_id;
@property(copy, nonatomic) NSString *ltype_image; // @synthesize ltype_image=_ltype_image;
@property(copy, nonatomic) NSArray *ltype_list; // @synthesize ltype_list=_ltype_list;
@property(copy, nonatomic) NSString *ltype_name; // @synthesize ltype_name=_ltype_name;

@end

