//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UILabel, YBookDetailModel;

@interface WNYD_BookStoreSexChoiceCell : UICollectionViewCell
{
    YBookDetailModel *_bookModel;
    UILabel *_typeLabel;
    UILabel *_bookNameLabel;
    UILabel *_authorLabel;
    UILabel *_shortInfoLabel;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UILabel *authorLabel; // @synthesize authorLabel=_authorLabel;
- (void)awakeFromNib;
@property(retain, nonatomic) YBookDetailModel *bookModel; // @synthesize bookModel=_bookModel;
@property(nonatomic) __weak UILabel *bookNameLabel; // @synthesize bookNameLabel=_bookNameLabel;
@property(nonatomic) __weak UILabel *shortInfoLabel; // @synthesize shortInfoLabel=_shortInfoLabel;
@property(nonatomic) __weak UILabel *typeLabel; // @synthesize typeLabel=_typeLabel;

@end

