//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WNYD_BaseViewController.h"

#import "BUBannerAdViewDelegate-Protocol.h"
#import "GADBannerViewDelegate-Protocol.h"
#import "GDTNativeExpressAdDelegete-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class BUBannerAdView, GADBannerView, GDTNativeExpressAd, GDTNativeExpressAdView, NSArray, NSMutableArray, NSString, UIScrollView, WNYD_AdvertModel, WNYD_NetworkManager, YBookDetailModel, YYLabel;

@interface WNYD_CatalogDetailController : WNYD_BaseViewController <UIScrollViewDelegate, GADBannerViewDelegate, GDTNativeExpressAdDelegete, BUBannerAdViewDelegate>
{
    YBookDetailModel *_readingBook;
    UIScrollView *_scrollView;
    YYLabel *_infoLabel;
    WNYD_NetworkManager *_netManager;
    GADBannerView *_bannerView;
    NSMutableArray *_flowViewArray;
    NSArray *_expressAdViews;
    GDTNativeExpressAd *_nativeExpressAd;
    GDTNativeExpressAdView *_nativeExpressAdView;
    WNYD_AdvertModel *_topInfoADModel;
    BUBannerAdView *_BUAdBannerView;
    double _BUAdBannerViewHeight;
}

- (void).cxx_destruct;
@property(retain, nonatomic) BUBannerAdView *BUAdBannerView; // @synthesize BUAdBannerView=_BUAdBannerView;
@property(nonatomic) double BUAdBannerViewHeight; // @synthesize BUAdBannerViewHeight=_BUAdBannerViewHeight;
- (void)addSeeMoreButton;
@property(retain, nonatomic) GADBannerView *bannerView; // @synthesize bannerView=_bannerView;
- (void)buildContent;
- (void)buildScrollView;
@property(retain, nonatomic) NSArray *expressAdViews; // @synthesize expressAdViews=_expressAdViews;
@property(retain, nonatomic) NSMutableArray *flowViewArray; // @synthesize flowViewArray=_flowViewArray;
- (float)heightForString:(id)arg1 fontSize:(float)arg2 andWidth:(float)arg3;
@property(retain, nonatomic) YYLabel *infoLabel; // @synthesize infoLabel=_infoLabel;
- (void)initInfoADView;
@property(retain, nonatomic) GDTNativeExpressAd *nativeExpressAd; // @synthesize nativeExpressAd=_nativeExpressAd;
@property(retain, nonatomic) GDTNativeExpressAdView *nativeExpressAdView; // @synthesize nativeExpressAdView=_nativeExpressAdView;
@property(retain, nonatomic) WNYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
@property(retain, nonatomic) YBookDetailModel *readingBook; // @synthesize readingBook=_readingBook;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) WNYD_AdvertModel *topInfoADModel; // @synthesize topInfoADModel=_topInfoADModel;
- (void)updateScrollViewContentSize;
- (void)updateScrollViewSize:(double)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

