//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "BUNativeExpressBannerViewDelegate-Protocol.h"

@class BUNativeExpressBannerView, NSString, WNYD_AdvertConfigModel, WNYD_ReaderSettings;
@protocol WNYD_BUADExpressBannerViewDelegate;

@interface WNYD_BUADExpressBannerView : UIView <BUNativeExpressBannerViewDelegate>
{
    WNYD_AdvertConfigModel *_ADModel;
    id <WNYD_BUADExpressBannerViewDelegate> _mydelegate;
    BUNativeExpressBannerView *_carouselBannerView;
    WNYD_ReaderSettings *_settings;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WNYD_AdvertConfigModel *ADModel; // @synthesize ADModel=_ADModel;
@property(retain, nonatomic) BUNativeExpressBannerView *carouselBannerView; // @synthesize carouselBannerView=_carouselBannerView;
- (void)dealloc;
- (id)getRootNavController;
- (void)initNativeBanner;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak id <WNYD_BUADExpressBannerViewDelegate> mydelegate; // @synthesize mydelegate=_mydelegate;
- (void)nativeExpressBannerAdView:(id)arg1 didLoadFailWithError:(id)arg2;
- (void)nativeExpressBannerAdView:(id)arg1 dislikeWithReason:(id)arg2;
- (void)nativeExpressBannerAdViewDidClick:(id)arg1;
- (void)nativeExpressBannerAdViewDidLoad:(id)arg1;
- (void)nativeExpressBannerAdViewRenderFail:(id)arg1 error:(id)arg2;
- (void)nativeExpressBannerAdViewRenderSuccess:(id)arg1;
- (void)nativeExpressBannerAdViewWillBecomVisible:(id)arg1;
@property(retain, nonatomic) WNYD_ReaderSettings *settings; // @synthesize settings=_settings;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

