//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString;

@interface WNYD_RankSexIndexTableView : UITableView <UITableViewDataSource, UITableViewDelegate>
{
    long long _itemIndex;
    long long _numberOfRows;
}

- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;
@property(nonatomic) long long itemIndex; // @synthesize itemIndex=_itemIndex;
@property(nonatomic) long long numberOfRows; // @synthesize numberOfRows=_numberOfRows;
- (void)refreshWithData:(id)arg1 atIndex:(long long)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

