//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WNYD_RegularModel : NSObject
{
    NSString *_regular_key;
    NSString *_regular_value;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *regular_key; // @synthesize regular_key=_regular_key;
@property(copy, nonatomic) NSString *regular_value; // @synthesize regular_value=_regular_value;

@end

