//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TTTAttributedLabelDelegate-Protocol.h"

@class NSString;

@interface WNYD_PrivacyTipsView : UIView <TTTAttributedLabelDelegate>
{
    CDUnknownBlockType _AgreeBlock;
    CDUnknownBlockType _privacyBlock;
    CDUnknownBlockType _DisAgreeBlock;
}

+ (id)sharedManager;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType AgreeBlock; // @synthesize AgreeBlock=_AgreeBlock;
@property(copy, nonatomic) CDUnknownBlockType DisAgreeBlock; // @synthesize DisAgreeBlock=_DisAgreeBlock;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)buildUI;
- (void)clickAgree:(id)arg1;
- (void)clickDisAgree:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(copy, nonatomic) CDUnknownBlockType privacyBlock; // @synthesize privacyBlock=_privacyBlock;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

