//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSLayoutConstraint, NSString, UIImageView, UILabel, UITableView;

@interface WNYD_AboutQMViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    UIImageView *_frontCoverImageView;
    NSLayoutConstraint *_topConstraint;
    UILabel *_editionLabel;
    UITableView *_tableView;
}

+ (id)colorWithHexString:(id)arg1 alpha:(double)arg2;
- (void).cxx_destruct;
- (void)back;
@property(nonatomic) __weak UILabel *editionLabel; // @synthesize editionLabel=_editionLabel;
@property(nonatomic) __weak UIImageView *frontCoverImageView; // @synthesize frontCoverImageView=_frontCoverImageView;
- (void)gotoSafariVC;
- (void)safariViewControllerDidFinish:(id)arg1;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak NSLayoutConstraint *topConstraint; // @synthesize topConstraint=_topConstraint;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

