//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WNYD_OldUserModel : NSObject
{
    NSString *_user_id;
    NSString *_user_avatar;
    NSString *_user_nick;
    NSString *_reg_time;
    NSString *_reg_day;
    long long _is_reg;
    long long _ad_style;
    NSString *_ad_end_datetime;
    long long _book_count;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *ad_end_datetime; // @synthesize ad_end_datetime=_ad_end_datetime;
@property(nonatomic) long long ad_style; // @synthesize ad_style=_ad_style;
@property(nonatomic) long long book_count; // @synthesize book_count=_book_count;
@property(nonatomic) long long is_reg; // @synthesize is_reg=_is_reg;
@property(retain, nonatomic) NSString *reg_day; // @synthesize reg_day=_reg_day;
@property(retain, nonatomic) NSString *reg_time; // @synthesize reg_time=_reg_time;
@property(retain, nonatomic) NSString *user_avatar; // @synthesize user_avatar=_user_avatar;
@property(retain, nonatomic) NSString *user_id; // @synthesize user_id=_user_id;
@property(retain, nonatomic) NSString *user_nick; // @synthesize user_nick=_user_nick;

@end

