//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;

@interface WNYD_UpdateTipsView : UIView
{
    UIButton *_btn;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (void)WNYD_getBookReset;
@property(nonatomic) __weak UIButton *btn; // @synthesize btn=_btn;
- (void)buildUI;
- (void)clickAgree:(id)arg1;
- (void)disMiss;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)updateOldHis;

@end

