//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AVSpeechSynthesizerDelegate-Protocol.h"
#import "BDSSpeechSynthesizerDelegate-Protocol.h"

@class AVSpeechSynthesisVoice, AVSpeechSynthesizer, AVSpeechUtterance, NSArray, NSString, WNYD_ReaderManager, WNYD_ReaderSettings;
@protocol WNYD_SpeechManagerDelegate;

@interface WNYD_SpeechManager : NSObject <BDSSpeechSynthesizerDelegate, AVSpeechSynthesizerDelegate>
{
    id <WNYD_SpeechManagerDelegate> _delegate;
    long long _state;
    NSString *_pauseString;
    NSArray *_speechArray;
    unsigned long long _speechCount;
    double _speechRate;
    double _speechVolume;
    AVSpeechSynthesisVoice *_voiceType;
    NSString *_sourceSpeechString;
    AVSpeechUtterance *_speechUtterance;
    WNYD_ReaderSettings *_readerSettings;
    WNYD_ReaderManager *_readerManager;
    unsigned long long _chapterIndex;
    unsigned long long _currentWordIndex;
    AVSpeechSynthesizer *_speechSynthesizer;
    NSString *_bdApp_id;
    NSString *_bdApp_key;
    NSString *_bdSecret;
    struct _NSRange _speechRange;
}

+ (id)shareSpeechManager;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *bdApp_id; // @synthesize bdApp_id=_bdApp_id;
@property(copy, nonatomic) NSString *bdApp_key; // @synthesize bdApp_key=_bdApp_key;
@property(copy, nonatomic) NSString *bdSecret; // @synthesize bdSecret=_bdSecret;
- (void)changeSpeechPitch:(double)arg1;
- (void)changeSpeechRate:(double)arg1;
- (void)changeSpeechVoice:(id)arg1;
@property(nonatomic) unsigned long long chapterIndex; // @synthesize chapterIndex=_chapterIndex;
- (void)checkSpeechStringValid;
- (void)configureOfflineTTS;
- (void)configureOnlineTTS;
- (void)configureSDK;
- (void)continueSpeech;
@property(nonatomic) unsigned long long currentWordIndex; // @synthesize currentWordIndex=_currentWordIndex;
@property(nonatomic) __weak id <WNYD_SpeechManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)exitSpeech;
- (long long)getDuplicateSubStrCountInCompleteStr:(id)arg1 withSubStr:(id)arg2;
- (id)init;
- (void)p_speechUpdateState:(long long)arg1;
- (void)p_startSpeechWith:(id)arg1;
- (void)pauseSpeech;
@property(retain, nonatomic) NSString *pauseString; // @synthesize pauseString=_pauseString;
@property(retain, nonatomic) WNYD_ReaderManager *readerManager; // @synthesize readerManager=_readerManager;
@property(retain, nonatomic) WNYD_ReaderSettings *readerSettings; // @synthesize readerSettings=_readerSettings;
@property(readonly, nonatomic) unsigned long long sectionStringCount;
- (void)setAudioSessionActive:(_Bool)arg1;
- (void)setLockScreenNowPlayingInfo;
@property(copy, nonatomic) NSString *sourceSpeechString; // @synthesize sourceSpeechString=_sourceSpeechString;
@property(retain, nonatomic) NSArray *speechArray; // @synthesize speechArray=_speechArray;
@property(nonatomic) unsigned long long speechCount; // @synthesize speechCount=_speechCount;
@property(nonatomic) struct _NSRange speechRange; // @synthesize speechRange=_speechRange;
@property(nonatomic) double speechRate; // @synthesize speechRate=_speechRate;
@property(retain, nonatomic) AVSpeechSynthesizer *speechSynthesizer; // @synthesize speechSynthesizer=_speechSynthesizer;
@property(retain, nonatomic) AVSpeechUtterance *speechUtterance; // @synthesize speechUtterance=_speechUtterance;
@property(nonatomic) double speechVolume; // @synthesize speechVolume=_speechVolume;
@property(retain, nonatomic) AVSpeechSynthesisVoice *voiceType; // @synthesize voiceType=_voiceType;
@property(readonly, copy, nonatomic) NSString *speakingString;
- (void)speechSynthesizer:(id)arg1 didCancelSpeechUtterance:(id)arg2;
- (void)speechSynthesizer:(id)arg1 didContinueSpeechUtterance:(id)arg2;
- (void)speechSynthesizer:(id)arg1 didFinishSpeechUtterance:(id)arg2;
- (void)speechSynthesizer:(id)arg1 didPauseSpeechUtterance:(id)arg2;
- (void)speechSynthesizer:(id)arg1 didStartSpeechUtterance:(id)arg2;
- (void)speechSynthesizer:(id)arg1 willSpeakRangeOfSpeechString:(struct _NSRange)arg2 utterance:(id)arg3;
- (void)startSpeechWith:(id)arg1 speechRate:(double)arg2;
@property(readonly, nonatomic) long long state; // @synthesize state=_state;
- (void)synthesizerErrorOccurred:(id)arg1 speaking:(long long)arg2 synthesizing:(long long)arg3;
- (void)synthesizerFinishWorkingSentence:(long long)arg1;
- (void)synthesizerNewDataArrived:(id)arg1 DataFormat:(int)arg2 characterCount:(int)arg3 sentenceNumber:(long long)arg4;
- (void)synthesizerSpeechEndSentence:(long long)arg1;
- (void)synthesizerSpeechStartSentence:(long long)arg1;
- (void)synthesizerStartWorkingSentence:(long long)arg1;
- (void)synthesizerTextSpeakLengthChanged:(int)arg1 sentenceNumber:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

