//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, WKWebView;

@interface WNYD_AboutWebViewController : UIViewController
{
    _Bool _isPresent;
    NSString *_navTitle;
    WKWebView *_webView;
}

+ (id)colorWithHexString:(id)arg1 alpha:(double)arg2;
- (void).cxx_destruct;
- (void)back;
- (void)buildNav;
- (void)didReceiveMemoryWarning;
- (id)getCurrentTimes;
@property(nonatomic) _Bool isPresent; // @synthesize isPresent=_isPresent;
@property(retain, nonatomic) NSString *navTitle; // @synthesize navTitle=_navTitle;
@property(nonatomic) __weak WKWebView *webView; // @synthesize webView=_webView;
- (void)viewDidLoad;

@end

