//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, YBookModel;

@interface WNYD_ThemesDetailCell : UITableViewCell
{
    YBookModel *_themes;
    UIImageView *_themesCover;
    UILabel *_themesName;
    UILabel *_themesAuthor;
    UILabel *_themesDes;
    UILabel *_themesBookCount;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) YBookModel *themes; // @synthesize themes=_themes;
@property(nonatomic) __weak UILabel *themesAuthor; // @synthesize themesAuthor=_themesAuthor;
@property(nonatomic) __weak UILabel *themesBookCount; // @synthesize themesBookCount=_themesBookCount;
@property(nonatomic) __weak UIImageView *themesCover; // @synthesize themesCover=_themesCover;
@property(nonatomic) __weak UILabel *themesDes; // @synthesize themesDes=_themesDes;
@property(nonatomic) __weak UILabel *themesName; // @synthesize themesName=_themesName;

@end

