//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface WNYD_RadoanLayerView : UIView
{
    long long _direction;
    double _radian;
}

@property(nonatomic) long long direction; // @synthesize direction=_direction;
@property(nonatomic) double radian; // @synthesize radian=_radian;

@end

