//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class DALabeledCircularProgressView, NSLayoutConstraint, NSString, UIImageView, UILabel, WNYD_BookIndexBookData;

@interface WNYD_BookStoreHotBookCell : UICollectionViewCell
{
    NSString *_hotsString;
    WNYD_BookIndexBookData *_bookModel;
    UIImageView *_bookCoverImageView;
    UILabel *_bookNameTitle;
    DALabeledCircularProgressView *_CoverProgressView;
    UILabel *_rankPosition;
    UILabel *_HeatTitle;
    UILabel *_heatNumber;
    UILabel *_CellTopTitle;
    UILabel *_titleIndex;
    NSLayoutConstraint *_titleX;
    NSLayoutConstraint *_nameX;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UILabel *CellTopTitle; // @synthesize CellTopTitle=_CellTopTitle;
@property(nonatomic) __weak DALabeledCircularProgressView *CoverProgressView; // @synthesize CoverProgressView=_CoverProgressView;
@property(nonatomic) __weak UILabel *HeatTitle; // @synthesize HeatTitle=_HeatTitle;
- (void)awakeFromNib;
@property(nonatomic) __weak UIImageView *bookCoverImageView; // @synthesize bookCoverImageView=_bookCoverImageView;
@property(retain, nonatomic) WNYD_BookIndexBookData *bookModel; // @synthesize bookModel=_bookModel;
@property(nonatomic) __weak UILabel *bookNameTitle; // @synthesize bookNameTitle=_bookNameTitle;
@property(nonatomic) __weak UILabel *heatNumber; // @synthesize heatNumber=_heatNumber;
@property(retain, nonatomic) NSString *hotsString; // @synthesize hotsString=_hotsString;
@property(nonatomic) __weak NSLayoutConstraint *nameX; // @synthesize nameX=_nameX;
@property(nonatomic) __weak UILabel *rankPosition; // @synthesize rankPosition=_rankPosition;
@property(nonatomic) __weak UILabel *titleIndex; // @synthesize titleIndex=_titleIndex;
@property(nonatomic) __weak NSLayoutConstraint *titleX; // @synthesize titleX=_titleX;

@end

