//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WNYD_ClassifyBannerData : NSObject
{
    NSString *_book_id;
    NSString *_url_path;
    NSString *_book_list_path;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *book_id; // @synthesize book_id=_book_id;
@property(copy, nonatomic) NSString *book_list_path; // @synthesize book_list_path=_book_list_path;
@property(copy, nonatomic) NSString *url_path; // @synthesize url_path=_url_path;

@end

