//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GADUnifiedNativeAdDelegate-Protocol.h"
#import "GADUnifiedNativeAdLoaderDelegate-Protocol.h"

@class GADAdLoader, GADUnifiedNativeAd, GADUnifiedNativeAdView, NSString, UILabel, WNYD_AdvertConfigModel, WNYD_ReaderSettings;
@protocol WNYD_GoogleAdvancedBannerViewDelegate;

@interface WNYD_GoogleAdvancedBannerView : UIView <GADUnifiedNativeAdLoaderDelegate, GADUnifiedNativeAdDelegate>
{
    GADUnifiedNativeAd *_nativBannerAd;
    WNYD_AdvertConfigModel *_ADModel;
    id <WNYD_GoogleAdvancedBannerViewDelegate> _mydelegate;
    UILabel *_titleLabel;
    GADAdLoader *_adLoader;
    WNYD_ReaderSettings *_settings;
    GADUnifiedNativeAdView *_nativeAdView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) WNYD_AdvertConfigModel *ADModel; // @synthesize ADModel=_ADModel;
@property(retain, nonatomic) GADAdLoader *adLoader; // @synthesize adLoader=_adLoader;
- (void)adLoader:(id)arg1 didFailToReceiveAdWithError:(id)arg2;
- (void)adLoader:(id)arg1 didReceiveUnifiedNativeAd:(id)arg2;
- (void)buildBannerViewWithBannerAd:(id)arg1;
- (void)dealloc;
- (id)getRootNavController;
- (void)initNativeBanner;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak id <WNYD_GoogleAdvancedBannerViewDelegate> mydelegate; // @synthesize mydelegate=_mydelegate;
@property(retain, nonatomic) GADUnifiedNativeAd *nativBannerAd; // @synthesize nativBannerAd=_nativBannerAd;
- (void)nativeAdDidDismissScreen:(id)arg1;
- (void)nativeAdDidRecordClick:(id)arg1;
- (void)nativeAdDidRecordImpression:(id)arg1;
@property(retain, nonatomic) GADUnifiedNativeAdView *nativeAdView; // @synthesize nativeAdView=_nativeAdView;
- (void)nativeAdWillDismissScreen:(id)arg1;
- (void)nativeAdWillLeaveApplication:(id)arg1;
- (void)nativeAdWillPresentScreen:(id)arg1;
- (void)refreshBackGroundColor;
@property(retain, nonatomic) WNYD_ReaderSettings *settings; // @synthesize settings=_settings;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

