//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "TTTAttributedLabelDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class DMCustomBtn, NSMutableArray, NSString, UIButton, UIPageControl, UIScrollView, UIView;

@interface WNYD_GuideFucViewController : UIViewController <UIScrollViewDelegate, TTTAttributedLabelDelegate>
{
    UIPageControl *_pageControl;
    long long currentPage;
    long long countOfPages;
    UIButton *selectBtn;
    UIScrollView *_scrollView;
    UIViewController *_chooseSexVC;
    UIViewController *_giudeVc;
    NSMutableArray *_selectArr;
    UIButton *_beginReader;
    UIView *_bgView;
    DMCustomBtn *_seleBtn;
    UIButton *_sureBtn;
    UIButton *_decMan;
    UIButton *_decMan1;
    UIView *_sexView;
}

- (void).cxx_destruct;
- (void)WNYD_buildHobby;
- (void)WNYD_buildSelectBtn:(id)arg1 origin:(double)arg2 view:(id)arg3 color:(id)arg4;
- (void)WNYD_buildWithSex:(id)arg1 origin:(double)arg2 view:(id)arg3;
- (void)WNYD_chooseSex;
- (void)WNYD_clcikhobbyBtn:(id)arg1;
- (void)WNYD_clickJump;
- (void)WNYD_clickMan;
- (void)WNYD_clickSelectBtn:(id)arg1;
- (void)WNYD_clickSexBtn:(id)arg1;
- (void)WNYD_clickSureBtn:(id)arg1;
- (void)WNYD_clickWoman;
- (void)WNYD_setupGuideFuc;
- (void)WNYD_showPrivacy;
- (void)WNYD_starBtn:(id)arg1;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
@property(nonatomic) __weak UIButton *beginReader; // @synthesize beginReader=_beginReader;
@property(nonatomic) __weak UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) UIViewController *chooseSexVC; // @synthesize chooseSexVC=_chooseSexVC;
- (void)clickAgree;
- (void)clickBeginBt;
- (void)clickdisAgree;
@property(nonatomic) __weak UIButton *decMan; // @synthesize decMan=_decMan;
@property(nonatomic) __weak UIButton *decMan1; // @synthesize decMan1=_decMan1;
- (void)didReceiveMemoryWarning;
@property(retain, nonatomic) UIViewController *giudeVc; // @synthesize giudeVc=_giudeVc;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)scrollViewDidScroll:(id)arg1;
@property(nonatomic) __weak DMCustomBtn *seleBtn; // @synthesize seleBtn=_seleBtn;
@property(retain, nonatomic) NSMutableArray *selectArr; // @synthesize selectArr=_selectArr;
@property(retain, nonatomic) UIView *sexView; // @synthesize sexView=_sexView;
@property(nonatomic) __weak UIButton *sureBtn; // @synthesize sureBtn=_sureBtn;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

