//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSLayoutConstraint, NSString, UIImageView, UILabel, UIView, WNYD_HotRankBookModel, YBookModel;

@interface WNYD_BookDetailCell : UITableViewCell
{
    _Bool _isRank;
    long long _rankCount;
    NSString *_keyWord;
    YBookModel *_bookModel;
    YBookModel *_rankModel;
    WNYD_HotRankBookModel *_hotRankModel;
    NSLayoutConstraint *_rankRight;
    NSLayoutConstraint *_imageX;
    NSLayoutConstraint *_detilRight;
    UILabel *_rankLabel;
    UIImageView *_bookImage;
    UILabel *_titleLabel;
    UILabel *_authorLabel;
    UILabel *_shortIntroLabel;
    UIView *_lineView;
    NSLayoutConstraint *_imageTop;
    NSLayoutConstraint *_imageBottom;
    NSLayoutConstraint *_titleX;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UILabel *authorLabel; // @synthesize authorLabel=_authorLabel;
- (void)awakeFromNib;
@property(nonatomic) __weak UIImageView *bookImage; // @synthesize bookImage=_bookImage;
@property(retain, nonatomic) YBookModel *bookModel; // @synthesize bookModel=_bookModel;
- (void)buildSelectColorWithLabel:(id)arg1 text:(id)arg2 color:(id)arg3;
@property(nonatomic) __weak NSLayoutConstraint *detilRight; // @synthesize detilRight=_detilRight;
@property(retain, nonatomic) WNYD_HotRankBookModel *hotRankModel; // @synthesize hotRankModel=_hotRankModel;
@property(nonatomic) __weak NSLayoutConstraint *imageBottom; // @synthesize imageBottom=_imageBottom;
@property(nonatomic) __weak NSLayoutConstraint *imageTop; // @synthesize imageTop=_imageTop;
@property(nonatomic) __weak NSLayoutConstraint *imageX; // @synthesize imageX=_imageX;
@property(nonatomic) _Bool isRank; // @synthesize isRank=_isRank;
@property(copy, nonatomic) NSString *keyWord; // @synthesize keyWord=_keyWord;
@property(nonatomic) __weak UIView *lineView; // @synthesize lineView=_lineView;
@property(nonatomic) long long rankCount; // @synthesize rankCount=_rankCount;
@property(nonatomic) __weak UILabel *rankLabel; // @synthesize rankLabel=_rankLabel;
@property(retain, nonatomic) YBookModel *rankModel; // @synthesize rankModel=_rankModel;
@property(nonatomic) __weak NSLayoutConstraint *rankRight; // @synthesize rankRight=_rankRight;
@property(nonatomic) __weak UILabel *shortIntroLabel; // @synthesize shortIntroLabel=_shortIntroLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak NSLayoutConstraint *titleX; // @synthesize titleX=_titleX;

@end

