//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, UIImageView, UILabel;

@interface WNYD_DiscBookCell : UITableViewCell
{
    NSString *_iconImage;
    NSString *_iconTitle;
    UIImageView *_iconImageView;
    UILabel *_iconNameLabel;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *iconImage; // @synthesize iconImage=_iconImage;
@property(nonatomic) __weak UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic) __weak UILabel *iconNameLabel; // @synthesize iconNameLabel=_iconNameLabel;
@property(copy, nonatomic) NSString *iconTitle; // @synthesize iconTitle=_iconTitle;

@end

