//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class WKWebView;

@interface WNYD_SecretViewController : UIViewController
{
    _Bool _isPush;
    _Bool _isPrivacy;
    _Bool _isUser;
    _Bool _isUpdate;
    WKWebView *_webView;
}

- (void).cxx_destruct;
- (void)WNYD_consent;
- (void)back;
- (void)buildNav;
- (void)didReceiveMemoryWarning;
@property(nonatomic) _Bool isPrivacy; // @synthesize isPrivacy=_isPrivacy;
@property(nonatomic) _Bool isPush; // @synthesize isPush=_isPush;
@property(nonatomic) _Bool isUpdate; // @synthesize isUpdate=_isUpdate;
@property(nonatomic) _Bool isUser; // @synthesize isUser=_isUser;
@property(nonatomic) __weak WKWebView *webView; // @synthesize webView=_webView;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

@end

