//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewFlowLayout.h>

@class NSArray, NSMutableArray;

@interface WNYD_CollectionViewLayout : UICollectionViewFlowLayout
{
    NSArray *_dataArr;
    long long _style;
    NSMutableArray *_layoutAttrArr;
    double _maxHeight;
}

- (void).cxx_destruct;
- (struct CGSize)collectionViewContentSize;
@property(retain, nonatomic) NSArray *dataArr; // @synthesize dataArr=_dataArr;
- (id)initWithStyle:(long long)arg1;
@property(retain, nonatomic) NSMutableArray *layoutAttrArr; // @synthesize layoutAttrArr=_layoutAttrArr;
- (id)layoutAttributesForElementsInRect:(struct CGRect)arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForSupplementaryViewOfKind:(id)arg1 atIndexPath:(id)arg2;
@property(nonatomic) double maxHeight; // @synthesize maxHeight=_maxHeight;
- (void)prepareLayout;
@property(nonatomic) long long style; // @synthesize style=_style;
- (void)setupRecommendViewLayout;
- (void)setupTagViewLayout;

@end

