//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class LOTAnimationView;

@interface WNYD_BaseTableViewController : UITableViewController
{
    _Bool _isFirstLoading;
    _Bool _canShowLoading;
    LOTAnimationView *_loadImageView;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool canShowLoading; // @synthesize canShowLoading=_canShowLoading;
- (void)hideLoadingView;
- (id)init;
@property(nonatomic) _Bool isFirstLoading; // @synthesize isFirstLoading=_isFirstLoading;
@property(nonatomic) __weak LOTAnimationView *loadImageView; // @synthesize loadImageView=_loadImageView;
- (void)setLoadingY:(double)arg1;
- (void)showLoadingView;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;

@end

