//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WNYD_BaseSettingViewController.h"

@class NSArray, NSURLSessionTask, SPAlertAction, UITextField, WNYD_NetworkManager, WNYD_SQLiteManager;

@interface WNYD_SettingViewController : WNYD_BaseSettingViewController
{
    CDUnknownBlockType _logoutBlock;
    WNYD_NetworkManager *_netManager;
    NSURLSessionTask *_UserFavSynTask;
    WNYD_SQLiteManager *_sqliteM;
    NSArray *_booksArr;
    SPAlertAction *_sureAction;
    UITextField *_passWordTextField;
    double _totalSize;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSURLSessionTask *UserFavSynTask; // @synthesize UserFavSynTask=_UserFavSynTask;
- (void)WNYD_getBookCache;
- (double)WNYD_getBookCacheWithRecordkey:(id)arg1 patchArr:(id)arg2;
@property(retain, nonatomic) NSArray *booksArr; // @synthesize booksArr=_booksArr;
- (void)clickColor;
- (void)dealloc;
- (void)landQuit;
@property(copy, nonatomic) CDUnknownBlockType logoutBlock; // @synthesize logoutBlock=_logoutBlock;
@property(retain, nonatomic) WNYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
- (long long)numberOfSectionsInTableView:(id)arg1;
@property(retain, nonatomic) UITextField *passWordTextField; // @synthesize passWordTextField=_passWordTextField;
- (void)quit;
@property(retain, nonatomic) WNYD_SQLiteManager *sqliteM; // @synthesize sqliteM=_sqliteM;
@property(retain, nonatomic) SPAlertAction *sureAction; // @synthesize sureAction=_sureAction;
@property(nonatomic) double totalSize; // @synthesize totalSize=_totalSize;
- (void)setUpData;
- (void)setUpGroup1;
- (void)setUpGroup2;
- (void)setUpGroup3;
- (void)setUpGroup4;
- (void)setUpGroup5;
- (void)setUpGroup6;
- (void)showBookShelfSortStyle;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tapFooterView:(id)arg1;
- (void)textFieldDidChanged:(id)arg1;
- (void)updateUserNickPassword;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

@end

