//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "JXCategoryViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class FDDemoScrollView, JXCategoryBaseView, NSString;

@interface WNYD_PagingBaseViewController : UIViewController <JXCategoryViewDelegate, UIScrollViewDelegate>
{
    _Bool _isNeedIndicatorPositionChangeItem;
    JXCategoryBaseView *_categoryView;
    FDDemoScrollView *_scrollView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) JXCategoryBaseView *categoryView; // @synthesize categoryView=_categoryView;
- (void)categoryView:(id)arg1 didSelectedItemAtIndex:(long long)arg2;
- (void)configListViewController:(id)arg1 index:(unsigned long long)arg2;
@property(nonatomic) _Bool isNeedIndicatorPositionChangeItem; // @synthesize isNeedIndicatorPositionChangeItem=_isNeedIndicatorPositionChangeItem;
- (Class)preferredCategoryViewClass;
- (double)preferredCategoryViewHeight;
- (unsigned long long)preferredListViewCount;
- (void)rightItemClicked;
@property(retain, nonatomic) FDDemoScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

