//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SelectChannelCellDeleteDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class DMCustomBtn, NSMutableArray, NSString, UIButton, UICollectionView, UILabel, UIView;

@interface WNYD_SelectChannelContreller : UIViewController <UICollectionViewDelegate, UICollectionViewDataSource, SelectChannelCellDeleteDelegate>
{
    NSMutableArray *_myTags;
    NSMutableArray *_recommandTags;
    UIButton *_editBtn;
    UILabel *_myLabelTips;
    _Bool _onEdit;
    _Bool _tagDeletable;
    _Bool _isChange;
    UICollectionView *_mainView;
    NSMutableArray *_myChannels;
    NSMutableArray *_recommandChannels;
    CDUnknownBlockType _choosedTags;
    CDUnknownBlockType _selectedTag;
    NSString *_curtSelTags;
    CDUnknownBlockType _ChangeTags;
    CDUnknownBlockType _AddOrRemoveTags;
    UIView *_backView;
    UIView *_lineView;
    NSMutableArray *_cellAttributesArray;
    DMCustomBtn *_exit;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType AddOrRemoveTags; // @synthesize AddOrRemoveTags=_AddOrRemoveTags;
@property(copy, nonatomic) CDUnknownBlockType ChangeTags; // @synthesize ChangeTags=_ChangeTags;
@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(retain, nonatomic) NSMutableArray *cellAttributesArray; // @synthesize cellAttributesArray=_cellAttributesArray;
@property(copy, nonatomic) CDUnknownBlockType choosedTags; // @synthesize choosedTags=_choosedTags;
- (_Bool)collectionView:(id)arg1 canMoveItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 moveItemAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
@property(copy, nonatomic) NSString *curtSelTags; // @synthesize curtSelTags=_curtSelTags;
- (void)deleteCell:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)doPan:(id)arg1;
- (void)editTags:(id)arg1;
@property(retain, nonatomic) DMCustomBtn *exit; // @synthesize exit=_exit;
- (id)initWithMyTags:(id)arg1 andRecommandTags:(id)arg2;
@property(nonatomic) _Bool isChange; // @synthesize isChange=_isChange;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
- (void)longPress:(id)arg1;
@property(retain, nonatomic) UICollectionView *mainView; // @synthesize mainView=_mainView;
- (void)makeTags;
@property(retain, nonatomic) NSMutableArray *myChannels; // @synthesize myChannels=_myChannels;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)preferredStatusBarStyle;
@property(retain, nonatomic) NSMutableArray *recommandChannels; // @synthesize recommandChannels=_recommandChannels;
- (void)refreshDelBtnsTag;
- (void)returnLast;
- (void)saveData;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType selectedTag; // @synthesize selectedTag=_selectedTag;
- (void)setupViews;
- (void)showClose;
- (void)showFeatureView;
- (void)stopPanGesture;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

