//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "WNYD_AdvertContentViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UICollectionView, UICollectionViewFlowLayout, UIImageView, UIScrollView, UIView, WNYD_AdvertConfigModel, WNYD_BookCategories, WNYD_NetworkManager;

@interface WNYD_TypeContentController : UIViewController <UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout, UIScrollViewDelegate, WNYD_AdvertContentViewDelegate>
{
    _Bool _TopADLoad;
    _Bool _MiddleADLoad;
    _Bool _BottomADLoad;
    _Bool _isDataload;
    NSString *_sexName;
    WNYD_BookCategories *_typeModel;
    WNYD_NetworkManager *_netManager;
    UIScrollView *_ContainerScrollView;
    UIView *_typeHeaderContentView;
    NSMutableArray *_editorBooksArr;
    UICollectionViewFlowLayout *_editorFlowLayout;
    UICollectionView *_editorCollectionView;
    UIView *_editorContentView;
    NSMutableArray *_weekBooksArr;
    UICollectionViewFlowLayout *_weekFlowLayout;
    UICollectionView *_weekCollectionView;
    UIView *_weekContentView;
    NSMutableArray *_NewBooksArr;
    UICollectionViewFlowLayout *_NewFlowLayout;
    UICollectionView *_NewCollectionView;
    UIView *_NewContentView;
    NSMutableArray *_serializeBooksArr;
    UICollectionViewFlowLayout *_serializeFlowLayout;
    UICollectionView *_serializeCollectionView;
    UIView *_serializeContentView;
    NSMutableArray *_endBooksArr;
    UICollectionViewFlowLayout *_endFlowLayout;
    UICollectionView *_endCollectionView;
    UIView *_endContentView;
    NSMutableArray *_sellBooksArr;
    UICollectionViewFlowLayout *_sellFlowLayout;
    UICollectionView *_sellCollectionView;
    UIView *_sellContentView;
    UICollectionViewFlowLayout *_headFlowLayout;
    UICollectionView *_headCollectionView;
    UIImageView *_typeContentLoadingImageView;
    UIView *_BookStoreBottomView;
    WNYD_AdvertConfigModel *_topModel;
    WNYD_AdvertConfigModel *_middleModel;
    WNYD_AdvertConfigModel *_bottomModel;
    UIView *_topADContentView;
    UIView *_middleADContentView;
    UIView *_bottomADContentView;
    double _topInfoHeight;
    double _middleInfoHeight;
    double _bottomInfoHeight;
    NSMutableArray *_ADSModelArr;
    UIView *_topADView;
    UIView *_middleADView;
    UIView *_bottomADView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *ADSModelArr; // @synthesize ADSModelArr=_ADSModelArr;
@property(retain, nonatomic) UIView *BookStoreBottomView; // @synthesize BookStoreBottomView=_BookStoreBottomView;
@property(nonatomic) _Bool BottomADLoad; // @synthesize BottomADLoad=_BottomADLoad;
@property(retain, nonatomic) UIScrollView *ContainerScrollView; // @synthesize ContainerScrollView=_ContainerScrollView;
- (void)CreatUI;
@property(nonatomic) _Bool MiddleADLoad; // @synthesize MiddleADLoad=_MiddleADLoad;
@property(retain, nonatomic) NSMutableArray *NewBooksArr; // @synthesize NewBooksArr=_NewBooksArr;
@property(retain, nonatomic) UICollectionView *NewCollectionView; // @synthesize NewCollectionView=_NewCollectionView;
@property(retain, nonatomic) UIView *NewContentView; // @synthesize NewContentView=_NewContentView;
@property(retain, nonatomic) UICollectionViewFlowLayout *NewFlowLayout; // @synthesize NewFlowLayout=_NewFlowLayout;
- (void)RefreshDataWithNetCheck;
@property(nonatomic) _Bool TopADLoad; // @synthesize TopADLoad=_TopADLoad;
- (void)WNYD_addLoadingPage;
- (void)WNYD_initAllInfoADSDK;
- (void)WNYD_isCanShowAD:(_Bool)arg1;
- (void)WNYD_loadTypeContentData;
@property(retain, nonatomic) UIView *bottomADContentView; // @synthesize bottomADContentView=_bottomADContentView;
@property(retain, nonatomic) UIView *bottomADView; // @synthesize bottomADView=_bottomADView;
@property(nonatomic) double bottomInfoHeight; // @synthesize bottomInfoHeight=_bottomInfoHeight;
@property(retain, nonatomic) WNYD_AdvertConfigModel *bottomModel; // @synthesize bottomModel=_bottomModel;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)creatNetErrorPage;
- (void)dealloc;
@property(retain, nonatomic) NSMutableArray *editorBooksArr; // @synthesize editorBooksArr=_editorBooksArr;
@property(retain, nonatomic) UICollectionView *editorCollectionView; // @synthesize editorCollectionView=_editorCollectionView;
@property(retain, nonatomic) UIView *editorContentView; // @synthesize editorContentView=_editorContentView;
@property(retain, nonatomic) UICollectionViewFlowLayout *editorFlowLayout; // @synthesize editorFlowLayout=_editorFlowLayout;
@property(retain, nonatomic) NSMutableArray *endBooksArr; // @synthesize endBooksArr=_endBooksArr;
@property(retain, nonatomic) UICollectionView *endCollectionView; // @synthesize endCollectionView=_endCollectionView;
@property(retain, nonatomic) UIView *endContentView; // @synthesize endContentView=_endContentView;
@property(retain, nonatomic) UICollectionViewFlowLayout *endFlowLayout; // @synthesize endFlowLayout=_endFlowLayout;
- (id)getADConfigModelWith:(id)arg1;
@property(retain, nonatomic) UICollectionView *headCollectionView; // @synthesize headCollectionView=_headCollectionView;
@property(retain, nonatomic) UICollectionViewFlowLayout *headFlowLayout; // @synthesize headFlowLayout=_headFlowLayout;
- (void)insertAdvertViewWithLocation:(long long)arg1;
@property(nonatomic) _Bool isDataload; // @synthesize isDataload=_isDataload;
@property(retain, nonatomic) UIView *middleADContentView; // @synthesize middleADContentView=_middleADContentView;
@property(retain, nonatomic) UIView *middleADView; // @synthesize middleADView=_middleADView;
@property(nonatomic) double middleInfoHeight; // @synthesize middleInfoHeight=_middleInfoHeight;
@property(retain, nonatomic) WNYD_AdvertConfigModel *middleModel; // @synthesize middleModel=_middleModel;
@property(retain, nonatomic) WNYD_NetworkManager *netManager; // @synthesize netManager=_netManager;
- (void)netWorkSolve;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)reloadMoreCollectonViewWithCato:(id)arg1 andTitleName:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
@property(retain, nonatomic) NSMutableArray *sellBooksArr; // @synthesize sellBooksArr=_sellBooksArr;
@property(retain, nonatomic) UICollectionView *sellCollectionView; // @synthesize sellCollectionView=_sellCollectionView;
@property(retain, nonatomic) UIView *sellContentView; // @synthesize sellContentView=_sellContentView;
@property(retain, nonatomic) UICollectionViewFlowLayout *sellFlowLayout; // @synthesize sellFlowLayout=_sellFlowLayout;
@property(retain, nonatomic) NSMutableArray *serializeBooksArr; // @synthesize serializeBooksArr=_serializeBooksArr;
@property(retain, nonatomic) UICollectionView *serializeCollectionView; // @synthesize serializeCollectionView=_serializeCollectionView;
@property(retain, nonatomic) UIView *serializeContentView; // @synthesize serializeContentView=_serializeContentView;
@property(retain, nonatomic) UICollectionViewFlowLayout *serializeFlowLayout; // @synthesize serializeFlowLayout=_serializeFlowLayout;
@property(retain, nonatomic) NSString *sexName; // @synthesize sexName=_sexName;
@property(retain, nonatomic) UIView *topADContentView; // @synthesize topADContentView=_topADContentView;
@property(retain, nonatomic) UIView *topADView; // @synthesize topADView=_topADView;
@property(nonatomic) double topInfoHeight; // @synthesize topInfoHeight=_topInfoHeight;
@property(retain, nonatomic) WNYD_AdvertConfigModel *topModel; // @synthesize topModel=_topModel;
@property(retain, nonatomic) UIImageView *typeContentLoadingImageView; // @synthesize typeContentLoadingImageView=_typeContentLoadingImageView;
@property(retain, nonatomic) UIView *typeHeaderContentView; // @synthesize typeHeaderContentView=_typeHeaderContentView;
@property(retain, nonatomic) WNYD_BookCategories *typeModel; // @synthesize typeModel=_typeModel;
- (void)setUpSubViewsUI;
@property(retain, nonatomic) NSMutableArray *weekBooksArr; // @synthesize weekBooksArr=_weekBooksArr;
@property(retain, nonatomic) UICollectionView *weekCollectionView; // @synthesize weekCollectionView=_weekCollectionView;
@property(retain, nonatomic) UIView *weekContentView; // @synthesize weekContentView=_weekContentView;
@property(retain, nonatomic) UICollectionViewFlowLayout *weekFlowLayout; // @synthesize weekFlowLayout=_weekFlowLayout;
- (void)showADContentWith:(id)arg1 andADHeight:(float)arg2 andIsLoadSuccess:(_Bool)arg3 andSelfView:(id)arg4;
- (void)typeButonCLick:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

