//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIPercentDrivenInteractiveTransition.h>

@class CADisplayLink, UIViewController;

@interface WXSPercentDrivenInteractiveTransition : UIPercentDrivenInteractiveTransition
{
    _Bool _isInter;
    long long _getstureType;
    long long _transitionType;
    CDUnknownBlockType _presentBlock;
    CDUnknownBlockType _pushBlock;
    CDUnknownBlockType _dismissBlock;
    CDUnknownBlockType _popBlock;
    CDUnknownBlockType _willEndInteractiveBlock;
    UIViewController *_vc;
    CADisplayLink *_displayLink;
    double _percent;
}

- (void).cxx_destruct;
- (void)UIChange;
- (void)addGestureToViewController:(id)arg1;
- (void)beganGesture;
- (void)continueAction;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(nonatomic) long long getstureType; // @synthesize getstureType=_getstureType;
@property(readonly, nonatomic) _Bool isInteractive;
- (void)panAction:(id)arg1;
@property(nonatomic) double percent; // @synthesize percent=_percent;
@property(copy, nonatomic) CDUnknownBlockType popBlock; // @synthesize popBlock=_popBlock;
@property(copy, nonatomic) CDUnknownBlockType presentBlock; // @synthesize presentBlock=_presentBlock;
@property(copy, nonatomic) CDUnknownBlockType pushBlock; // @synthesize pushBlock=_pushBlock;
@property(nonatomic) long long transitionType; // @synthesize transitionType=_transitionType;
@property(nonatomic) __weak UIViewController *vc; // @synthesize vc=_vc;
@property(copy, nonatomic) CDUnknownBlockType willEndInteractiveBlock; // @synthesize willEndInteractiveBlock=_willEndInteractiveBlock;

@end

