//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, UIView;

@interface XHLaunchAdConfiguration : NSObject
{
    _Bool _showEnterForeground;
    long long _duration;
    long long _skipButtonType;
    long long _showFinishAnimate;
    double _showFinishAnimateTime;
    NSString *_openURLString;
    id _openModel;
    UIView *_customSkipView;
    NSArray *_subViews;
    struct CGRect _frame;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *customSkipView; // @synthesize customSkipView=_customSkipView;
@property(nonatomic) long long duration; // @synthesize duration=_duration;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(retain, nonatomic) id openModel; // @synthesize openModel=_openModel;
@property(copy, nonatomic) NSString *openURLString; // @synthesize openURLString=_openURLString;
@property(nonatomic) _Bool showEnterForeground; // @synthesize showEnterForeground=_showEnterForeground;
@property(nonatomic) long long showFinishAnimate; // @synthesize showFinishAnimate=_showFinishAnimate;
@property(nonatomic) double showFinishAnimateTime; // @synthesize showFinishAnimateTime=_showFinishAnimateTime;
@property(nonatomic) long long skipButtonType; // @synthesize skipButtonType=_skipButtonType;
@property(copy, nonatomic) NSArray *subViews; // @synthesize subViews=_subViews;

@end

