//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XHLaunchAdConfiguration.h"

@class NSString;

@interface XHLaunchImageAdConfiguration : XHLaunchAdConfiguration
{
    _Bool _GIFImageCycleOnce;
    NSString *_imageNameOrURLString;
    long long _contentMode;
    unsigned long long _imageOption;
}

+ (id)defaultConfiguration;
- (void).cxx_destruct;
@property(nonatomic) _Bool GIFImageCycleOnce; // @synthesize GIFImageCycleOnce=_GIFImageCycleOnce;
@property(nonatomic) long long contentMode; // @synthesize contentMode=_contentMode;
@property(copy, nonatomic) NSString *imageNameOrURLString; // @synthesize imageNameOrURLString=_imageNameOrURLString;
@property(nonatomic) unsigned long long imageOption; // @synthesize imageOption=_imageOption;

@end

