//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSArray, NSNumber, NSString;

@interface YBaseModel : NSObject <NSCopying, NSCoding>
{
    _Bool _collapse;
    int _latelyFollower;
    int _wordCount;
    NSString *_idField;
    NSString *_cover;
    NSString *_image1;
    NSString *_cat;
    NSString *_lastChapter;
    NSString *_shortIntro;
    double _retentionRatio;
    NSString *_author;
    NSString *_title;
    NSString *_updated;
    NSString *_updatedTime;
    NSString *_status;
    NSString *_type;
    NSString *_lists_id;
    NSString *_ltype_id;
    NSString *_ltype_name;
    NSString *_image;
    NSString *_ltype_image;
    NSArray *_ltype_list;
    NSString *_source;
    NSString *_body;
    NSString *_link;
    NSString *_ranking_type;
    NSNumber *_is_liked;
    long long _likes_count;
    long long _comment_num;
    NSString *_ltype;
    NSString *_stype;
    NSString *_choose;
    NSString *_book_count;
    NSString *_site_name;
    NSString *_openUrl;
    NSString *_sex;
    NSString *_total_count;
    NSString *_rankPosition;
    long long _form;
    double _score;
}

+ (id)modelCustomPropertyMapper;
+ (void)requestModelDataWithUrlString:(id)arg1 complish:(CDUnknownBlockType)arg2 cachingPolicy:(unsigned long long)arg3 hubInView:(id)arg4;
+ (void)requestModelDataWithUrlString:(id)arg1 complish:(CDUnknownBlockType)arg2 useCache:(_Bool)arg3 saveCache:(_Bool)arg4 hubInView:(id)arg5;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *author; // @synthesize author=_author;
@property(retain, nonatomic) NSString *body; // @synthesize body=_body;
@property(copy, nonatomic) NSString *book_count; // @synthesize book_count=_book_count;
@property(retain, nonatomic) NSString *cat; // @synthesize cat=_cat;
@property(retain, nonatomic) NSString *choose; // @synthesize choose=_choose;
@property(nonatomic) _Bool collapse; // @synthesize collapse=_collapse;
@property(nonatomic) long long comment_num; // @synthesize comment_num=_comment_num;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) NSString *cover; // @synthesize cover=_cover;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
@property(nonatomic) long long form; // @synthesize form=_form;
- (unsigned long long)hash;
@property(retain, nonatomic) NSString *idField; // @synthesize idField=_idField;
@property(copy, nonatomic) NSString *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *image1; // @synthesize image1=_image1;
- (id)initWithCoder:(id)arg1;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic) NSNumber *is_liked; // @synthesize is_liked=_is_liked;
@property(retain, nonatomic) NSString *lastChapter; // @synthesize lastChapter=_lastChapter;
@property(nonatomic) int latelyFollower; // @synthesize latelyFollower=_latelyFollower;
@property(nonatomic) long long likes_count; // @synthesize likes_count=_likes_count;
@property(retain, nonatomic) NSString *link; // @synthesize link=_link;
@property(retain, nonatomic) NSString *lists_id; // @synthesize lists_id=_lists_id;
@property(retain, nonatomic) NSString *ltype; // @synthesize ltype=_ltype;
@property(copy, nonatomic) NSString *ltype_id; // @synthesize ltype_id=_ltype_id;
@property(copy, nonatomic) NSString *ltype_image; // @synthesize ltype_image=_ltype_image;
@property(copy, nonatomic) NSArray *ltype_list; // @synthesize ltype_list=_ltype_list;
@property(copy, nonatomic) NSString *ltype_name; // @synthesize ltype_name=_ltype_name;
@property(copy, nonatomic) NSString *openUrl; // @synthesize openUrl=_openUrl;
@property(retain, nonatomic) NSString *rankPosition; // @synthesize rankPosition=_rankPosition;
@property(retain, nonatomic) NSString *ranking_type; // @synthesize ranking_type=_ranking_type;
@property(nonatomic) double retentionRatio; // @synthesize retentionRatio=_retentionRatio;
@property(nonatomic) double score; // @synthesize score=_score;
@property(copy, nonatomic) NSString *sex; // @synthesize sex=_sex;
@property(retain, nonatomic) NSString *shortIntro; // @synthesize shortIntro=_shortIntro;
@property(copy, nonatomic) NSString *site_name; // @synthesize site_name=_site_name;
@property(retain, nonatomic) NSString *source; // @synthesize source=_source;
@property(retain, nonatomic) NSString *status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *stype; // @synthesize stype=_stype;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *total_count; // @synthesize total_count=_total_count;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *updated; // @synthesize updated=_updated;
@property(retain, nonatomic) NSString *updatedTime; // @synthesize updatedTime=_updatedTime;
@property(nonatomic) int wordCount; // @synthesize wordCount=_wordCount;
- (id)timeFormatted:(id)arg1;

@end

