//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YBaseModel.h"

#import "NSCoding-Protocol.h"

@class BUNativeAd, GADUnifiedNativeAd, NSArray, NSString, YDownloadModel;

@interface YBookDetailModel : YBaseModel <NSCoding>
{
    _Bool _le;
    _Bool _allowBeanVoucher;
    _Bool _allowMonthly;
    _Bool _allowVoucher;
    _Bool _donate;
    _Bool _hasCp;
    _Bool _isSerial;
    _Bool _hasSticky;
    _Bool _hasUpdated;
    _Bool _closeUpdated;
    _Bool _hasLoadCompletion;
    long long _chaptersCount;
    NSString *_copyright;
    NSString *_creater;
    long long _followerCount;
    NSArray *_gender;
    long long _latelyFollowerBase;
    NSString *_longIntro;
    NSString *_majorCate;
    long long _minRetentionRatio;
    NSString *_minorCate;
    long long _postCount;
    long long _serializeWordCount;
    NSArray *_tags;
    NSArray *_comment_info_list;
    NSArray *_author_book_list;
    NSArray *_relevant_book_list;
    NSArray *_sites;
    NSString *_is_top;
    NSString *_dateString;
    BUNativeAd *_nativBannerAd;
    GADUnifiedNativeAd *_googleNativBannerAd;
    long long _score_number;
    long long _view_count;
    long long _words_number;
    NSString *_last_crawler_book_id;
    NSArray *_notice_data;
    long long _source_count;
    long long _selectSummaryChapterCount;
    long long _selectSummaryReadingChapter;
    NSString *_lastReadingChapter;
    long long _is_fatten;
    long long _fatten_word_number;
    NSString *_reading_datetime;
    NSString *_reading_site_id;
    NSString *_reading_site_path;
    NSString *_reading_site_path_reload;
    NSString *_reading_chapter_key;
    YDownloadModel *_downloadM;
    long long _loadStatus;
    CDUnknownBlockType _loadProgress;
    CDUnknownBlockType _loadCompletion;
    CDUnknownBlockType _loadFailure;
    CDUnknownBlockType _loadCancel;
}

+ (id)modelCustomPropertyMapper;
+ (id)modelPropertyBlacklist;
- (void).cxx_destruct;
@property(nonatomic) _Bool allowBeanVoucher; // @synthesize allowBeanVoucher=_allowBeanVoucher;
@property(nonatomic) _Bool allowMonthly; // @synthesize allowMonthly=_allowMonthly;
@property(nonatomic) _Bool allowVoucher; // @synthesize allowVoucher=_allowVoucher;
@property(retain, nonatomic) NSArray *author_book_list; // @synthesize author_book_list=_author_book_list;
@property(nonatomic) long long chaptersCount; // @synthesize chaptersCount=_chaptersCount;
@property(nonatomic) _Bool closeUpdated; // @synthesize closeUpdated=_closeUpdated;
@property(retain, nonatomic) NSArray *comment_info_list; // @synthesize comment_info_list=_comment_info_list;
@property(retain, nonatomic) NSString *copyright; // @synthesize copyright=_copyright;
@property(retain, nonatomic) NSString *creater; // @synthesize creater=_creater;
@property(retain, nonatomic) NSString *dateString; // @synthesize dateString=_dateString;
@property(nonatomic) _Bool donate; // @synthesize donate=_donate;
@property(nonatomic) __weak YDownloadModel *downloadM; // @synthesize downloadM=_downloadM;
@property(nonatomic) long long fatten_word_number; // @synthesize fatten_word_number=_fatten_word_number;
@property(nonatomic) long long followerCount; // @synthesize followerCount=_followerCount;
@property(retain, nonatomic) NSArray *gender; // @synthesize gender=_gender;
- (id)getBookWordCount;
@property(retain, nonatomic) GADUnifiedNativeAd *googleNativBannerAd; // @synthesize googleNativBannerAd=_googleNativBannerAd;
@property(nonatomic) _Bool hasCp; // @synthesize hasCp=_hasCp;
@property(nonatomic) _Bool hasLoadCompletion; // @synthesize hasLoadCompletion=_hasLoadCompletion;
@property(nonatomic) _Bool hasSticky; // @synthesize hasSticky=_hasSticky;
@property(nonatomic) _Bool hasUpdated; // @synthesize hasUpdated=_hasUpdated;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic) _Bool isSerial; // @synthesize isSerial=_isSerial;
@property(nonatomic) long long is_fatten; // @synthesize is_fatten=_is_fatten;
@property(retain, nonatomic) NSString *is_top; // @synthesize is_top=_is_top;
@property(copy, nonatomic) NSString *lastReadingChapter; // @synthesize lastReadingChapter=_lastReadingChapter;
@property(copy, nonatomic) NSString *last_crawler_book_id; // @synthesize last_crawler_book_id=_last_crawler_book_id;
@property(nonatomic) long long latelyFollowerBase; // @synthesize latelyFollowerBase=_latelyFollowerBase;
@property(nonatomic) _Bool le; // @synthesize le=_le;
@property(copy, nonatomic) CDUnknownBlockType loadCancel; // @synthesize loadCancel=_loadCancel;
@property(copy, nonatomic) CDUnknownBlockType loadCompletion; // @synthesize loadCompletion=_loadCompletion;
@property(copy, nonatomic) CDUnknownBlockType loadFailure; // @synthesize loadFailure=_loadFailure;
@property(copy, nonatomic) CDUnknownBlockType loadProgress; // @synthesize loadProgress=_loadProgress;
@property long long loadStatus; // @synthesize loadStatus=_loadStatus;
@property(retain, nonatomic) NSString *longIntro; // @synthesize longIntro=_longIntro;
@property(retain, nonatomic) NSString *majorCate; // @synthesize majorCate=_majorCate;
@property(nonatomic) long long minRetentionRatio; // @synthesize minRetentionRatio=_minRetentionRatio;
@property(retain, nonatomic) NSString *minorCate; // @synthesize minorCate=_minorCate;
@property(retain, nonatomic) BUNativeAd *nativBannerAd; // @synthesize nativBannerAd=_nativBannerAd;
@property(retain, nonatomic) NSArray *notice_data; // @synthesize notice_data=_notice_data;
@property(nonatomic) long long postCount; // @synthesize postCount=_postCount;
@property(copy, nonatomic) NSString *reading_chapter_key; // @synthesize reading_chapter_key=_reading_chapter_key;
@property(copy, nonatomic) NSString *reading_datetime; // @synthesize reading_datetime=_reading_datetime;
@property(copy, nonatomic) NSString *reading_site_id; // @synthesize reading_site_id=_reading_site_id;
@property(copy, nonatomic) NSString *reading_site_path; // @synthesize reading_site_path=_reading_site_path;
@property(copy, nonatomic) NSString *reading_site_path_reload; // @synthesize reading_site_path_reload=_reading_site_path_reload;
@property(retain, nonatomic) NSArray *relevant_book_list; // @synthesize relevant_book_list=_relevant_book_list;
@property(nonatomic) long long score_number; // @synthesize score_number=_score_number;
@property(nonatomic) long long selectSummaryChapterCount; // @synthesize selectSummaryChapterCount=_selectSummaryChapterCount;
@property(nonatomic) long long selectSummaryReadingChapter; // @synthesize selectSummaryReadingChapter=_selectSummaryReadingChapter;
@property(nonatomic) long long serializeWordCount; // @synthesize serializeWordCount=_serializeWordCount;
@property(retain, nonatomic) NSArray *sites; // @synthesize sites=_sites;
@property(nonatomic) long long source_count; // @synthesize source_count=_source_count;
@property(retain, nonatomic) NSArray *tags; // @synthesize tags=_tags;
@property(nonatomic) long long view_count; // @synthesize view_count=_view_count;
@property(nonatomic) long long words_number; // @synthesize words_number=_words_number;

// Remaining properties
@property(nonatomic) double score;

@end

