//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class UIColor, UIFont, UIImageView;

@interface YeeBadgeLable : UILabel
{
    UIColor *m_pTextClolor;
    UIColor *m_pBackGroundClolor;
    UIFont *m_pLableFont;
    struct CGSize m_CMinSize;
    UIImageView *m_pBackImageView;
    long long m_tTextAlignment;
}

- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)init;
- (void)makeBrdgeViewWithCor:(double)arg1 CornerColor:(id)arg2;
- (void)makeBrdgeViewWithText:(id)arg1 textColor:(id)arg2 backColor:(id)arg3 textFont:(id)arg4 tframe:(struct CGRect)arg5;
- (struct CGSize)sizeWithString:(id)arg1 font:(id)arg2 constrainedToWidth:(double)arg3;

@end

