//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextPosition.h>

#import "NSCopying-Protocol.h"

@interface YYTextPosition : UITextPosition <NSCopying>
{
    long long _offset;
    long long _affinity;
}

+ (id)positionWithOffset:(long long)arg1;
+ (id)positionWithOffset:(long long)arg1 affinity:(long long)arg2;
@property(readonly, nonatomic) long long affinity; // @synthesize affinity=_affinity;
- (long long)compare:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) long long offset; // @synthesize offset=_offset;

@end

