//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "AutoReadToolBarDelegate-Protocol.h"

@class CADisplayLink, CAShapeLayer, NSString, UIImageView, UIView, ZQAutoReadToolBar;
@protocol ZQAutoViewDelegate;

@interface ZQAutoReadViewController : UIViewController <AutoReadToolBarDelegate>
{
    _Bool _isPaused;
    _Bool _isPanChange;
    id <ZQAutoViewDelegate> _delegate;
    CADisplayLink *_link;
    CAShapeLayer *_shapeLayer;
    UIImageView *_backImage;
    UIImageView *_shadowImage;
    double _topY;
    double _speed;
    ZQAutoReadToolBar *_toolBar;
    UIView *_tapView;
    double _PanChangeY;
}

- (void).cxx_destruct;
@property(nonatomic) double PanChangeY; // @synthesize PanChangeY=_PanChangeY;
- (void)addToolBar;
@property(retain, nonatomic) UIImageView *backImage; // @synthesize backImage=_backImage;
@property(nonatomic) __weak id <ZQAutoViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)endAutoRead;
- (void)getCurrent:(id)arg1;
- (id)init;
@property(nonatomic) _Bool isPanChange; // @synthesize isPanChange=_isPanChange;
@property(nonatomic) _Bool isPaused; // @synthesize isPaused=_isPaused;
@property(retain, nonatomic) CADisplayLink *link; // @synthesize link=_link;
- (void)setCurrentMaskLayer;
- (void)setCurrentShadowLayer;
@property(retain, nonatomic) UIImageView *shadowImage; // @synthesize shadowImage=_shadowImage;
@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
@property(nonatomic) double speed; // @synthesize speed=_speed;
@property(retain, nonatomic) UIView *tapView; // @synthesize tapView=_tapView;
@property(retain, nonatomic) ZQAutoReadToolBar *toolBar; // @synthesize toolBar=_toolBar;
@property(nonatomic) double topY; // @synthesize topY=_topY;
- (void)singlePan:(id)arg1;
- (void)singleTap;
- (void)speedLow:(double)arg1;
- (void)speedUp:(double)arg1;
- (void)startAuto;
- (void)updateLayer;
- (void)updateWithView:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

